#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=devhelp
version=2.32.0
group=Desktops/gnome2
license=GPLv2
description="API documentation browser"
src="d/devhelp/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Devhelp's primary goal is to be an API documentation browser for
GNOME. When you build (or install) a GNOME library, it will build an
API reference for you and install it into:

  $datadir/gtk-doc/html/$PACKAGE. 

Along with the HTML files, a .devhelp and/or .devhelp2 index file is
also generated automatically. Thus Devhelp can simply scan that folder
for those index files and display the books they represent.
EOF
}

# '

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
