#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=gdl
version=2.31.3
group=Desktops/gnome2
license=LGPLv2
description="GTK+ Docking Library"
src="g/gdl/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Provides docking features for gtk+. Currently used by anjuta and lumiera.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
