#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=libgda
version=4.1.11
group=Desktops/gnome2
license=LGPLv2/GPLv2
description="GNU Data Access library"
src="l/libgda/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
GNU Data Access (GDA) is an attempt to provide uniform access to different kinds
of data sources (databases, information servers, mail spools, etc). It is a
complete architecture that provides all you need to access your data. It is
defined by a set of plugin APIs as generic as possible (but very powerful at the
same time) so that any kind of data source can be accessed through them.

libgda is an interface to the GDA architecture, providing a nice wrapper around
the GDA interfaces, for both the client and the server parts. It also provides a
bunch of tools to help you both in the development and management of your data
sources, all done through the GDA model's interfaces.

libgda was part of the GNOME-DB project but has been separated from it to allow
non-GNOME applications to be developed based on it.
EOF
}

# '

buildPhase()
{
    local extraArgs=

    if odbc_config --version
    then
        extraArgs="--with-odbc=/opt/unixODBC"
    fi

    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --disable-introspection $extraArgs
    make
}

installPhase()
{
    make install

    # Categorize the GDA desktop menu items as GNOME-specific
    sed -i 's/Categories=/Categories=GNOME;/' /opt/gnome-$gnome2Version/share/applications/gda-browser-4.0.desktop
    sed -i 's/Categories=/Categories=GNOME;/' /opt/gnome-$gnome2Version/share/applications/gda-control-center-4.0.desktop
}
