#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=facile
version=1.1
group=Libraries/OCaml
license=LGPLv2.1
description="Functional constraint library"
src="f/facile/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
FaCiLe is a Functional Constraint Library implemented in Objective Caml.
EOF
}

buildPhase()
{
    ./configure
    make
}

installPhase()
{
    make install
}
