#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=brasero
version=2.32.1
group=Desktops/gnome2
license=GPLv2
description="Brasero CD/DVD mastering tool"
src="b/brasero/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Brasero is a CD/DVD mastering tool for the GNOME Desktop. It is designed to be simple and easy to use. 

Features:

Data CD/DVD:
- supports edition of discs contents (remove/move/rename files inside directories)
- can burn data CD/DVD on the fly
- automatic filtering for unwanted files (hidden files, broken/recursive symlinks, files not conforming to joliet standard, ...)
- supports multisession
- supports joliet extension
- can write the image to the hard drive

Audio CD:
- write CD-TEXT information (automatically found thanks to gstreamer)
- supports the edition of CD-TEXT information
- can burn audio CD on the fly
- can use all audio files handled by GStreamer local installation (ogg, flac, mp3, ...)
- can search for audio files inside dropped folders 
- can insert a pause
- can split a track

CD/DVD copy:
- can copy a CD/DVD to the hard drive
- can copy DVD and CD on the fly
- supports single-session data DVD
- supports any kind of CD
- can copy encrypted Video DVDs (needs libdvdcss)

Others:
- erase CD/DVD
- can save/load projects
- can burn CD/DVD images and cue files
- song, image and video previewer
- device detection thanks to HAL
- file change notification (requires kernel > 2.6.13)
- supports Drag and Drop / Cut'n'Paste from nautilus (and others apps)
- can use files on a network as long as the protocol is handled by gnome-vfs
- can search for files thanks to beagle (search is based on keywords or on file type)
- can display a playlist and its contents (note that playlists are automatically searched through beagle)
- all disc IO is done asynchronously to prevent the application from blocking
- Brasero default backend is provided by cdrtools/cdrkit but libburn can be used as an alternative
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
