#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=bug-buddy
version=2.32.0
group=Desktops/gnome2
license=GPLv2
description="Bug buddy"
src="b/bug-buddy/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
bug-buddy can extract debugging information from a crashed application and
create either a stacktrace or a minidump file to send to the GNOME
bug tracker.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --localstatedir=/var/lib \
        --mandir=/opt/gnome-$gnome2Version/share/man
    make $globalBuildOptions
}

installPhase()
{
    make install
}
