#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=dasher
version=4.11
group=Desktops/gnome2
license=GPLv2
description="Dasher"
src="d/dasher/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Dasher is a zooming predictive text entry system, designed for situations
where keyboard input is impractical (for instance, accessibility or PDAs). It
is usable with highly limited amounts of physical input while still allowing
high rates of text entry.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
