#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=evolution
version=2.32.1
group=Desktops/gnome2
license=LGPLv2/LGPLv3/GPLv2
description="Evolution mail client and calendar"
src="e/evolution/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Evolution is the integrated mail, calendar and address book suite from the
Evolution Team.
EOF
}

buildPhase()
{
    local extraArgs=

    if mono --version
    then
        extraArgs="--enable-mono"
    fi

    if python --version
    then
        extraArgs="$extraArgs --enable-python"
    fi

    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --localstatedir=/var/lib \
        --libexecdir=/opt/gnome-$gnome2Version/lib \
        --enable-nss \
        --enable-smime \
        --disable-nm \
        $extraArgs
    make $globalBuildOptions
}

installPhase()
{
    make install
}
