#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=evolution-data-server
version=2.32.1
group=Desktops/gnome2
license=LGPLv2
description="Evolution Data Server"
src="e/evolution-data-server/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The Evolution Data Server package provides a unified backend for programs that
work with contacts, tasks, and calendar information. It was originally developed
for Evolution (hence the name), but is now used by other packages as well.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --libexecdir=/opt/gnome-$gnome2Version/lib/evolution-data-server-1.2 \
        --enable-nntp \
        --enable-gnome-keyring \
        --enable-nss \
        --enable-smime
    make $globalBuildOptions
}

installPhase()
{
    make install
}
