#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=folks
version=0.2.1
group=Desktops/gnome2
license=LGPLv2.1
description="Folks aggregator"
src="f/folks/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
libfolks is a library that aggregates people from multiple sources (eg,
Telepathy connection managers) to create metacontacts.

This source distribution also builds a Telepathy backend
(libfolks-telepathy-backend.so) and Telepathy-specific implementations of the
libfolks classes (libfolks-telepathy.so).
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
