#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gcalctool
version=5.32.1
group=Desktops/gnome2
license=GPLv2
description="Calculator application"
src="g/gcalctool/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
gcalctool is a calculator application that was previously in the OpenWindows
Deskset of the Solaris 8 operating system.

It incorporates a multiple precision arithmetic packages based on the work of
Professor Richard Brent.

There is a single graphics driver for Gtk2 included with this release.

EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --localstatedir=/var/lib \
        --mandir=/opt/gnome-$gnome2Version/share/man
    make $globalBuildOptions
}

installPhase()
{
    make install
}
