#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gconf-editor
version=2.32.0
group=Desktops/gnome2
license=GPLv2
description="GConf editor"
src="g/gconf-editor/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
An editor for the GConf configuration system.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --localstatedir=/var/lib
    make $globalBuildOptions
}

installPhase()
{
    make install
}
