#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gedit
version=2.30.4
group=Desktops/gnome2
license=GPLv2
description="GNOME Editor"
src="g/gedit/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
gedit is a small and lightweight UTF-8 text editor for the GNOME environment.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --libexecdir=/opt/gnome-$gnome2Version/lib/gedit-2 \
        --localstatedir=/var/lib
    make $globalBuildOptions
}

installPhase()
{
    make install
}
