#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-icon-theme
version=2.31.0
group=Desktops/gnome2
license=LGPLv3/CC-BY-SA-3.0
description="GNOME Icon Theme"
src="g/gnome-icon-theme/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The GNOME Icon Theme package contains an assortment of scalable and
non-scalable icons of different sizes and themes.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
