#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-user-share
version=2.30.1
group=Desktops/gnome2
license=GPLv2
description="GNOME User Share"
src="g/gnome-user-share/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
gnome-user-share is a small package that binds together various free
software projects to bring easy to use user-level file sharing to the
masses.
EOF
}


buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
	--libexecdir=/opt/gnome-$gnome2Version/lib/gnome-user-share
    make $globalBuildOptions
}

installPhase()
{
    make install
}
