#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-terminal
version=2.32.1
group=Desktops/gnome2
license=GPLv3
description="GNOME Terminal"
src="g/gnome-terminal/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
This is the GNOME terminal emulator application. gnome-terminal is
only the shell (menubar, prefs dialog); the terminal emulation ("stuff
in the middle") comes from the VTE widget.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --localstatedir=/var/lib
    make $globalBuildOptions
}

installPhase()
{
    make install
}
