#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-packagekit
version=2.32.0
group=Desktops/gnome2
license=GPLv2
description="GNOME Package Kit"
src="g/gnome-packagekit/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
gnome-packagekit are PackageKit client programs designed for the GNOME desktop.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
