#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-icon-theme-symbolic
version=2.31.0
group=Desktops/gnome2
license=LGPLv3/CC-BY-SA-3.0
description="GNOME Icon Theme Symbolic"
src="g/gnome-icon-theme-symbolic/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Purpose of this icon theme is to extend the base icon theme that follows the
Tango style guidelines for specific purposes. This would include OSD messages,
panel system/notification area, and possibly menu icons. 

Icons follow the naming specification, but have a -symbolic suffix, so only
applications specifically looking up these symbolic icons will render them. If
a -symbolic icon is missing, the app will fall back to the regular name.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
