#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-utils
version=2.32.0
group=Desktops/gnome2
license=GPLv2
description="GNOME Utilities"
src="g/gnome-utils/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
GNOME Utilities for the GNOME 2.30 Desktop contains the following -

gnome-system-log     [logview]
gnome-search-tool    [gseachtool]
gnome-dictionary     [gnome-dictionary]
gnome-screenshot     [gnome-screenshot]
baobab               [baobab]
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --localstatedir=/var/lib \
        --libexecdir=/opt/gnome-$gnome2Version/lib/gnome-utils \
        --mandir=/opt/gnome-$gnome2Version/share/man
    make $globalBuildOptions
}

installPhase()
{
    make install
}
