#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-applets
version=2.32.0
group=Desktops/gnome2
license=LGPLv2
description="GNOME Applets"
src="g/gnome-applets/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
This package contains applets for use with the GNOME panel.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --localstatedir=/var/lib \
        --libexecdir=/opt/gnome-$gnome2Version/lib/gnome-applets \
        --mandir=/opt/gnome-$gnome2Version/share/man

    make $globalBuildOptions
}

installPhase()
{
    make install
}
