#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-system-tools
version=2.32.0
group=Desktops/gnome2
license=GPLv2
description="GMOME System Tools"
src="g/gnome-system-tools/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
- Targeted to desktop users:

  These tools are intended to simplify the tasks of configuring a Unix system
  for workstations. They are not intended for configuring Unix servers.

- Unified system configuration:

  Configuring different Unix systems is different; every Unix system has
  different ways of being administrated. The GNOME System Tools aspire to
  unify these systems.

- Multi-platform:

  Each one of the GNOME System Tools is split in two parts: a backend (which
  is typically written in Perl) and a user interface frontend (which is
  typically written in C or Python).

  The backends are written in a way that should allow us to quickly adapt
  them to various different flavors of Unix; the backend probes your system
  and parses the existing system files. When the user has finished editing
  the system settings, the configuration is written back as patches to the
  system files.

  This means that the GNOME System Tools use whatever configuration files are
  available on your system, and you can still edit those files by hand or
  with other configuration tools without conflicts or data loss.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
