#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-themes
version=2.32.1
group=Desktops/gnome2
license=LGPLv2.1
description="GNOME Themes"
src="g/gnome-themes/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The GNOME Themes package contains several more theme sets for GNOME.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version --enable-all-themes
    make $globalBuildOptions
}

installPhase()
{
    make install
}
