#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-session
version=2.32.1
group=Desktops/gnome2
license=GPLv2
description="GNOME Session"
src="g/gnome-session/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
gnome-session contains the GNOME session manager, as well as a
configuration program to choose applications starting on login.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --mandir=/opt/gnome-$gnome2Version/share/man \
        --with-at-spi-registryd=/opt/gnome-$gnome2Version/lib/at-spi
    make $globalBuildOptions
}

installPhase()
{
    make install

    # Add wrapper that sets the menu prefix. This wrapper can be used to
    # launch GNOME from an xinitrc or Xsession
    cat > /opt/gnome-$gnome2Version/bin/gnome-session-wrapper <<EOF
#!/bin/sh

export XDG_MENU_PREFIX="gnome-"
exec /opt/gnome-$gnome2Version/bin/gnome-session
EOF

    chmod 755 /opt/gnome-$gnome2Version/bin/gnome-session-wrapper

    # Add xinitrc option
    cat > /etc/X11/xinit/xinitrc.gnome << "EOF"
#!/bin/sh

exec dbus-launch --exit-with-session gnome-session-wrapper
EOF

    mkdir -p /usr/share/ul/ul-xinit
    cat > /usr/share/ul/ul-xinit/gnome << "EOF"
description="GNOME desktop environment"
EOF

    # Add xsession option for non XDG compliant display managers
    mkdir -p /usr/share/ul/ul-xsession/sessions
    install -m755 $cbtBaseDir/plugins/ul-xsession/sessions/gnome /usr/share/ul/ul-xsession/sessions

    # Add xsession option for XDG compliant display managers
    mkdir -p /etc/X11/sessions
    cat > /etc/X11/sessions/gnome.desktop <<EOF
[Desktop Entry]
Type=XSession
Exec=dbus-launch --exit-with-session /opt/gnome-$gnome2Version/bin/gnome-session-wrapper
Name=GNOME
Comment=The GNU Network Object Model Environment. A complete, free and easy-to-use desktop environment
EOF
}
