#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-system-monitor
version=2.28.2
group=Desktops/gnome2
license=GPLv2
description="GNOME System Monitor"
src="g/gnome-system-monitor/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The GNOME System Monitor package contains gnome-system-monitor, GNOME's
replacement for gtop.
EOF
}

# '

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --localstatedir=/var/lib
    make $globalBuildOptions
}

installPhase()
{
    make install
}
