#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-media
version=2.32.0
group=Desktops/gnome2
license=GPLv2
description="GNOME Media"
src="g/gnome-media/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
These are the GNOME media tools for GNOME 2.28 (and beyond):

gnome-volume-control    - PulseAudio based volume control applets.
grecord                 - GNOME Sound Recorder.
gstreamer-properties    - GStreamer Properties Capplet.
profiles                - Audio Profile library.
gst-mixer               - GNOME GStreamer-based audio mixer. (deprecated)
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --localstatedir=/var/lib \
        --libexecdir=/opt/gnome-$gnome2Version/lib/gnome-media
    make $globalBuildOptions
}

installPhase()
{
    make install
}
