#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libgtop
version=2.28.2
group=Desktops/gnome2
license=GPLv2
description="GNOME Top library"
src="l/libgtop/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The libgtop package contains the GNOME top libraries.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --infodir=/opt/gnome-$gnome2Version/share/info
    make $globalBuildOptions
}

installPhase()
{
    make install
}
