#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libgnomeprint
version=2.18.8
group=Desktops/gnome2
license=LGPLv2.1
description="GNOME printing library"
src="l/libgnomeprint/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The libgnomeprint package contains libgnomeprint libraries.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
