#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=liboobs
version=2.32.0
group=Desktops/gnome2
license=GPLv2
description="Object-Oriented wrapper for System Tools Backends"
src="l/liboobs/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Liboobs is a wrapping library to the System Tools Backends, it will provide easy
to access GObjects to system configuration details, like users, groups and
network interfaces, it will handle sessions with the backend and data
consistency too.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
