#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=pygtksourceview
version=2.10.1
group=Desktops/gnome2
license=LGPLv2
description="Python bindings for the GtkSourceView library"
src="p/pygtksourceview/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
This archive contains python bindings for the version 2 of the
GtkSourceView library.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
