#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=seahorse
version=2.32.0
group=Desktops/gnome2
license=GPLv2
description="Seahorse key manager GUI"
src="s/seahorse/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Seahorse is a graphical interface for managing and using encryption keys.
Currently it supports PGP keys (using GPG/GPGME) and SSH keys. Its goal is to
provide an easy to use Key Management Tool, along with an easy to use interface
for encryption operations.

Seahorse is integrated into the GNOME Desktop Environment and allows users to
perform operations from their regular applications, like nautilus or gedit.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
