#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=sound-juicer
version=2.32.0
group=Desktops/gnome2
license=GPLv2
description="Sound juicer"
src="s/sound-juicer/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Sound juicer is a CD ripping tool using GTK+ and GStreamer.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --localstatedir=/var/lib
    make $globalBuildOptions
}

installPhase()
{
    make install
}
