#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=swfdec-gnome
version=2.30.1
group=Desktops/gnome2
license=GPLv3
description="swfdec GNOME integration"
src="s/swfdec-gnome/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
This package contains programs to integrate Flash functionality into the GNOME
desktop. It's main application is swfdec-player, a stand-alone viewer for
Flash files. It also contains swfdec-thumbnailer, a program that provides
screenshots for files to display in the Nautilus file manager
EOF
}

# '

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
