#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=tomboy
version=1.4.2
group=Desktops/gnome2
license=LGPLv2.1
description="Desktop note-taking application"
src="t/tomboy/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Tomboy is a desktop note-taking application for Linux and Unix. Simple and
easy to use, but with potential to help you organize the ideas and
information you deal with every day.

Have you ever felt the frustration at not being able to locate a website you
wanted to check out, or find an email you found interesting, or remember an
idea about the direction of the political landscape in post-industrial
Australia? Or are you one of those desperate souls with home-made, buggy, or
not-quite-perfect notes systems?

Time for Tomboy. We bet you'll be surprised at how well a little application
can make life less cluttered and run more smoothly.
EOF
}

# '

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version
    make # $globalBuildOptions
}

installPhase()
{
    make install
}
