#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=yelp
version=2.30.2
group=Desktops/gnome2
license=GPLv2
description="Yelp"
src="y/yelp/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Yelp is the default help browser for the GNOME desktop. Yelp provides
a simple graphical interface for viewing DocBook, HTML, man, and info
formatted documentation.  The name Yelp was suggested by Daniel Lundin.
Yelp is pronounced the same as the swedish word for 'help'.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --localstatedir=/var/lib
    make
}

installPhase()
{
    make install
}
