#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libassuan
version=2.0.1
group=Libraries/Protocols
license=LGPLv2.1
description="IPC library used by GnuPG and other packages"
src="l/libassuan/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
This is the IPC library used by GnuPG 2, GPGME and a few other packages.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
