#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libcddb
version=1.3.2
group=Libraries/Protocols
license=LGPLv2
description="CDDB server access library"
src="l/libcddb/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Libcddb is a library that implements the different protocols (CDDBP,
HTTP, SMTP) to access data on a CDDB server (http://freedb.org). It
tries to be as cross-platform as possible. The initial libary will
have a C API.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
