#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libmusicbrainz
version=2.1.5
group=Libraries/Protocols
license=LGPLv2.1
description="Musicbrainz client library"
src="l/libmusicbrainz/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
The MusicBrainz Client Library (libmusicbrainz), also known as mb_client, is a
development library geared towards developers who wish to add MusicBrainz lookup
capabilities to their applications.
EOF
}

buildPhase()
{
    sed -i '1i\
#include <string.h>' lib/c_wrapper.cpp
    sed -i '1i\
#include <string.h>' lib/comhttpsocket.cpp
    sed -i '1i\
#include <string.h>' lib/comsocket.cpp
    sed -i '1i\
#include <string.h>' lib/http.cpp
    sed -i '1i\
#include <string.h>' lib/sigclient.cpp

    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
