#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=openslp
version=1.2.1
group=Libraries/Protocols
license=BSD-3
description="Service Location Protocol implementation"
src="o/openslp/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
The OpenSLP project is an effort to develop an open-source implementation of
Service Location Protocol suitable for commercial and non-commercial 
application.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
