#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=libticables2
version=1.2.0
group=Libraries/Protocols
license=GPLv2
description="TI cables library"
src="l/libticables2/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
This library is part of the TILP framework and provides support for a variety of
linking cables.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
