#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=libtifiles2
version=1.1.1
group=Libraries/Protocols
license=GPLv2
description="TI files library"
src="l/libtifiles2/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
This library is part of the TILP framework and provides support for file
transfers from and to Texas Instruments (TI) calculators.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
