#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=libticalcs2
version=1.1.2
group=Libraries/Protocols
license=GPLv2
description="TI calculators library"
src="l/libticalcs2/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
This library is part of the TILP framework and provides support for a variety of
Texas Instruments (TI) calculator models.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
