#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=w3m
version=0.5.3
group=Network/Clients
license=MIT
description="Textual web-browser"
src="w/w3m/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
 w3m is a pager with WWW capability. It IS a pager, but it can be
used as a text-mode WWW browser.

The features of w3m are as follows:

* When reading HTML document, you can follow links and view images
  (using external image viewer).
* It has 'internet message mode', which determines the type of document
  from header. If the Content-Type: field of the document is text/html,
  that document is displayed as HTML document.
* You can change URL description like 'http://hogege.net' in plain text
  into link to that URL.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --libexecdir=/usr/lib/w3m
    make $globalBuildOptions
}

installPhase()
{
    make install
}
