#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/bzip2

group=lfs-stage1

buildPhase()
{
    make
}

installPhase()
{
    make PREFIX=/stage1 install
}
