#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/gcc

group=lfs-stage1
patches=("g/gcc/$name-$version-2.patch.bz2" "g/gcc/$name-$version-no_fixinc-1.patch")
workDir=$name-$version

buildPhase()
{
    mkdir ../$name-build
    cd ../$name-build
    CFLAGS="-O2 -pipe" ../$name-$version/configure --prefix=/stage1 \
       --with-local-prefix=/stage1 --enable-languages=c \
       --disable-nls --enable-shared
    make BOOT_LDFLAGS="-static -s" BOOT_CFLAGS="-O2 -pipe" \
       STAGE1_CFLAGS="-O2 -pipe" bootstrap
}

installPhase()
{
    chown -R root:root *
    cd ../$name-build
    chown -R root:root *

    make install
    ln -s gcc /stage1/bin/cc
}
