#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/gettext

group=lfs-stage1

buildPhase()
{
    CFLAGS="$CFLAGS -pipe" ./configure --prefix=/stage1
    make
}

installPhase()
{
    make install
    rm -f /stage1/lib/gettext/gnu.gettext.*
}
