#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/gzip

patches=("g/gzip/$name-$version.patch.bz2")
group=lfs-stage1

buildPhase()
{
    ./configure --prefix=/stage1
    make
}

installPhase()
{
    make PREFIX=/stage1 install
}
