#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/ncurses

group=lfs-stage1

buildPhase()
{
    ./configure --prefix=/stage1 --with-shared \
       --without-debug
    make
}

installPhase()
{
    make install
}
