#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/sed

group=lfs-stage1

buildPhase()
{
    ./configure --prefix=/stage1 --bindir=/stage1/bin
    make
}

installPhase()
{
    make install
}
