#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/tar

patches=("t/tar/$name-$version.patch.bz2")
group=lfs-stage1

buildPhase()
{
    ./configure --prefix=/stage1 --disable-nls \
        --libexecdir=/stage1/bin --bindir=/stage1/bin
    make
}

installPhase()
{
    make install
}
