#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/textutils

group=lfs-stage1

buildPhase()
{
    ./configure --prefix=/stage1 --disable-nls
    make
}

installPhase()
{
    make install
}
