#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=freetype
version=1.3.1
group=Libraries/X
license=X11
description="Freetype"
src="f/freetype/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
FreeType is written in C. It is designed to be small, efficient, and highly
customizable while capable of producing high-quality output (glyph images) of
most vector and bitmap font formats for digital typography.

This is an old package required to build ttmkfdir.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install
}
