#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=freetype2
version=2.1.3
group=Libraries/X
license=X11
description="Freetype 2"
src="f/freetype2/freetype-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
FreeType is written in C. It is designed to be small, efficient, and highly
customizable while capable of producing high-quality output (glyph images) of
most vector and bitmap font formats for digital typography. FreeType is a freely
available and portable software library to render fonts.
EOF
}

buildPhase()
{
    # When this package used to be mainstream (2002), several techniques of the
    # bytecode interpreter were patented -- without a license, you were not
    # allowed to use them. As a result, it was disabled by default.
    #
    # However, it is now more than 20 years later. These patents have expired.
    # As a result, it is now allowed to use them
    #
    # These shell instructions enable the bytecode interpreter
    cp include/freetype/config/ftoption.h bak
    sed 's|/\* #define  TT_CONFIG_OPTION_BYTECODE_INTERPRETER \*/|#define  TT_CONFIG_OPTION_BYTECODE_INTERPRETER|' bak > include/freetype/config/ftoption.h

    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install
}
