#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=ttmkfdir
version=noversion
group=Libraries/X
license=X11
description="TTF make font dir"
src="t/ttmkfdir/$name.tar.gz"

showLongDescription()
{
    cat << "EOF"
Tool to create a True Type Font directory that can be used by XFree86.
EOF
}

preUnpack()
{
    mkdir ttmkfdir
    cd ttmkfdir
}

buildPhase()
{
    sed -e 's|FREETYPE_INCL=$(FREETYPE_BASE)/lib|FREETYPE_INCL=$(FREETYPE_BASE)/include/freetype|' \
      -e 's|FREETYPE_LIB=-L$(FREETYPE_BASE)/lib/.libs -lttf|FREETYPE_LIB=-L$(FREETYPE_BASE)/lib -lttf|' \
      Makefile > Makefile.new
    mv Makefile.new Makefile
    make FREETYPE_BASE=/usr
}

installPhase()
{
    install -m755 ttmkfdir /usr/bin
    mkdir -p /usr/X11R6/lib/X11/fonts/ttf
}
