#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=XFree86
version=4.2.1
shortVersion=420
group=Display
license=X11
description="XFree86"
srcs=("x/XFree86/X${shortVersion}src-1.tgz" "x/XFree86/X${shortVersion}src-2.tgz" "x/XFree86/X${shortVersion}src-3.tgz" "x/Xaw3d/Xaw3d-1.5.tar.gz")
patches=("x/XFree86/4.2.0-4.2.1.diff.gz" "x/XFree86/4.2.1-mit-shm-security.patch")
files=("x/Xaw3d/Xaw3d-1.3-glibc.patch.gz")

# Disable stripping. The driver modules will no longer work if you strip them
strip=no
stripSo=no

showLongDescription()
{
    cat << "EOF"
XFree86 is an implementation of the X Window System.
EOF
}

buildPhase()
{
    cp config/cf/site.def config.bak
    sed 's/BuildXKB              NO/BuildXKB              YES/' config.bak > config/cf/site.def
    
    echo $'\n#define HasZlib YES\n' >> config/cf/host.def
    echo $'\n#define HasNCurses YES\n' >> config/cf/host.def
    echo $'\n#define HasFreetype2 YES\n' >> config/cf/host.def
    echo $'\n#define BuildFreetype2Library NO\n' >> config/cf/host.def
    
    if [ "$CFLAGS" != "" ]
    then
        cat >> config/cf/host.def <<EOF

#define DefaultGcc2i386Opt  -O2 -march=i686

EOF
    fi
    
    make World

    # Build Xaw3d
    ln -s lib X11
    gzip -cd $sourcesDir/${files[0]} | patch -p2
    cd lib/Xaw3d

    ../../config/imake/imake -I../../config/cf -DTOPDIR=../.. -DCURRENTDIR=lib/Xaw3d
    make includes
    make depend
    make
}

installPhase()
{
    make install
    make install.man

    # Create some symlinks
    ln -sf X11R6 /usr/X11
    ln -sf /usr/X11R6/bin /usr/bin/X11
    ln -sf /usr/X11R6/lib/X11 /usr/lib/X11
    ln -sf /usr/X11R6/include/X11 /usr/include/X11

    # Install Xaw3d
    cd lib/Xaw3d
    make install

    # Add inclusion of the profile settings to the Xsession so that graphical
    # logins also spawn meaningful shell sessions
    cp /etc/X11/xdm/Xsession /etc/X11/xdm/Xsession.bak
    sed 's|#!/bin/sh|#!/bin/bash --login|' /etc/X11/xdm/Xsession.bak > /etc/X11/xdm/Xsession
    rm /etc/X11/xdm/Xsession.bak

    # Rename xinitrc and create symlink
    mv /etc/X11/xinit/xinitrc /etc/X11/xinit/xinitrc.twm
    ln -sfn xinitrc.twm /etc/X11/xinit/xinitrc

    # Add profile link
    install -m755 $cbtBaseDir/profile.d/10X11.sh /etc/profile.d
    if which csh
    then
        install -m755 $cbtBaseDir/profile.d/10X11.csh /etc/profile.d
    fi

    # Add window manager option
    mkdir -p /usr/share/ul/ul-xinit
    cat > /usr/share/ul/ul-xinit/twm << "EOF"
description="Tab Window Manager"
EOF

    mkdir -p /usr/share/ul/ul-xsession/sessions
    install -m755 $cbtBaseDir/plugins/ul-xsession/sessions/{xsession,failsafe} /usr/share/ul/ul-xsession/sessions
}

postConfigurePhase()
{
    echo "/usr/X11R6/lib" >> /etc/ld.so.conf
    ldconfig
}
