#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=renderproto
version=0.9.3
group=Display/X11/proto
license=MIT
description="renderproto"
src="x/xorg/proto/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
X.org generated proto package: renderproto
EOF
}

buildPhase()
{
    ./configure $XORG_CONFIG --with-xorg-module-dir=/usr/X11R7.3/lib/X11/modules
    make
}

installPhase()
{
    make install
}
