#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=DirectFB
version=1.4.3
group=Display
license=LGPLv2.1
description="Direct Framebuffer library"
src="d/DirectFB/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
DirectFB is a thin library that provides hardware graphics acceleration, input
device handling and abstraction, integrated windowing system with support for
translucent windows and multiple display layers, not only on top of the Linux
Framebuffer Device. It is a complete hardware abstraction layer with software
fallbacks for every graphics operation that is not supported by the underlying
hardware. DirectFB adds graphical power to embedded systems and sets a new
standard for graphics under Linux.
EOF
}

buildPhase()
{
    LIBS="-L/usr/X11R$xorgVersion/lib" \
        ./configure --prefix=/usr --sysconfdir=/etc
    make $globalBuildOptions
}

installPhase()
{
    make install
}
