#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=qt
version=2.3.1
group=Libraries/kde
license=GPLv2/QPL
description="Trolltech Qt library"
src="q/qt/$name-x11-$version.tar.gz"
buildAsRoot=true

showLongDescription()
{
    cat << "EOF"
qt is a cross-platform application development framework for creating graphical
user interfaces as well as cross-platform applications that run on various
software and hardware platforms with little or no change in the underlying
codebase while still being a native application with native capabilities and
speed.
EOF
}

buildPhase()
{
    true
}

installPhase()
{
    export QTDIR=/opt/$name-$version
    cd ..
    mv $name-$version /opt
    chown -R root:root "$QTDIR"
    cd "$QTDIR"
    yes yes | ./configure -shared -sm -thread -gif -system-libpng -system-libmng -system-zlib -system-jpeg -xft
    make

    ln -sfn /opt/$name-$version /opt/$name
    install -m755 $cbtBaseDir/profile.d/21qt.sh /etc/profile.d
    if which csh
    then
        install -m755 $cbtBaseDir/profile.d/21qt.csh /etc/profile.d
    fi
}
