#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libmng
version=1.0.4
group=Libraries/Image
license=zlib
description="MNG library"
src="l/libmng/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
The libmng libraries are used by programs wanting to read and write
Multiple-image Network Graphics (MNG) files which are the animation equivalents
to PNG files.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --with-zlib --with-jpeg --with-lcms
    make
}

installPhase()
{
    make install
}
