#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=tiff
version=3.5.7
group=Libraries/Image
license=MIT
description="TIFF library"
src="t/tiff/$name-v$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
The libtiff package contains the TIFF libraries and associated utilities. The
libraries are used by many programs for reading and writing TIFF files and the
utilities are used for general work with TIFF files.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr -noninteractive
    chmod 644 Makefile
    cp Makefile Makefile.old
    sed 's/-${MAKEFLAGS}/${MAKEFLAGS}/' Makefile.old > Makefile
    make COPTS="" OPTIMIZER="$CFLAGS"
}

installPhase()
{
    make install
}
