#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/slackware-8.0

name=checkinstall
version=1.5.3
group=Tools/Additional
license=GPLv2
description="Checkinstall"
src="c/checkinstall/$name-$version.tgz"
noCheckInstall=true # We must disable this so that we can bootstrap checkinstall

showLongDescription()
{
    cat << "EOF"
checkinstall keeps track of all the files created or modified by your
installation script, builds a standard binary package (.deb, .rpm, .tgz) and
installs it in your system giving you the ability to uninstall it with your
distribution's standard package management utilities.
EOF
}

# '

buildPhase()
{
    make
}

installPhase()
{
    make install
    # Force re-running make install with checkinstall with the right parameters
    installCommand="make install"
    installPackageWithCheckInstall 
}
