#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/slackware-8.0

name=dos2unix
version=3.1
group=Tools/Additional
license=BSD-2
description="dos2unix"
src="d/dos2unix/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
dos2unix is program that converts plain text files in DOS/MAC format to UNIX
format.
EOF
}

buildPhase()
{
    make clean
    make
}

installPhase()
{
    make install
}
