#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=glew
version=1.5.7
group=Libraries/Multimedia
license=MIT
description="OpenGL Extension Wrangler Library"
src="g/glew/$name-$version.tgz"

showLongDescription()
{
    cat << "EOF"
The OpenGL Extension Wrangler Library is a simple tool that helps C/C++
developers initialize extensions and write portable applications. GLEW currently
supports a variety of operating systems, including Windows, Linux, Darwin, Irix,
and Solaris.
EOF
}

buildPhase()
{
    make
}

installPhase()
{
    make install
}
