#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=exiv2
version=0.21.1
group=Libraries/FileFormats
license=GPLv2
description="Exif, IPTC, XMP parser library"
src="e/exiv2/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Exiv2 is a C++ library and a command line utility to read and write Exif, IPTC
and XMP image metadata.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
