#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=wv
version=1.2.4
group=Libraries/FileFormats
license=GPLv2
description="Word conversion library"
src="w/wv/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
wv converts Word 2,6,7,8,9 files to html and latex. The Word 2 conversion is
still incomplete (no formatting), but it will do a passable job extracting the
text, which is what you probably want anyway.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
