#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=proftpd
version=1.2.1
group=Network/Servers
license=GPLv2
description="ProFTP daemon"
src="p/proftpd/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
ProFTPD is an FTP server. ProFTPD's primary design goal is to be a highly
feature rich FTP server, exposing a large amount of configuration options to the
user.
EOF
}

# '

preConfigurePhase()
{
    groupadd -g 46 proftpd
    useradd -u 46 -c proftpd -d /home/ftp -g proftpd -s /bin/false proftpd
}

buildPhase()
{
    install_user=proftpd install_group=proftpd \
      ./configure --prefix=/usr --sysconfdir=/etc \
      --localstatedir=/var
    make
}

installPhase()
{
    make install

    cat > /etc/proftpd.conf << "EOF"
# This is a basic ProFTPD configuration file
# It establishes a single server and a single anonymous login.

ServerName			"ProFTPD Default Installation"
ServerType			standalone
DefaultServer			on

# Port 21 is the standard FTP port.
Port				21
# Umask 022 is a good standard umask to prevent new dirs and files
# from being group and world writable.
Umask				022

# To prevent DoS attacks, set the maximum number of child processes
# to 30.  If you need to allow more than 30 concurrent connections
# at once, simply increase this value.  Note that this ONLY works
# in standalone mode, in inetd mode you should use an inetd server
# that allows you to limit maximum number of processes per service
# (such as xinetd)
MaxInstances			30

# Set the user and group that the server normally runs at.
User				proftpd
Group				proftpd

# Normally, we want files to be overwritable.
<Directory /*>
  AllowOverwrite		on
</Directory>

# A basic anonymous configuration, no upload directories.
<Anonymous ~proftpd>
  User				proftpd
  Group				proftpd
  # We want clients to be able to login with "anonymous" as well as "proftpd"
  UserAlias			anonymous proftpd

  # Limit the maximum number of anonymous logins
  MaxClients			10

  # We want 'welcome.msg' displayed at login, and '.message' displayed
  # in each newly chdired directory.
  DisplayLogin			welcome.msg
  DisplayFirstChdir		.message

  # Limit WRITE everywhere in the anonymous chroot
  <Limit WRITE>
    DenyAll
  </Limit>
</Anonymous>
EOF

    install -m754 $cbtBaseDir/init.d/proftpd /etc/rc.d/init.d
    install -d -m755 /usr/share/ul/ul-init
    install -m644 $cbtBaseDir/plugins/ul-init/proftpd /usr/share/ul/ul-init
}
