#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xinetd
version=2.3.9
group=Network/Servers
license=xinetd
description="Extensible Internet Daemon"
src="x/xinetd/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
xinetd (Extended Internet Service Daemon) is an open-source super-server daemon
which runs on many Unix-like systems, and manages Internet-based connectivity.

It offers a more secure alternative to the older inetd ("the Internet daemon"),
which most modern Linux distributions have deprecated.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install

    cat > /etc/xinetd.conf << "EOF"
# Begin /etc/xinetd

defaults
{
    instances      = 60
    log_type       = SYSLOG daemon
    log_on_success = HOST PID USERID
    log_on_failure = HOST USERID
    cps            = 25 30
}

# All service files are stored in the /etc/xinetd.d directory
includedir /etc/xinetd.d

# End /etc/xinetd
EOF

    install -m754 $cbtBaseDir/init.d/xinetd /etc/rc.d/init.d
    install -d -m755 /usr/share/ul/ul-init
    install -m644 $cbtBaseDir/plugins/ul-init/xinetd /usr/share/ul/ul-init
}
