#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=docbook-xml
version=4.2
group=Libraries/Docbook
license=MIT
description="Docbook XML DTD"
src="d/docbook-xml/$name-$version.zip"
workDir=docbook-xml

showLongDescription()
{
    cat << "EOF"
This package contains document type definitions for verification of XML data
files against the DocBook rule set. These are useful for structuring books and
software documentation to a standard allowing you to utilize transformations
already written for that standard.
EOF
}

unpackPhase()
{
    mkdir -p docbook-xml
    cd docbook-xml
    unzip "$sourcesDir/$src"
}

buildPhase()
{
    echo
}

installPhase()
{
    chown -R root:root *
    install -d /usr/share/xml/docbook/xml-dtd-$version &&
    cp -af docbook.cat *.dtd ent/ *.mod /usr/share/xml/docbook/xml-dtd-$version
}

postConfigurePhase()
{
    if [ ! -e /etc/xml/catalog ]
    then
        mkdir -p /etc/xml; xmlcatalog --noout --create /etc/xml/catalog
    fi

    if [ ! -e /etc/xml/docbook ]
    then
        xmlcatalog --noout --create /etc/xml/docbook
    fi

    xmlcatalog --noout --add "public" \
    "-//OASIS//ELEMENTS DocBook XML Information Pool V4.2//EN" \
    "file:///usr/share/xml/docbook/xml-dtd-4.2/dbpoolx.mod" \
    /etc/xml/docbook

    xmlcatalog --noout --add "public" \
    "-//OASIS//DTD DocBook XML V4.2//EN" \
    "http://oasis-open.org/docbook/xml/4.2/docbookx.dtd" \
    /etc/xml/docbook

    xmlcatalog --noout --add "public" \
    "-//OASIS//ENTITIES DocBook XML Character Entities V4.2//EN" \
    "file:///usr/share/xml/docbook/xml-dtd-4.2/dbcentx.mod" \
    /etc/xml/docbook

    xmlcatalog --noout --add "public" \
    "-//OASIS//ENTITIES DocBook XML Notations V4.2//EN" \
    "file:///usr/share/xml/docbook/xml-dtd-4.2/dbnotnx.mod" \
    /etc/xml/docbook

    xmlcatalog --noout --add "public" \
    "-//OASIS//ENTITIES DocBook XML Additional General Entities V4.2//EN" \
    "file:///usr/share/xml/docbook/xml-dtd-4.2/dbgenent.mod" \
    /etc/xml/docbook

    xmlcatalog --noout --add "public" \
    "-//OASIS//ELEMENTS DocBook XML Document Hierarchy V4.2//EN" \
    "file:///usr/share/xml/docbook/xml-dtd-4.2/dbhierx.mod" \
    /etc/xml/docbook

    xmlcatalog --noout --add "public" \
    "-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
    "file:///usr/share/xml/docbook/xml-dtd-4.2/soextblx.dtd" \
    /etc/xml/docbook

    xmlcatalog --noout --add "public" \
    "-//OASIS//DTD DocBook XML CALS Table Model V4.2//EN" \
    "file:///usr/share/xml/docbook/xml-dtd-4.2/calstblx.dtd" \
    /etc/xml/docbook

    xmlcatalog --noout --add "rewriteSystem" \
    "http://www.oasis-open.org/docbook/xml/4.2" \
    "file:///usr/share/xml/docbook/xml-dtd-4.2" \
    /etc/xml/docbook

    xmlcatalog --noout --add "rewriteURI" \
    "http://www.oasis-open.org/docbook/xml/4.2" \
    "file:///usr/share/xml/docbook/xml-dtd-4.2" \
    /etc/xml/docbook

    xmlcatalog --noout --add "delegatePublic" \
    "-//OASIS//ENTITIES DocBook XML" \
    "file:///etc/xml/docbook" /etc/xml/catalog

    xmlcatalog --noout --add "delegatePublic" \
    "-//OASIS//DTD DocBook XML" \
    "file:///etc/xml/docbook" /etc/xml/catalog

    xmlcatalog --noout --add "delegateSystem" \
    "http://www.oasis-open.org/docbook/" \
    "file:///etc/xml/docbook" /etc/xml/catalog

    xmlcatalog --noout --add "delegateURI" \
    "http://www.oasis-open.org/docbook/" \
    "file:///etc/xml/docbook" /etc/xml/catalog
}
