#!/bin/sh
# Begin $rc_base/init.d/apache

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy: bdubbs $
#$Date: 2005-08-01 13:29:19 -0600 (Mon, 01 Aug 2005) $

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		echo "Starting Apache daemon..."
		apachectl start
		evaluate_retval
		;;

	stop)
		echo "Stopping Apache daemon..."
		apachectl stop
		evaluate_retval
		;;

	restart)
		echo "Restarting Apache daemon..."
		apachectl restart
		evaluate_retval
		;;

	status)
		statusproc httpd
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/apache
