#!/bin/sh
# Begin $rc_base/init.d/fcron

source /etc/sysconfig/rc
source $rc_functions

case "$1" in
	start)
		echo "Starting fcron..."
		loadproc fcron
		;;

	stop)
		echo "Stopping fcron..."
		killproc fcron
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc fcron
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/fcron
