#!/bin/sh
# Begin $rc_base/init.d/nfsclient

source /etc/sysconfig/rc
source $rc_functions

case "$1" in
	start)
		echo -n "Starting statd for NFS" 
		loadproc /usr/sbin/rpc.statd
		;;

	stop)
		;;

	restart)
		$0 stop
		/usr/bin/sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

# End $rc_base/init.d/nfsclient
