#!/bin/sh
# Begin $rc_base/init.d/openldap

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy: bdubbs $
#$Date: 2005-08-01 13:29:19 -0600 (Mon, 01 Aug 2005) $

source /etc/sysconfig/rc
source $rc_functions

case "$1" in
	start)
		echo "Starting LDAP slapd Server..."
		loadproc /usr/sbin/slapd

		echo "Starting LDAP slurpd Server..."
		loadproc /usr/sbin/slurpd
		;;

	stop)
		echo "Stopping LDAP slapd Server..."
		# slapd needs SIGINT
		killproc /usr/sbin/slapd INT

		echo "Stopping LDAP slurpd Server..."
		killproc /usr/sbin/slurpd
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/sbin/slapd
		statusproc /usr/sbin/slurpd
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/openldap
