#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=ConsoleKit
version=0.4.3
group=Libraries/Desktop
license=GPLv2
description="Console Kit"
src="c/ConsoleKit/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
ConsoleKit is a framework for defining and tracking users, login
sessions, and seats.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --enable-pam-module \
        --libexecdir=/usr/lib/ConsoleKit
    make $globalBuildOptions
}

installPhase()
{
    make install

    cat >> /etc/pam.d/system-session << "EOF"
# Begin ConsoleKit addition

session   optional    pam_loginuid.so
session   optional    pam_ck_connector.so nox11

# End ConsoleKit addition
EOF

    cat > /usr/lib/ConsoleKit/run-session.d/pam-foreground-compat.ck << "EOF"
#!/bin/sh
TAGDIR=/var/run/console

[ -n "$CK_SESSION_USER_UID" ] || exit 1
[ "$CK_SESSION_IS_LOCAL" = "true" ] || exit 0

TAGFILE="$TAGDIR/`getent passwd $CK_SESSION_USER_UID | cut -f 1 -d:`"

if [ "$1" = "session_added" ]; then
    mkdir -p "$TAGDIR"
    echo "$CK_SESSION_ID" >> "$TAGFILE"
fi

if [ "$1" = "session_removed" ] && [ -e "$TAGFILE" ]; then
    sed -i "\%^$CK_SESSION_ID\$%d" "$TAGFILE"
    [ -s "$TAGFILE" ] || rm -f "$TAGFILE"
fi
EOF
    chmod -v 755 /usr/lib/ConsoleKit/run-session.d/pam-foreground-compat.ck
}
