#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=desktop-file-utils
version=0.15
group=Libraries/Desktop
license=GPLv2
description="Desktop file utilities"
src="d/desktop-file-utils/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Utilities for manipulating desktop files.

desktop-file-validate: validates a desktop file and prints warnings/errors
about desktop entry specification violations.

desktop-file-install: installs a desktop file to the applications directory,
optionally munging it a bit in transit.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    # To shut up warnings
    export XDG_DATA_DIRS=/usr/local/share:/usr/share
    export XDG_CONFIG_DIRS=/etc/xdg
    
    make install

    install -m755 $cbtBaseDir/profile.d/24desktop.sh /etc/profile.d
    if which csh
    then
        install -m755 $cbtBaseDir/profile.d/24desktop.csh /etc/profile.d
    fi

}
