#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=icon-naming-utils
version=0.8.90
group=Libraries/Desktop
license=GPLv2
description="Icon naming utils"
src="i/icon-naming-utils/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Utilities for manipulating desktop files.

desktop-file-validate: validates a desktop file and prints warnings/errors
                       about desktop entry specification violations.

desktop-file-install: installs a desktop file to the applications directory,
                      optionally munging it a bit in transit.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr \
        --libexecdir=/usr/lib/icon-naming-utils
    make $globalBuildOptions
}

installPhase()
{
    make install
}
