#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libspectre
version=0.2.2
group=Libraries/Desktop
license=GPLv2
description="PostScript rendering library"
src="l/libspectre/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
libspectre is a small library for rendering Postscript documents. It
provides a convenient easy to use API for handling and rendering
Postscript documents.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
