#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=pyxdg
version=0.19
group=Libraries/Desktop
license=LGPLv2
description="Python implementation of various XDG specs"
src="p/pyxdg/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
The XDG Package contains:

- Implementation of the XDG-Base-Directory Standard
      http://standards.freedesktop.org/basedir-spec/

- Implementation of the XDG-Desktop Standard
      http://standards.freedesktop.org/basedir-spec/

- Implementation of the XDG-Menu Standard
      http://standards.freedesktop.org/basedir-spec/

- Implementation of the XDG-Icon-Theme Standard
      http://standards.freedesktop.org/basedir-spec/

- Implementation of the XDG-Shared MIME-info Database
      http://standards.freedesktop.org/basedir-spec/

- Implementation of the XDG-Recent File Storage Specification
    http://standards.freedesktop.org/basedir-spec/
EOF
}

buildPhase()
{
    echo
}

installPhase()
{
    python setup.py install
}
