#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=shared-mime-info
version=0.23
group=Libraries/Desktop
license=GPLv2
description="Shared MIME information"
src="s/shared-mime-info/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
This package contains:

- The freedesktop.org shared MIME database spec.
- The merged GNOME and KDE databases, in the new format.
- The update-mime-database command, used to install new MIME data.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
