#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=startup-notification
version=0.9
group=Libraries/Desktop
license=LGPLv2
description="Startup notification library"
src="s/startup-notification/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
startup-notification contains a reference implementation of the startup
notification protocol.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
    install -v -m644 -D doc/startup-notification.txt /usr/share/doc/$name-$version/startup-notification.txt
}
