#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=telepathy-logger
version=0.1.7
group=Libraries/Desktop
license=GPLv2.1
description="Telepathy headless observer client"
src="t/telepathy-logger/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
tp-logger is a headless Observer client that logs information received by the
Telepathy framework. It features pluggable backends to log different sorts of
messages, in different formats.

tp-logger features a Telepathy-style D-Bus API to expose logs and interesting
information related to logging (most frequent contacts, etc.). It also provides
a GLib-compatible client API for making bulk log requests (e.g. for display
logs in applications without having to provide lots of information over D-Bus).
EOF
}

buildPhase()
{
    ./configure --prefix=/usr \
        --libexecdir=/usr/lib/telepathy-logger
    make $globalBuildOptions
}

installPhase()
{
    make install
}
