#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=unrar
version=4.0.3
group=Tools/Packers
license=unrar
description="UnRAR"
src="u/unrar/unrarsrc-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
The unrar package contains a RAR extraction utility used for extracting files
from RAR archives. RAR archives are usually created with WinRAR, primarily in a
Windows environment.
EOF
}

buildPhase()
{
    make -f makefile.unix
}

installPhase()
{
    make -f makefile.unix DESTDIR=/usr install
}
