#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=autogen
version=5.11.5
group=Tools/Development
license=GPLv3
description="Hex editor"
src="a/autogen/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
This is AutoGen, an automated text file generator. It was inspired out of
frustration and hassle with maintaining syncronization between option flag
lists, global variables and usage information. The desire for more than
#define macros came about when it became apparent that macros alone were
insufficient for reducing the maintenance into a single option list. The
impetus to actually start something finally came when I had to maintain a
large callout procedure table and associated lookup tables.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
