#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=inkscape
version=0.48.5
group=Applications
description="Vector graphics editor"
license=GPLv2
src="i/inkscape/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Inkscape is an open source drawing tool with capabilities similar to
Illustrator, Freehand, and CorelDraw that uses the W3C standard scalable
vector graphics  format (SVG). Some supported SVG features include
basic shapes, paths, text, markers, clones, alpha blending, transforms,
gradients, and grouping. In addition, Inkscape supports Creative Commons
meta-data, node-editing, layers, complex path operations, text-on-path,
and SVG XML editing. It also imports several formats like EPS, Postscript,
JPEG, PNG, BMP, and TIFF and exports PNG as well as multiple vector-based
formats.

Inkscape's main motivation is to provide the Open Source community
with a fully W3C compliant XML, SVG, and CSS2 drawing tool. Additional
planned work includes conversion of the codebase from C/Gtk to C++/Gtkmm,
emphasizing a lightweight core with powerful features added through
an extension mechanism, and the establishment of a friendly, open,
community-oriented development processes.
EOF
}

# '

buildPhase()
{
    LIBS="-L/usr/X11R$xorgVersion/lib" \
        ./configure --prefix=/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
