#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=esound
version=0.2.29
group=Libraries/Multimedia
license=LGPLv2.1
description="Enlightened Sound Daemon"
src="e/esound/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The EsounD package contains the Enlightened Sound Daemon. This is useful for
mixing together several digitized audio streams for playback by a single device.
EOF
}

buildPhase()
{
    if [ -f /usr/lib/libwrap.a ]
    then
        local extraArgs="--with-libwrap"
    fi

    ./configure --prefix=/usr --sysconfdir=/etc $extraArgs
    make
}

installPhase()
{
    make install
}
