#!/bin/bash -e

source $cbtFunctionsDir/deployTrivialPackage
source $cbtBaseDir/settings/ul-packages-settings

name=binfmt_misc
group=Services
description="binfmt_misc configuration script"

showLongDescription()
{
    cat << "EOF"
A script making it possible to load miscellaneous binary executable formats
using the Linux kernel's binfmt_misc loader.
EOF
}

# '

installPhase()
{
    install -m754 $cbtBaseDir/init.d/binfmt_misc /etc/rc.d/init.d
    install -d -m755 /usr/share/ul/ul-init
    install -m644 $cbtBaseDir/plugins/ul-init/binfmt_misc /usr/share/ul/ul-init
}
