#!/bin/bash -e

source $cbtFunctionsDir/deployTrivialPackage
source $cbtBaseDir/settings/ul-packages-settings

name=Xsession
group=Services
description="Xsession script"

showLongDescription()
{
    cat << "EOF"
A session script making it possible to select any supported window manager.
EOF
}

installPhase()
{
    mkdir -p /usr/share/ul/ul-xsession
    cp $cbtBaseDir/plugins/ul-xsession/{Xsession,common} /usr/share/ul/ul-xsession
    chmod 755 /usr/share/ul/ul-xsession/Xsession
}
