#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=iptables
version=1.2.7a
group=Network/Tools
license=GPLv2
description="iptables configuration utility"
src="i/iptables/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
iptables is a user-space utility program that allows a system administrator to
configure the IP packet filter rules of the Linux kernel firewall, implemented
as different Netfilter modules.
EOF
}

buildPhase()
{
    make PREFIX=/usr
}

installPhase()
{
    make PREFIX=/usr install
}
