#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=tcpdump
version=3.7.2
group=Network/Tools
license=BSD
description="Packet inspection utility"
src="t/tcpdump/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
tcpdump is a data-network packet analyzer computer program that runs under a
command line interface. It allows the user to display TCP/IP and other packets
being transmitted or received over a network to which the computer is attached.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install
}
