#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=wget
version=1.8.2
group=Network/Tools
license=GPLv2
description="Download utility"
src="w/wget/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
GNU Wget is a free software package for retrieving files using HTTP, HTTPS, FTP
and FTPS, the most widely used Internet protocols. It is a non-interactive
commandline tool, so it may easily be called from scripts, cron jobs, terminals
without X-Windows support, etc.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --sysconfdir=/etc
    make
}

installPhase()
{
    make install
}
