#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=fvwm95
version=2.0.43f
group=Desktops/X11
license=GPLv2
description="fvwm95 window manager"
src="f/fvwm95/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
fvwm95 is a hack based on fvwm2. It tries to emulate the good features of a
well known product without bloating the regular fvwm code. fvwm95 is based on
fvwm, which, in turn, is based on twm.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr/X11R6
    make
}

installPhase()
{
    make install
    cat > /etc/X11/xinit/xinitrc.fvwm95 << "EOF"
#!/bin/sh

exec fvwm95
EOF

    mkdir -p /usr/share/ul/ul-xinit
    cat > /usr/share/ul/ul-xinit/fvwm95 << "EOF"
description="FVWM95 window manager"
EOF

    mkdir -p /usr/share/ul/ul-xsession/sessions
    install -m755 $cbtBaseDir/plugins/ul-xsession/sessions/fvwm95 /usr/share/ul/ul-xsession/sessions
}
