#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xpaint
version=2.6.9
group=Desktops/X11
license=MIT
description="X Paint"
src="x/xpaint/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
XPaint is a free and open-source raster graphics editor for Unix-like
operating systems. Its main purpose is to be a lightweight and easy-to-use
raster editor. It supports various image file formats, including GIF, PNG, JPEG,
TIFF, PPM, XBM and XPM.
EOF
}

buildPhase()
{
    xmkmf -a
    make xaw
}

installPhase()
{
    make install
    make install.man
}
