#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libXdmcp
version=1.0.2
group=Display/X11/lib2
license=MIT
description="libXdmcp"
src="x/xorg/lib2/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
A library implementing the X Display Manager Control Protocol.
EOF
}

buildPhase()
{
    ./configure $XORG_CONFIG
    make $globalBuildOptions
}

installPhase()
{
    make install
}
