#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=asciidoc
version=8.6.3
group=Tools/Development
license=GPLv2
description="Plain text markup language"
src="a/asciidoc/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
AsciiDoc is a plain text markup language for writing technical content. It's
packed with semantic elements and equipped with features to modularize and reuse
content. AsciiDoc content can be composed using a text editor, managed in a
version control system, and published to multiple output formats.
EOF
}

# '

buildPhase()
{
    ./configure --prefix=/usr \
        --sysconfdir=/etc
    make $globalBuildOptions
}

installPhase()
{
    make install
}
