#!/bin/bash -e

source $cbtFunctionsDir/deployXDGDesktopSourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=ddd
version=3.3.11
group=Tools/Development
license=GPLv2
description="Data Display Debugger"
src="d/ddd/$name-$version.tar.gz"

desktopTargetDir="/usr/share/applications"
desktopName="DDD"
genericName="Debugger"
exec=ddd
comment="Data Display Debugger"
categories="Development;"

showLongDescription()
{
    cat << "EOF"
GNU DDD is a graphical front end for the command-line debugger GDB. Besides
"usual" frontend features such as viewing source texts, DDD has become famous
through its interactive graphical data display, where data structures are
displayed as graphs.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
