#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=git
version=1.7.3.4
group=Tools/Development
license=GPLv2
description="Git source code management system"
src="g/git/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
"git" can mean anything, depending on your mood.

 - random three-letter combination that is pronounceable, and not
   actually used by any common UNIX command.  The fact that it is a
   mispronunciation of "get" may or may not be relevant.
 - stupid. contemptible and despicable. simple. Take your pick from the
   dictionary of slang.
 - "global information tracker": you're in a good mood, and it actually
   works for you. Angels sing, and a light suddenly fills the room.
 - "goddamn idiotic truckload of sh*t": when it breaks

Git is a fast, scalable, distributed revision control system with an
unusually rich command set that provides both high-level operations
and full access to internals.
EOF
}

# '

buildPhase()
{
    ./configure --prefix=/usr \
        --libexecdir=/usr/lib
    make $globalBuildOptions
    make man
}

installPhase()
{
    make install
    make install-man
}
