#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xmlto
version=0.0.21
group=Tools/Development
license=GPLv2
description="Converts XML to various formats"
src="x/xmlto/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Utility xmlto is a simple shell script for converting XML files to various
formats. It serves as an easy-to-use command-line frontend to make fine output
without remembering many long options and searching for the syntax of the
backends.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
