#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=x11perf
version=1.4.1
group=Display/X11/app
license=MIT
description="x11perf"
src="x/xorg/app/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
X.org generated app package: x11perf
EOF
}

buildPhase()
{
    ./configure $XORG_CONFIG --with-xorg-module-dir=/usr/X11R7.3/lib/X11/modules
    make
}

installPhase()
{
    make install
}
