#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xdriinfo
version=1.0.2
group=Display/X11/app
license=MIT
description="xdriinfo"
src="x/xorg/app/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
X.org generated app package: xdriinfo
EOF
}

buildPhase()
{
    ./configure $XORG_CONFIG --with-xorg-module-dir=/usr/X11R7.3/lib/X11/modules
    make
}

installPhase()
{
    make install
}
