#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xman
version=1.0.3
group=Display/X11/app
license=MIT
description="xman"
src="x/xorg/app/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
X.org generated app package: xman
EOF
}

buildPhase()
{
    ./configure $XORG_CONFIG --with-xorg-module-dir=/usr/X11R7.3/lib/X11/modules
    make
}

installPhase()
{
    make install

    # Install desktop item
    mkdir -p /usr/share/applications
    install -m644 $cbtBaseDir/xdg/applications/$name.desktop /usr/share/applications
}
