#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=expat
version=2.0.1
group=Libraries/XML
license=MIT
description="Stream oriented XML parser"
src="e/expat/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Expat is a stream-oriented XML parser library written in C.
Expat excels with files too large to fit RAM, and where performance and
flexibility are crucial.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
    install -v -m755 -d /usr/share/doc/$name-$version
    install -v -m644 doc/*.{html,png,css} /usr/share/doc/$name-$version
}
