#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libxml2
version=2.7.3
group=Libraries/XML
license=MIT
description="XML parser library"
src="l/libxml2/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
libxml2 is an XML toolkit implemented in C, originally developed for the GNOME
Project.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --with-history
    make $globalBuildOptions
}

installPhase()
{
    make install
}
