#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=arj
version=3.10.18
group=Tools/Packers
license=GPLv2
description="ARJ archiver"
src="a/arj/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
An open-source implementation of the world-famous ARJ archiver. This version
has been created with an intent to preserve maximum compatibility and retain
the feature set of the original ARJ archiver as provided by ARJ Software.
EOF
}

buildPhase()
{
    cd gnu
    autoconf
    ./configure --prefix=/usr
    cd ..
    make
}

installPhase()
{
    make install
    # Create symlink to preserve compatibility with unarj
    ln -s arj /usr/bin/unarj
}
