#!/bin/bash -e

source $cbtFunctionsDir/deployXDGDesktopSourcePackage
source $cbtBaseDir/settings/extra-settings

name=pingus
version=0.7.3
group=Games
license=GPLv2
description="Pingus"
src="p/pingus/$name-$version.tar.bz2"

desktopTargetDir="/usr/local/share/applications"
desktopName="Pingus"
genericName="Platform game"
exec=/usr/local/games/pingus/bin/pingus
comment="Pingus"
categories="Game;"

showLongDescription()
{
    cat << "EOF"
Pingus is a free Lemmings-like puzzle game covered under the GNU GPL. It
features currently 77 playable levels and runs under a wide variety of operating
systems.
EOF
}

buildPhase()
{
    scons LIBPATH="/usr/X11R$xorgVersion/lib"
}

installPhase()
{
    ./install.sh /usr/local/games/pingus
}
