#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=prboom
version=2.5.0
group=Games
license=GPLv2
description="DOOM port"
src="p/prboom/$name-$version.tar.gz"
wadBaseDir="/usr/local/share/doom"

showLongDescription()
{
    cat << "EOF"
PrBoom, originally short for "Proff Boom", is a source port of Doom for Windows,
Linux/POSIX, AmigaOS 4, OpenVMS and Mac OS X based initially on Boom.
EOF
}

buildPhase()
{
    LIBS="-L/usr/X11R$xorgVersion/lib" \
        ./configure
    make $globalBuildOptions
}

installPhase()
{
    make install

    # Create desktop links

    mkdir -p /usr/local/share/applications

    cat > /usr/local/share/applications/doom.desktop <<EOF
[Desktop Entry]
Type=Application
Name=prboom (Doom)
GenericName=Shoot em up game
Comment=Doom on prboom
Categories=Game;Shooter;
Exec=/usr/local/games/prboom -iwad $wadBaseDir/doom.wad
EOF

    cat > /usr/local/share/applications/doom2.desktop <<EOF
[Desktop Entry]
Type=Application
Name=prboom (Doom 2)
GenericName=Shoot em up game
Comment=Doom 2 on prboom
Categories=Game;Shooter;
Exec=/usr/local/games/prboom -iwad $wadBaseDir/doom2.wad
EOF

    cat > /usr/local/share/applications/plutonia.desktop <<EOF
[Desktop Entry]
Type=Application
Name=prboom (Plutonia)
GenericName=Shoot em up game
Comment=Plutonia on prboom
Categories=Game;Shooter;
Exec=/usr/local/games/prboom -iwad $wadBaseDir/plutonia.wad
EOF

    cat > /usr/local/share/applications/tnt.desktop <<EOF
[Desktop Entry]
Type=Application
Name=prboom (TNT)
GenericName=Shoot em up game
Comment=TNT on prboom
Categories=Game;Shooter;
Exec=/usr/local/games/prboom -iwad $wadBaseDir/tnt.wad
EOF
}
