#!/bin/bash -e

source $cbtFunctionsDir/deployXDGDesktopSourcePackage
source $cbtBaseDir/settings/extra-settings

name=quake2
version=r0.16.1
group=Games
license=GPLv2
description="icculus.org Quake 2 port"
src="q/quake2/$name-$version.tar.gz"

desktopTargetDir="/usr/local/share/applications"
desktopName="Quake 2"
genericName="Shoot em up game"
exec=/usr/local/bin/run-quake2
comment="icculus.org Quake 2 port"
categories="Game;Shooter;"

showLongDescription()
{
    cat << "EOF"
A port of Quake 2 provided by icculus.org
EOF
}

buildPhase()
{
    make
}

installPhase()
{
    chown -R root:root releasei386
    mv releasei386 /usr/local/share/quake2
    cat > /usr/local/bin/run-quake2 << "EOF"
#!/bin/bash -e
cd /usr/local/share/quake2
exec /usr/local/share/quake2/sdlquake2 "$@"
EOF
    chmod 755 /usr/local/bin/run-quake2
}
