#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=supertux
version=0.1.3
group=Games
license=GPLv2
description="Supertux"
src="s/supertux/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
SuperTux is an open-source classic 2D jump'n run sidescroller game in a style
similar to the original Super Mario games.
EOF
}

# '

buildPhase()
{
    ./configure
    sed -i 's/Menu:://' src/menu.h
    make $globalBuildOptions
}

installPhase()
{
    make install
}
