#!/bin/bash -e

source $cbtFunctionsDir/deployXDGDesktopSourcePackage
source $cbtBaseDir/settings/extra-settings

name=umodpack
version=0.5b16_allinone
pkgVersion=0.5b16-allinone
license=GPLv2
group=Games
description="UT Mod administration tool"
srcs=("t/tk/Tk-804.028.tar.gz" "u/umodpack/$name-$pkgVersion.tar.gz")
workDir=$name-0.5b16

desktopTargetDir="/usr/share/applications"
desktopName="utmodpack"
genericName="Mod administration tool"
exec=/usr/bin/xumod
comment="UT mod administration tool"
categories="Game;Shooter;"

showLongDescription()
{
    cat << "EOF"
Umodpack is crossplatform tool for managing umod packages for Unreal games.
It can install, deinstall and extract files from umod file. Umodpack includes
command line tool and GUI.
EOF
}

buildPhase()
{
    # This package bundles old version of Tk and Archive-Zip
    # If we install them they conflict with newer versions that have already
    # been installed. We disable them
    sed -i -e "/'Tk'/d" \
        -e "/'Archive::Zip/d" \
        Makefile.PL
    rm -r Tk*
    rm -r Archive-Zip-*

    perl Makefile.PL
    make
}

installPhase()
{
    make install
}
