#!/bin/bash -e

source $cbtFunctionsDir/deployXDGDesktopSourcePackage
source $cbtBaseDir/settings/extra-settings

name=xbill
version=2.1
group=Games
license=GPLv2
description="XBill"
src="x/xbill/$name-$version.tar.gz"

desktopTargetDir="/usr/local/share/applications"
desktopName="XBill"
genericName="Platform game"
exec=/usr/local/bin/xbill
comment="XBill"
categories="Game;"

showLongDescription()
{
    cat << "EOF"
XBill is an arcade style game for the X Window System. The game features a
bespectacled character known as "Bill". The goal is to prevent Bill's legions of
clones from installing "Wingdows", a virus "cleverly designed to resemble a
popular operating system", on a variety of computers running other operating
systems.
EOF
}

# '

buildPhase()
{
    ./configure --localstatedir=/var/lib
    make
}

installPhase()
{
    make install
}
