#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=flac
version=1.0.4
group=Libraries/Audio
license=LGPLv2/GPLv2
description="Free Lossless Audio Codec"
src="f/flac/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
FLAC stands for Free Lossless Audio Codec, an audio format similar to MP3, but
lossless, meaning that audio is compressed in FLAC without any loss in quality.
This is similar to how Zip works, except with FLAC you will get much better
compression because it is designed specifically for audio, and you can play back
compressed FLAC files in your favorite player just like you would an MP3 file.

FLAC stands out as the fastest and most widely supported lossless audio codec,
and the only one that at once is non-proprietary, is unencumbered by patents,
has an open-source reference implementation, has a well documented format and
API, and has several other independent implementations.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install
}
