#!/bin/bash -e

source $cbtFunctionsDir/deployDesktopSourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xsane
version=0.86
group=Hardware
license=GPLv2
description="XSane"
src="x/xsane/$name-$version.tar.gz"

desktopName="XSane - Scanning"
category=Graphics
comment="Acquire images from a scanner"
exec=xsane

showLongDescription()
{
    cat << "EOF"
XSane is a graphical scanning frontend. It uses the SANE library to talk to
scanners.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install

    # Install GIMP plugin
    if gimp-config --version
    then
        ln -sf /usr/bin/xsane /opt/gnome/lib/gimp/1.2/plug-ins
    fi
}
