#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=aspell-en
version=6.0_0
pkgVersion=6.0-0
group=Tools/Misc
license=GPLv2
description="English dictionary for aspell"
src="a/aspell/aspell6-en-$pkgVersion.tar.bz2"

showLongDescription()
{
    cat << "EOF"
English dictionary for aspell
EOF
}

buildPhase()
{
    ./configure
    make $globalBuildOptions
}

installPhase()
{
    make install
}
