#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xdg-menu
version=0.2
group=Tools/Misc
# License is not in the source package, but listed as GPLv2 on:
# https://build.opensuse.org/projects/openSUSE:Factory/packages/xdg-menu/files/xdg-menu.spec
license=GPLv2
description="XDG Menu converter"
src="x/xdg-menu/$name-$version.tar.bz2"
patches=("x/xdg-menu/xdg-menu-su.patch" "x/xdg-menu/xdg-menu-twm.patch")
defaultPatchLevel=0

showLongDescription()
{
    cat << "EOF"
This package contains a Perl script which converts XDG menus to formats used by
various kinds of window manager, such as WindowMaker, TWM and fvwm2.
EOF
}

buildPhase()
{
    # Fix path to kdesu
    sed -i 's|/opt/kde3/bin/kdesu|/opt/kde/bin/kdesu|g' xdg_menu
}

installPhase()
{
    install -m755 xdg_menu /usr/bin
    install -m755 xdg_menu_su /usr/bin

    mkdir -p /etc/xdg/menus
    install -m644 $cbtBaseDir/xdg/menus/ul-applications.menu /etc/xdg/menus
    install -m644 $cbtBaseDir/xdg/menus/gnome-kde.menu /etc/xdg/menus/ul-kde.menu
    install -m644 $cbtBaseDir/xdg/menus/kde-gnome.menu /etc/xdg/menus/ul-gnome.menu
}
