#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libXft
version=2.1.12
group=Display/X11/lib
license=MIT
description="libXft"
src="x/xorg/lib/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
X.org generated lib package: libXft
EOF
}

buildPhase()
{
    ./configure $XORG_CONFIG --with-xorg-module-dir=/usr/X11R7.3/lib/X11/modules
    make
}

installPhase()
{
    make install
}
