#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=alsa-lib
version=1.0.18
group=Hardware
license=GPLv2
description="ALSA libraries"
src="a/alsa-lib/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The ALSA Library package contains the ALSA library. This is used by programs
(including ALSA Utilities) requiring access to the ALSA sound interface.
EOF
}

buildPhase()
{
    ./configure --enable-static
    make $globalBuildOptions
}

installPhase()
{
    make install
    install -v -m644 -D doc/asoundrc.txt \
        /usr/share/doc/$name-$version/asoundrc.txt
}
