#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=alsa-utils
version=1.0.18
group=Hardware
license=GPLv2
description="ALSA utilities"
src="a/alsa-utils/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The alsa-utils package contains various utilities which are useful for
controlling your sound card.
EOF
}

buildPhase()
{
    ./configure
    make $globalBuildOptions
}

installPhase()
{
    make install

    cat > /etc/udev/rules.d/40-alsa.rules << "EOF"
# /etc/udev/rules.d/40-alsa.rules
# When a sound device is detected, restore the volume settings
KERNEL=="controlC[0-9]*", ACTION=="add", RUN+="/usr/sbin/alsactl restore %n"
EOF
    chmod -v 644 /etc/udev/rules.d/40-alsa.rules

    install -m754 $cbtBaseDir/init.d/alsa /etc/rc.d/init.d
    install -d -m755 /usr/share/ul/ul-init
    install -m644 $cbtBaseDir/plugins/ul-init/alsa /usr/share/ul/ul-init
}
