#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=cdrdao
version=1.2.3
group=Hardware
license=GPLv2
description="Tools for recording CDs disk at once"
src="c/cdrdao/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The cdrdao package contains CD recording utilities useful to record discs in
disk at once (DAO) mode.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
