#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=dvd+rw-tools
version=7.1
group=Hardware
license=GPLv2
description="Tools for DVD Recordables"
src="d/dvd+rw-tools/$name-$version.tar.gz"
patches=("d/dvd+rw-tools/$name-$version-headers-1.patch")

showLongDescription()
{
    cat << "EOF"
The dvd+rw-tools package contains several utilities to master the DVD media,
both +RW/+R and -R[W]. The principle tool is growisofs which provides a way to
both lay down and grow an ISO9660 file system on (as well as to burn an
arbitrary pre-mastered image to) all supported DVD media. This is useful for
creating a new DVD or adding to an existing image on a partially burned DVD. 
EOF
}

buildPhase()
{
    make all rpl8 btcflash
}

installPhase()
{
    make prefix=/usr install
    install -v -m644 -D index.html \
        /usr/share/doc/$name-$version/index.html
}
