#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gutenprint
version=5.2.6
group=Hardware
license=GPLv2
description="Gutenprint printing system"
src="g/gutenprint/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Gutenprint, formerly named Gimp-Print, is a suite of printer drivers that may
be used with most common UNIX print spooling systems, including CUPS, lpr,
LPRng, or others. These drivers provide high quality printing for UNIX
(including Macintosh OS X 10.3 and newer) and Linux systems in many cases equal
to or better than proprietary vendor-supplied drivers.

Gutenprint also includes an enhanced print plug-in for the GIMP image editor,
replacing the Gimp-Print 4.2-based plugin supplied with GIMP 1.2, 2.0, and 2.2,
and offering an alternative with additional capabilities to the GtkPrint-based
plugin supplied with GIMP 2.4 and beyond.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
