#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=isapnptools
version=1.27
group=Hardware
license=GPLv2
description="ISA Plug and Play tools"
src="i/isapnptools/$name-$version.tgz"

showLongDescription()
{
    cat << "EOF"
These programs allow ISA Plug-And-Play devices to be configured on a Linux
machine.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
