#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libgphoto2
version=2.4.7
group=Hardware
license=LGPLv2.1
description="Photo camera library"
src="l/libgphoto2/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
libgphoto2 is a library that can be used by applications to access various
digital cameras.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
