#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=wireless_tools
version=29
group=Hardware
license=GPLv2
description="Wireless tools"
src="w/wireless_tools/$name.$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
This package contains the Wireless tools, used to manipulate
the Wireless Extensions. The Wireless Extensions is an interface
allowing you to set Wireless LAN specific parameters and get the
specific stats.

It also contains the IfRename package, used for advance
renaming of network interfaces.
EOF
}

buildPhase()
{
    make
}

installPhase()
{
    make PREFIX=/usr install
}
