#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=ppp
version=2.4.4
group=Network/Tools
license=BSD
description="PPP daemon and chat program"
src="p/ppp/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
ppp is an open source package which implements the Point-to-Point Protocol (PPP)
on Linux and Solaris systems.
EOF
}

preConfigurePhase()
{
    groupadd -g 52 pppusers
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
    make install-etcppp

    install -d /etc/ppp/peers
    install -m755 scripts/{pon,poff,plog} /usr/bin
    install -m644 scripts/pon.1 /usr/share/man/man1
}
