#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=traceroute
version=2.0.12
group=Network/Tools
license=GPLv2
description="Traceroute tool"
src="t/traceroute/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
traceroute tracks the route packets taken from an IP network on
their way to a given host. It utilizes the IP protocol's time to
live (TTL) field and attempts to elicit an ICMP TIME_EXCEEDED
response from each gateway along the path to the host.
EOF
}

# '

buildPhase()
{
    make $globalBuildOptions
}

installPhase()
{
    make prefix=/usr install
}
