#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libexif
version=0.6.17
group=Libraries/Image
license=LGPLv2.1
description="EXIF headers library"
src="l/libexif/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
libexif is a library for parsing, editing, and saving EXIF data. It is
intended to replace lots of redundant implementations in command-line
utilities and programs with GUIs.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr \
        --with-doc-dir=/usr/share/doc/$name-$version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
