#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libgdiplus
version=2.6.7
group=Libraries/Image
license=MIT
description="Independent GDI+ implementation"
src="l/libgdiplus/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
libgdiplus: An Open Source implementation of the GDI+ API.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
