#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libpng
version=1.2.35
group=Libraries/Image
license=zlib
description="PNG library"
src="l/libpng/$name-$version.tar.bz2"
patches=("l/libpng/$name-$version-apng-1.patch")

showLongDescription()
{
    cat << "EOF"
libpng is the official PNG reference library. It supports almost all PNG
features, is extensible, and has been extensively tested for over 30 years.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
    install -v -m755 -d /usr/share/doc/$name-$version
    install -v -m644 README $name-$version.txt \
        /usr/share/doc/$name-$version
}
