#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=openexr
version=1.6.1
group=Libraries/Image
license=BSD-3
description="EXR codec library"
src="o/openexr/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
IlmImf is our "EXR" file format for storing 16-bit FP images.  Libraries in
this package depend on the IlmBase library.
EOF
}

buildPhase()
{
    # Fix compile errors due to missing header

    sed -i '1i\
#include <string.h>' IlmImf/ImfChromaticities.cpp
    sed -i '1i\
#include <string.h>' exrmaketiled/main.cpp
    sed -i '1i\
#include <string.h>' exrenvmap/main.cpp

    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
