#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=tiff
version=3.8.2
group=Libraries/Image
license=MIT
description="TIFF library"
src="t/tiff/$name-$version.tar.gz"
patches=("t/tiff/$name-$version-fixes-2.patch")

showLongDescription()
{
    cat << "EOF"
The libtiff package contains the TIFF libraries and associated utilities. The
libraries are used by many programs for reading and writing TIFF files and the
utilities are used for general work with TIFF files.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
