#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=Net-DBus
version=0.33.6
group=Libraries/Perl
license=AL/GPLv2
description="Perl XS API to the D-Bus messaging system"
src="n/Net-DBus/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Net::DBus provides a Perl XS API to the dbus inter-application messaging system.
The Perl API covers the core base level of the dbus APIs, not concerning itself
yet with the GLib or QT wrappers.
EOF
}

buildPhase()
{
    perl Makefile.PL
    make
}

installPhase()
{
    make install
}
