#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=XML-Twig
version=3.37
group=Libraries/Perl
license=AL
description="Expat XML parser extension for Perl"
src="x/XML-Twig/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
XML::Twig is (yet another!) XML transformation module. 

Its strong points: can be used to process huge documents while still
being in tree mode; not bound by DOM or SAX, so it is very perlish and
offers a very comprehensive set of methods; simple to use; DWIMs as
much as possible

What it doesn't offer: full SAX support (it can export SAX, but only
reads XML), full XPath support (unless you use XML::Twig::XPath), nor
DOM support.
EOF
}

# '

buildPhase()
{
    perl Makefile.PL -y
    make
}

installPhase()
{
    make install
}
