#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=XML-Simple
version=2.18
group=Libraries/Perl
license=AL
description="Easy API to read and write XML files"
src="x/XML-Simple/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Easy API to read/write XML (esp config files)
EOF
}

buildPhase()
{
    perl Makefile.PL
    make
}

installPhase()
{
    make install
}
