#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=db31
majorVersion=3.1
version=3.1.17
group=Libraries/Shared
license=BSD-3
description="Berkeley Database version 3.1"
src="d/db/db-$version.tar.gz"
workDir=db-$version/build_unix

showLongDescription()
{
    cat << "EOF"
Berkeley DB (BDB) is an embedded database software library for key/value data.
Berkeley DB is written in C with API bindings for many other programming
languages. BDB stores arbitrary key/data pairs as byte arrays and supports
multiple data items for a single key.

This version is the only version that GNOME Evolution is compatible with.
EOF
}

buildPhase()
{
    ../dist/configure --prefix=/opt/db-$majorVersion --enable-compat185
    make
}

installPhase()
{
    chown -R root:root ../*
    make install
}
