#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=kdesdk
version=3.5.10
group=Desktops/kde
license=GPLv2
description="KDE SDK"
src="k/kdesdk/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
This is a collection of applications and tools used by KDE developers.
It also has example code for use in learning KDE programming or starting
a new KDE application.

* cervisia: CVS client part
* kapptemplate: shell script to easy the beginning of new apps
* kexample: a sample KDE application, heavily documented
* kbabel: an editor for *.po files
* kbugbuster: a graphical frontend for the KDE bug reporting system
* kdepalettes: palettes matching KDE's style for Gimp and XPaint
* kmtrace: converts glibc's mtrace log into a full backtrace
* kspy: displays all used QObjects in an application
* kstartperf: startup time measurement
* poxml: 
* scripts: various helper scripts (see scripts/README)
* scheck: An interface style to highlight accel and style guide conflicts
* kuiviewer: A KPart that lets you view .ui files.
* umbrello: A UML modeller.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/kde-$kdeVersion --disable-debug \
        --disable-dependency-tracking
    make $globalBuildOptions
}

installPhase()
{
    make install
}
