#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=kdeutils
version=3.5.10
group=Desktops/kde
license=GPLv2
description="KDE utilities"
src="k/kdeutils/$name-$version.tar.bz2"
patches=("k/kdeutils/$name-$version-python26-1.patch")

showLongDescription()
{
    cat << "EOF"
A collection of utilities that integrate well with the KDE desktop:

* ark: manager for compressed files and archives
* kcalc: scientific calculator
* kcharselect: select special characters from any fonts and put them into
               the clipboard
* charselectapplet: dito, but as a Kicker applet
* kdepasswd: like 'passwd', a graphical password changer
* kdessh: front end to ssh
* kdf: like 'df', a graphical free disk space viewer
* kedit: a simple text editor, without formatting like bold, italics etc
* kfloppy: format a floppy disks with this app
* khexedit: binary file editor
* kjots: manages several "books" with a subject and notes
* klaptopdaemon: battery and power management, including KControl plugins
* kregexpeditor: graphical regular expression editor
* ktimer: execute programs after some time
EOF
}

# '

buildPhase()
{
    ./configure --prefix=/opt/kde-$kdeVersion --disable-debug \
        --disable-dependency-tracking
    make $globalBuildOptions
}

installPhase()
{
    make install
}
