#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=kdevelop
version=3.5.4
group=Desktops/kde
license=GPLv2
description="KDE development IDE"
src="k/kdevelop/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
KDevelop provides an Integrated Development Environment (IDE) to be used for a
wide variety of programming tasks.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/kde-$kdeVersion --disable-debug \
        --disable-dependency-tracking
    make $globalBuildOptions
}

installPhase()
{
    make install
}
