#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=kdewebdev
version=3.5.10
group=Desktops/kde
license=GPLv2
description="KDE web development utilities"
src="k/kdewebdev/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The kdewebdev package contains Quanta Plus and other applications, which are
useful for web development. They are runtime dependencies of Quanta Plus, and
it is highly recommended that you install them.

The extra applications are:

Kommander: a GUI script builder and executor tool. Needed for some Quanta functionality.
KFileReplace: powerful search and replace in multiple files
KXSLDbg: XSL debugger
KImageMapEditor: image map editor
KLinkStatus: link checker
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/kde-$kdeVersion --disable-debug \
        --disable-dependency-tracking
    make $globalBuildOptions
}

installPhase()
{
    make install
}
