#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=konversation
version=1.1
group=Desktops/kde
license=GPLv2
description="IRC client for KDE"
src="k/konversation/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Konversation is a user-friendly Internet Relay Chat (IRC) client which provides
easy access to standard IRC networks such as Libera, where the KDE IRC channels
can be found.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/kde-$kdeVersion
    make $globalBuildOptions
}

installPhase()
{
    make install
}
