#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=krename
version=3.0.14
group=Desktops/kde
license=GPLv2
description="Batch renaming tool for KDE"
src="k/krename/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Krename is a very powerful batch file renamer for KDE3.

Features include:
- renaming a list of files based on a set of expressions
- copying/moving a list of files to another directory
- convert filenames to upper/lower case
- adding numbers to filenames
- finding and replacing parts of the filename
- rename Mp3/Ogg Vorbis files based on their ID3 tags.
- setting access and modification dates
- permissions and file ownership
- a plug-in API which allows you to extend krename's features
- rename directories recursively
- support for KFilePlugins
- create undo file
- and many more...
EOF
}

# '

buildPhase()
{
    ./configure --prefix=/opt/kde-$kdeVersion
    make $globalBuildOptions
}

installPhase()
{
    make install
}
