#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/bash

group=lfs-stage2

buildPhase()
{
    ./configure --prefix=/usr --with-curses \
      --bindir=/bin
    make
}

installPhase()
{
    make install
    cd /bin
    ln -sf bash sh

    mkdir -p /usr/lib/ul-adduser
    cat > /usr/lib/ul-adduser/bash << "EOF"
shellPath=/bin/bash
description="Bourne Again SHell"
EOF

    cat > /usr/lib/ul-adduser/sh << "EOF"
shellPath=/bin/sh
description="Generic Bourne-compatible shell"
EOF
}
