#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings

name=bin86
version=0.16.2
group=lfs-stage2
description="bin86"
license=GPLv2
src="b/bin86/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
This is the as86 and ld86 distribution written by Bruce Evans. It's a complete
8086 assembler and loader which can make 32-bit code for the 386+ processors.
EOF
}

# '

buildPhase()
{
    make
}

installPhase()
{
    make PREFIX=/usr install
}
