#!/bin/bash -e

source $cbtBaseDir/settings/lfs-settings

name=create-essential-symlinks
group=lfs-stage2
description="Creates essential symlinks"

execute()
{
    # NOTE: this symlink was already created in stage1
    #ln -s /stage1/bin/bash /bin/bash

    ln -s bash /bin/sh
    ln -s /stage1/bin/cat /bin/cat
    ln -s /stage1/bin/pwd /bin/pwd
    ln -s /stage1/bin/stty /bin/stty
}
