#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/gawk

group=lfs-stage2

buildPhase()
{
    cp awklib/Makefile.in awklib/Makefile.in.backup
    sed -e '/^datadir/s/awk/gawk/' \
      -e '/^libexecdir/s%/awk%%' awklib/Makefile.in.backup \
      > awklib/Makefile.in
    ./configure --prefix=/usr --libexecdir=/usr/bin
    make
}

installPhase()
{
    make install
}
