#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/gcc

group=lfs-stage2
patches=("g/gcc/$name-$version-2.patch.bz2" "g/gcc/$name-$version-no_fixinc-1.patch")
workDir=$name-$version

buildPhase()
{
    mkdir ../$name-build
    cd ../$name-build
    CFLAGS="-O2 -pipe" CXXFLAGS="-O2 -pipe" ../$name-$version/configure --prefix=/usr \
       --enable-shared --enable-threads=posix \
       --enable-__cxa_atexit --enable-clocale=gnu
    make LDFLAGS="-s"
    # make -k check
}

installPhase()
{
    chown -R root:root *
    cd ../$name-build
    chown -R root:root *
    make install
    ln -sf ../usr/bin/cpp /lib
    ln -sf gcc /usr/bin/cc
    rm /usr/lib/libiberty.a

    # Create a symlink to provide ABI compatibility with older C++ binaries,
    # such as Netscape Communicator 4.8
    cd /usr/lib
    ln -sf libstdc++-3-libc6.2-2.10.0.so libstdc++-libc6.1-1.so.2
}
