#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/glibc

group=lfs-stage2
workDir=$name-$version
files=("g/glibc/$name-$version-mtab.patch")

buildPhase()
{
    mv ../linuxthreads* .
    cp malloc/Makefile malloc/Makefile.backup
    sed 's%\$(PERL)%/usr/bin/perl%' malloc/Makefile.backup > malloc/Makefile
    cp login/Makefile login/Makefile.backup
    sed 's/root/0/' login/Makefile.backup > login/Makefile
    cat $sourcesDir/${files[0]} | patch -p1
    mkdir ../$name-build
    cd ../$name-build
    CFLAGS="-O2 -pipe" ../$name-$version/configure --prefix=/usr \
      --enable-add-ons --disable-profile --libexecdir=/usr/bin \
      --with-headers=/usr/include
    echo "cross-compiling = no" > configparms
    make
}

installPhase()
{
    cd ../$name-build
    touch /etc/ld.so.conf
    make install
    make localedata/install-locales
}
