#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/gzip

group=lfs-stage2

buildPhase()
{
    ./configure --prefix=/usr
    cp gzexe.in gzexe.in.backup
    sed 's%"BINDIR"%/bin%' gzexe.in.backup > gzexe.in
    make
}

installPhase()
{
    make install
    cd /usr/bin
    mv gzip /bin
    rm gunzip zcat
    cd /bin
    ln -sf gzip gunzip
    ln -sf gzip zcat
    ln -sf gunzip uncompress
}
