#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings

name=lfs-bootscripts
version=1.9
group=lfs-stage2
description="LFS Bootscripts"
license=BSD
src="l/lfs-bootscripts/$name-$version.tar.bz2"
patches=("l/lfs-bootscripts/$name-$version-mtab.patch")

showLongDescription()
{
    cat << "EOF"
The LFS-Bootscripts package contains a set of scripts to start/stop the LFS
system at bootup/shutdown.
EOF
}

buildPhase()
{
    true
}

installPhase()
{
    cp -a rc.d sysconfig /etc
    chown -R root.root /etc/rc.d /etc/sysconfig

    # Adjust the network termination process so that it stops before sending signals
    # The dhcpcd daemon needs to be properly shut down first

    cd /etc/rc.d/rc0.d
    mv K80network K45network
    cd ../rc6.d
    mv K80network K45network
}
