#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings

name=linux
version=2.4.23 # 2.4.18
license=GPLv2
group=lfs-stage2
description="Linux"
src="l/linux/$name-$version.tar.bz2"
buildAsRoot=true

showLongDescription()
{
    cat << "EOF"
The Linux kernel is at the core of every Linux system. It's what makes Linux
tick. When a computer is turned on and boots a Linux system, the very first
piece of Linux software that gets loaded is the kernel.

The kernel initializes the system's hardware components such as serial ports,
parallel ports, sound cards, network cards, IDE controllers, SCSI controllers
and a lot more. In a nutshell, the kernel makes the hardware available so that
the software can run.
EOF
}

preUnpack()
{
    cd /usr/src
}

postUnpack()
{
    echo
    #mv /usr/src/$name /usr/src/$name-$version # not needed with 2.4.21
}

openWorkDirPhase()
{
    chown -R root:root /usr/src/$name-$version
    cd /usr/src/$name-$version
}

buildPhase()
{
    make mrproper
    make menuconfig > /dev/tty1
    make dep
    make bzImage
    make modules
}

installPhase()
{
    make modules_install
    cp -v arch/i386/boot/bzImage /boot/lfskernel-$version
    cp -v System.map /boot/System.map-$version
    cp -v .config /boot/config-$version
}
