#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/linux-headers

group=lfs-stage2

buildPhase()
{
    make mrproper
    make include/linux/version.h
    make symlinks
}

installPhase()
{
    mkdir -p /usr/include/asm
    cp include/asm/* /usr/include/asm
    cp -R include/asm-generic /usr/include
    cp -R include/linux /usr/include
    touch /usr/include/linux/autoconf.h
}
