#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/make

group=lfs-stage2

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install
    chgrp root /usr/bin/make
    chmod 755 /usr/bin/make
}
