#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings

name=mktemp
version=1.4
group=lfs-stage2
description="mktemp"
license=BSD-3
src="m/mktemp/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
mktemp is a small program to allow safe temporary file creation from shell scripts.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install
}
