#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings

name=modutils
version=2.4.15
group=lfs-stage2
description="Module utilities"
license=GPLv2
src="m/modutils/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
The modutils package contains utilities that are intended to make a Linux
modular kernel manageable for all users, administrators and distribution
maintainers.
EOF
}

buildPhase()
{
    ./configure
    make
}

installPhase()
{
    make install
}
