#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings

name=net-tools
version=1.60
group=lfs-stage2
description="Network tools"
license=GPLv2
src="n/net-tools/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
A collection of programs that form the base set of the NET-3 networking
distribution for the Linux operating system.
EOF
}

buildPhase()
{
    yes "" | make
}

installPhase()
{
    make update
}
