#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/perl

group=lfs-stage2

buildPhase()
{
    ./configure.gnu --prefix=/usr
    make
}

installPhase()
{
    make install
}
