#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings

name=shadow
version=4.0.3
group=lfs-stage2
description="Shadow password suite"
license=BSD
src="s/shadow/$name-$version.tar.bz2"
patches=("s/shadow/$name-$version-newgrp_fix-1.patch" "s/shadow/$name-$version-pam-2.patch" "s/shadow/$name-$version-DISPLAY-1.patch")

showLongDescription()
{
    cat << "EOF"
The Shadow Password Suite consists of a collection of library modules and
administrative utilities which provide for enhanced system security.
EOF
}

buildPhase()
{
    LDFLAGS="-lpam -lpam_misc" ./configure --prefix=/usr --enable-shared --with-libpam
    make
}

installPhase()
{
    make install
    cp debian/securetty /etc
    cd etc
    cp limits login.access /etc

    sed -e 's%/var/spool/mail%/var/mail%' \
      -e 's|#MD5_CRYPT_ENAB	no|#MD5_CRYPT_ENAB	yes|' \
      -e "s/^DIALUPS_CHECK_ENAB/# &/" \
      -e "s/^LASTLOG_ENAB/# &/" \
      -e "s/^MAIL_CHECK_ENAB/# &/" \
      -e "s/^PORTTIME_CHECKS_ENAB/# &/" \
      -e "s/^CONSOLE/# &/" \
      -e "s/^MOTD_FILE/# &/" \
      -e "s/^NOLOGINS_FILE/# &/" \
      -e "s/^PASS_MIN_LEN/# &/" \
      -e "s/^SU_WHEEL_ONLY/# &/" \
      -e "s/^CONSOLE_GROUPS/# &/" \
      -e "s/^ENVIRON_FILE/# &/" \
      login.defs.linux > /etc/login.defs
    cd /usr/sbin
    ln -sf vipw vigr
    rm /bin/vipw
    mv /bin/sg /usr/bin
    cd /lib
    mv libmisc.*a libshadow.*a /usr/lib
    cd /usr/lib
    ln -sf ../../lib/libshadow.so

    # This fix is not in the book but the la file contains a wrong reference to libmisc.la
    # KDE fails to compile as a result
    sed 's|/lib/libmisc.la|/usr/lib/libmisc.la|' /usr/lib/libshadow.la > /usr/lib/libshadow.la.new
    mv /usr/lib/libshadow.la.new /usr/lib/libshadow.la

    mkdir -p /etc/pam.d

    cat > /etc/pam.d/login << "EOF"
# Begin /etc/pam.d/login

auth        requisite      pam_securetty.so
auth        requisite      pam_nologin.so
auth        required       pam_env.so
auth        required       pam_unix.so
account     required       pam_access.so
account     required       pam_unix.so
session     required       pam_motd.so
session     required       pam_limits.so
session     optional       pam_mail.so     dir=/var/mail standard
session     optional       pam_lastlog.so
session     required       pam_unix.so

# End /etc/pam.d/login
EOF

    cat > /etc/pam.d/passwd << "EOF"
# Begin /etc/pam.d/passwd

password    required       pam_unix.so     md5 shadow 

# End /etc/pam.d/passwd
EOF

    cat > /etc/pam.d/shadow << "EOF"
# Begin /etc/pam.d/shadow

auth        sufficient      pam_rootok.so
auth        required        pam_unix.so
account     required        pam_unix.so
session     required        pam_unix.so
password    required        pam_permit.so

# End /etc/pam.d/shadow
EOF

    cat > /etc/pam.d/su << "EOF"
# Begin /etc/pam.d/su

auth        sufficient      pam_rootok.so
auth        required        pam_unix.so
account     required        pam_unix.so
session     required        pam_unix.so

# End /etc/pam.d/su
EOF

    cat > /etc/pam.d/useradd << "EOF"
# Begin /etc/pam.d/useradd

auth        sufficient      pam_rootok.so
auth        required        pam_unix.so
account     required        pam_unix.so
session     required        pam_unix.so
password    required        pam_permit.so

# End /etc/pam.d/useradd
EOF

    cat > /etc/pam.d/chage << "EOF"
# Begin /etc/pam.d/chage

auth        sufficient      pam_rootok.so
auth        required        pam_unix.so
account     required        pam_unix.so
session     required        pam_unix.so
password    required        pam_permit.so

# End /etc/pam.d/chage
EOF

    cat > /etc/pam.d/other << "EOF"
# Begin /etc/pam.d/other

auth        required        pam_deny.so
auth        required        pam_warn.so
account     required        pam_deny.so
session     required        pam_deny.so
password    required        pam_deny.so
password    required        pam_warn.so

# End /etc/pam.d/other
EOF
}
