#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/tar

group=lfs-stage2
patches=("t/tar/$name-$version.patch.bz2")

buildPhase()
{
    ./configure --prefix=/usr --libexecdir=/usr/bin \
      --bindir=/bin
    make
}

installPhase()
{
    make install
}
