#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/texinfo

group=lfs-stage2

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install
    make TEXMF=/usr/share/texmf install-tex
}
