#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/textutils

group=lfs-stage2

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install
    mv /usr/bin/cat /usr/bin/head /bin
}
