#!/bin/bash -e

source $cbtBaseDir/settings/lfs-settings

name=tmpfiles-configure
group=lfs-stage2
description="Creates required temp files"

execute()
{
    touch /var/run/utmp /var/log/{btmp,lastlog,wtmp}
    chmod 644 /var/run/utmp /var/log/{btmp,lastlog,wtmp}
}
