#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/util-linux

group=lfs-stage2

buildPhase()
{
    cp hwclock/hwclock.c hwclock/hwclock.c.backup &&
    sed 's%etc/adjtime%var/lib/hwclock/adjtime%' \
      hwclock/hwclock.c.backup > hwclock/hwclock.c &&

    ./configure
    make HAVE_SLN=yes
}

installPhase()
{
    make HAVE_SLN=yes install
    mkdir -p /var/lib/hwclock
}
