#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=kdeaddons
version=2.2.2
group=Desktops/kde
license=GPLv2
description="KDE addons"
src="k/kdeaddons/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
A collection of plugins and scripts for KDE applications to enhance its
functionality.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/kde-$kdeVersion --disable-debug --enable-final
    make
}

installPhase()
{
    make install
}
