#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=kdegraphics
version=2.2.2
group=Desktops/kde
license=GPLv2
description="KDE graphics"
src="k/kdegraphics/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
A collection of graphical oriented applications for the KDE desktop.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/kde-$kdeVersion --disable-debug --enable-final
    make
}

installPhase()
{
    make install
}
