#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=kdemultimedia
version=2.2.2
group=Desktops/kde
license=GPLv2
description="KDE multimedia"
src="k/kdemultimedia/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
A collection of audio and video applications and plugins for the KDE desktop.
EOF
}

buildPhase()
{
    ( echo "#undef __STRICT_ANSI__"
      cat mpeglib/lib/input/cdromAccess_Linux.cpp
    ) > mpeglib/lib/input/cdromAccess_Linux.cpp.new

    mv mpeglib/lib/input/cdromAccess_Linux.cpp.new mpeglib/lib/input/cdromAccess_Linux.cpp

    ./configure --prefix=/opt/kde-$kdeVersion --disable-debug --enable-final
    make
}

installPhase()
{
    make install
}
