#!/bin/bash -e

source $cbtFunctionsDir/deployDesktopSourcePackage
source $cbtBaseDir/settings/extra-settings

name=tilem
version=0.925r2
license=LGPLv2.1
group=Emulators
description="TI 8x emulator"
src="t/tilem/${name}_0-925r2.tar.gz"

desktopName="TilEm"
category=Emulators
exec=tilem
comment="TI 8x emulator"

showLongDescription()
{
    cat << "EOF"

TilEm is an emulator and debugger for Texas Instruments Z80-based graphing
calculators. It can emulate any of the following calculator models: TI-73,
TI-73 Explorer, TI-76.fr, TI-81, TI-82, TI-82 STATS / TI-82 STATS.fr, TI-83,
TI-83 Plus, TI-83 Plus Silver Edition, TI-83 Plus.fr, TI-84 Plus, TI-84 Plus
Silver Edition, TI-84 pocket.fr, TI-85, TI-86.
EOF
}

buildPhase()
{
    cp src/tilem/Makefile src/tilem/Makefile.orig
    sed 's|gtkc = |gtkc = -I/opt/gnome/include |' src/tilem/Makefile.orig > src/tilem/Makefile
    make
}

installPhase()
{
    make install
}
