#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=Wine
name2=wine
version=20030318
license=LGPLv2.1
group=Emulators
description="WINE Is Not an Emulator"
src="w/Wine/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Wine is a program making it possible to run Microsoft Windows programs on UNIX.
It consists of a program loaded which loads and executes a Microsoft Windows
binrary and a library (called winelib) that implements Windows API calls using
their UNIX or X11 equivalents. The library may also be used for porting Win32
code into native UNIX executables.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/$name2-$version \
      --mandir=/opt/$name2-$version/share/man
    make depend
    make
}

installPhase()
{
    make install
    ln -s /opt/$name2-$version /opt/$name2

    # Install sample configuration documentation
    mkdir -p /opt/$name2-$version/share/doc/wine
    cp -av documentation/samples /opt/$name2-$version/share/doc/wine
    chown -R root:root /opt/$name2-$version/share/doc/wine

    # Install profile scripts
    install -m755 $cbtBaseDir/profile.d/40wine.sh /etc/profile.d
    if which csh
    then
        install -m755 $cbtBaseDir/profile.d/40wine.csh /etc/profile.d
    fi
}
