#!/bin/bash -e

name=coreutils
version=6.12
description="GNU Coreutils"
license=GPLv3
src="c/coreutils/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
These are the GNU core utilities.  This package is the union of
the GNU fileutils, sh-utils, and textutils packages.

Most of these programs have significant advantages over their Unix
counterparts, such as greater speed, additional options, and fewer
arbitrary limits.

The programs that can be built with this package are:

  [ arch base64 basename cat chcon chgrp chmod chown chroot cksum comm cp
  csplit cut date dd df dir dircolors dirname du echo env expand expr
  factor false fmt fold groups head hostid hostname id install join kill
  link ln logname ls md5sum mkdir mkfifo mknod mktemp mv nice nl nohup
  nproc od paste pathchk pinky pr printenv printf ptx pwd readlink rm rmdir
  runcon seq sha1sum sha224sum sha256sum sha384sum sha512sum shred shuf
  sleep sort split stat stdbuf stty su sum sync tac tail tee test timeout
  touch tr true truncate tsort tty uname unexpand uniq unlink uptime users
  vdir wc who whoami yes
EOF
}
