#!/bin/bash -e

name=findutils
version=4.4.2
description="GNU Findutils"
license=GPLv3
src="f/findutils/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
The GNU Find Utilities are the basic directory searching utilities of the GNU
operating system. These programs are typically used in conjunction with other
programs to provide modular and powerful directory search and file locating
capabilities to other commands.
EOF
}
