#!/bin/bash -e

name=gcc
version=4.3.6
description="GNU Compiler Collection"
license=GPLv3
src="g/gcc/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The GNU Compiler Collection includes front ends for C, C++, Objective-C,
Fortran, and Java well as libraries for these languages (libstdc++,...).

GCC was originally written as the compiler for the GNU operating system.
EOF
}
