#!/bin/bash -e

name=linux-headers
version=2.6.27.57
description="Linux headers"
license=GPLv2
src="l/linux/linux-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
This package only contains the Linux kernel headers that are required by glibc
EOF
}
