#!/bin/bash -e

name=tcl
version=8.5.5
description="Tool Command Language"
license=tcl
src="t/tcl/${name}${version}-src.tar.gz"
workDir="${name}${version}/unix"

showLongDescription()
{
    cat << "EOF"
Tcl (Tool Command Language) is a very powerful but easy to learn dynamic
programming language, suitable for a very wide range of uses, including web and
desktop applications, networking, administration, testing and many more.
EOF
}
