#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=nfs-utils
version=1.1.6
group=Network/Servers-Clients
license=GPLv2
description="NFS utilities"
src="n/nfs-utils/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The NFS Utilities package contains the userspace server and client tools
necessary to use the kernel's NFS abilities. NFS is a protocol that allows
sharing file systems over the network.
EOF
}

# '

buildPhase()
{
    ./configure --prefix=/usr \
        --sysconfdir=/etc \
        --disable-nfsv4 \
        --disable-gss
    make $globalBuildOptions
}

installPhase()
{
    make install
    install -m754 $cbtBaseDir/init.d/nfs-server /etc/rc.d/init.d
    install -m754 $cbtBaseDir/init.d/nfs-client /etc/rc.d/init.d
    install -d -m755 /usr/share/ul/ul-init
    install -m644 $cbtBaseDir/plugins/ul-init/nfs-server /usr/share/ul/ul-init
    install -m644 $cbtBaseDir/plugins/ul-init/nfs-client /usr/share/ul/ul-init
}
