#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=exempi
version=2.1.1
group=Libraries/FileFormats
license=BSD-3
description="Adobe XMP support"
src="e/exempi/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
exempi is a port of Adobe XMP SDK to work on UNIX and to be build with 
GNU automake. It includes XMPCore and XMPFiles, and exempi, a C-based API.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
