#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=icu4c
version=4.0
version2=4_0
group=Libraries/FileFormats
license=MIT
description="ICU4C unicode library"
src="i/icu4c/$name-$version2-src.tgz"
workDir="icu/source"

showLongDescription()
{
    cat << "EOF"
The International Components for Unicode (ICU) libraries provide robust and
full-featured Unicode services on a wide variety of platforms to help this
design goal.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
