#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libcue
version=1.4.0
group=Libraries/FileFormats
license=GPLv2
description="CUE sheet parsing library"
src="l/libcue/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
libcue provides an API for parsing and extracting data from CUE sheets.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
