#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libogg
version=1.1.4
group=Libraries/FileFormats
license=BSD
description="OGG bitstreams library"
src="l/libogg/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Libogg contains necessary functionality to create, decode, and work with Ogg
bitstreams.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
