#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libwpd
version=0.8.14
group=Libraries/FileFormats
license=LGPLv2.1
description="WordPerfect parsing library"
src="l/libwpd/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
libwpd is a C++ library designed to help process WordPerfect documents. It is
most commonly used to import WordPerfect documents into other word processors,
but may be useful in other cases as well.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
