#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=wv2
version=0.3.1
group=Libraries/FileFormats
license=LGPLv2
description="Word file access library"
src="w/wv2/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
wv is a library which allows access to Microsoft Word files. It can load and
parse Word 2000, 97, 95 and 6 file formats. (These are the file formats known
internally as Word 9, 8, 7 and 6.) There is some support for reading earlier
formats as well: Word 2 docs are converted to plaintext.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
