#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=db2
majorVersion=2.7
version=2.7.7
group=Libraries/Shared
license=BSD-3
description="Berkeley Database version 2.7"
src="d/db/db-$version.tar.gz"
workDir=db-$version/build_unix

showLongDescription()
{
    cat << "EOF"
Berkeley DB (BDB) is an embedded database software library for key/value data.
Berkeley DB is written in C with API bindings for many other programming
languages. BDB stores arbitrary key/data pairs as byte arrays and supports
multiple data items for a single key.
EOF
}

buildPhase()
{
    ../dist/configure --prefix=/opt --enable-compat185
    make
}

installPhase()
{
    chown -R root:root ../*
    make install
    mv /opt/BerkeleyDB /opt/db-$majorVersion
    cd /opt/db-$majorVersion/include
    sed 's/^DB185/DB/' db_185.h > db_185.h.new
    mv db_185.h.new db_185.h
}
