#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libpcap
version=0.7.2
group=Libraries/Shared
license=BSD
description="Packet capturing library"
src="l/libpcap/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
libpcap provides a portable framework for low-level network monitoring
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install
}
