#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libxml2
version=2.4.30
group=Libraries/Shared
license=MIT
description="XML parser library"
src="l/libxml2/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
libxml2 is an XML toolkit implemented in C, originally developed for the GNOME
Project.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    chown -R root:root *
    make install
}
