#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=openjade
version=1.3.2
group=Libraries/Shared
license=MIT
description="DSSSL transformation engine"
src="o/openjade/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
OpenJade provides an implementation of DSSSL -- Document Style Semantics and
Specification Language -- an ISO standard for formatting SGML (and XML)
documents.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --disable-static --enable-http \
      --enable-default-catalog=/etc/sgml/catalog \
      --enable-default-search-path=/usr/share/sgml \
      --datadir=/usr/share/sgml/$name-$version
    make
}

installPhase()
{
    make install

    ln -sf openjade /usr/bin/jade
    ln -sf libogrove.so /usr/lib/libgrove.so
    ln -sf libospgrove.so /usr/lib/libspgrove.so
    ln -sf libostyle.so /usr/lib/libstyle.so
    install -m644 dsssl/catalog /usr/share/sgml/$name-$version/
    install -m644 dsssl/*.dtd dsssl/*.dsl dsssl/*.sgm \
      /usr/share/sgml/$name-$version
    install-catalog --add /etc/sgml/$name-$version.cat \
      /usr/share/sgml/$name-$version/catalog
    install-catalog --add /etc/sgml/sgml-docbook.cat /etc/sgml/$name-$version.cat
}
