#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=readline
version=4.3
group=Libraries/Shared
license=GPLv2
description="Readline library"
src="r/readline/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
The GNU Readline library provides a set of functions for use by applications
that allow users to edit command lines as they are typed in. Both Emacs and vi
editing modes are available.

The Readline library includes additional functions to maintain a list of
previously-entered command lines, to recall and perhaps reedit those lines, and
perform csh-like history expansion on previous commands.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install
}
