#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=tk
version=8.4.4
group=Programming
license=tcl
description="Tk graphical toolkit for Tcl"
src="t/tk/${name}${version}-src.tar.gz"
workDir="${name}${version}/unix"

showLongDescription()
{
    cat << "EOF"
Tk is a graphical user interface toolkit that takes developing desktop
applications to a higher level than conventional approaches. Tk is the standard
GUI not only for Tcl, but for many other dynamic languages, and can produce
rich, native applications that run unchanged across Windows, Mac OS X, Linux and
more.
EOF
}

buildPhase()
{
    CFLAGS="$CFLAGS -I/usr/include/tcl8.4/generic" \
      ./configure --prefix=/usr
    make
}

installPhase()
{
    V=`echo $version | cut -d "." -f 1,2`
    DIR=$PWD
    cp tkConfig.sh tkConfig.sh.orig
    sed -e "s:${DIR}/unix:/usr/lib:" \
      -e "s:${DIR}:/usr/include/tk${V}:" \
      tkConfig.sh.orig > tkConfig.sh
    make install
    install -d /usr/include/tk${V}/unix
    install -m644 *.h /usr/include/tk${V}/unix/
    install -d /usr/include/tk${V}/generic
    install -m644 ../generic/*.h /usr/include/tk${V}/generic/
    rm -f /usr/include/tk${V}/generic/{tk,tkDecls,tkPlatDecls}.h
    ln -nsf /usr/include/tk${V} /usr/lib/tk${V}/include
    ln -sf libtk${V}.so /usr/lib/libtk.so
    ln -sf wish${V} /usr/bin/wish
}
