#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libdvdcss
version=1.2.10
group=Libraries/Video
license=GPLv2
description="DVD CSS library"
src="l/libdvdcss/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
libdvdcss is a free and open-source software library for accessing DVDs
encrypted with Content Scramble System (CSS).
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
