#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libfame
version=0.9.1
group=Libraries/Video
license=LGPLv2
description="Fame MPEG encoder"
src="l/libfame/$name-$version.tar.gz"
patches=("l/libfame/$name-$version-gcc34-1.patch")

showLongDescription()
{
    cat << "EOF"
libFAME is a library for fast (real-time) MPEG video encoding, written
in C and assembly. libFAME currently allows encoding of fast MPEG-1 video, 
as well as MPEG-4 (OpenDivX compatible) rectangular and arbitrary shaped video.
This is the first public release of that library, for beta testing.
EOF
}

buildPhase()
{
    sed -i 's/$CC --version/$CC -dumpversion/' configure
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
