#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libmpeg2
version=0.5.1
group=Libraries/Video
license=GPLv2
description="MPEG-1 and MPEG-2 video decoder"
src="l/libmpeg2/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
libmpeg2 is a free library for decoding mpeg-2 and mpeg-1 video streams.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
