#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libtheora
version=1.1.1
group=Libraries/Video
license=BSD-3
description="Theora library"
src="l/libtheora/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Theora is Xiph.Org's first publicly released video codec, intended
for use within the Foundation's Ogg multimedia streaming system.
Theora is derived directly from On2's VP3 codec; Currently the 
encoders are nearly identical, but Theora will make use of new
features supported by the decoder to improve on what is possible
with VP3.
EOF
}

# '

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
