#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=Guppi
version=0.40.3
group=Desktops/gnome
license=GPLv2
description="GNOME-based scriptable plot program"
src="g/Guppi/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Guppi is a GPLed GNOME-based Guile-scriptable plot program with integratable
statistics capabilities.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnomeVersion
    make
}

installPhase()
{
    make install
}
