#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=pl
version=5.8.3
group=Programming
license=LGPLv2.1
description="SWI Prolog"
src="p/pl/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
SWI-Prolog offers a comprehensive free Prolog environment. Since its start in
1987, SWI-Prolog development has been driven by the needs of real world
applications. SWI-Prolog is widely used in research and education as well as
commercial applications.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
