#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=a2ps
version=4.13b
group=Tools/Graphics
license=psutils
description="Any to PostScript converter"
src="a/a2ps/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
GNU a2ps is an Any to PostScript filter. Of course it processes plain text
files, but also pretty prints quite a few popular languages.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --enable-paths=yes
    make
}

installPhase()
{
    make install
}

