#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=docbook-dsssl
version=1.79
group=Libraries/Docbook
license=MIT
description="Docbook DSSSL stylesheets"
src="d/docbook-dsssl/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The docbook-dsssl package contains DSSSL stylesheets. These are used by
openjade or other tools to transform SGML and XML DocBook files.
EOF
}

buildPhase()
{
    echo
}

installPhase()
{
    install -v -m755 bin/collateindex.pl /usr/bin
    install -v -m644 bin/collateindex.pl.1 /usr/share/man/man1
    install -v -d -m755 /usr/share/sgml/docbook/dsssl-stylesheets-1.79
    cp -v -R * /usr/share/sgml/docbook/dsssl-stylesheets-$version
}

postConfigurePhase()
{
    install-catalog --add /etc/sgml/dsssl-docbook-stylesheets.cat \
        /usr/share/sgml/docbook/dsssl-stylesheets-$version/catalog
    install-catalog --add /etc/sgml/dsssl-docbook-stylesheets.cat \
        /usr/share/sgml/docbook/dsssl-stylesheets-$version/common/catalog
    install-catalog --add /etc/sgml/sgml-docbook.cat \
        /etc/sgml/dsssl-docbook-stylesheets.cat
}
