#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gle
version=3.1.0
group=Libraries/X
license=GPLv2
description="Graphics Layout Engine"
src="g/gle/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
GLE is a library package of C functions that draw extruded surfaces, including
surfaces of revolution, sweeps, tubes, polycones, polycylinders and helicoids.
Generically, the extruded surface is specified with a 2D polyline that is
extruded along a 3D path. A local coordinate system allows for additional
flexibility in the primitives drawn. Extrusions may be texture mapped in a
variety of ways. The GLE library generates 3D triangle coordinates, lighting
normal vectors and texture coordinates as output.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
