#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libdrm
version=2.3.0
group=Libraries/X
license=X11
description="Direct Rendering Manager library"
src="l/libdrm/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
libdrm is a userspace library for accessing the DRM, direct rendering manager,
on Linux, BSD and other operating systes that support the ioctl interface.

The library provides wrapper functions for the ioctls to avoid exposing the
kernel interface directly, and for chipsets with drm memory manager, support for
tracking relocations and buffers.

libdrm is a low-level library, typically used by graphics drivers such as the
Mesa DRI drivers, the X drivers, libva and similar projects.
EOF
}

buildPhase()
{
    ./configure --prefix=$XORG_PREFIX
    make $globalBuildOptions
}

installPhase()
{
    make install
}
