#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xcb-util
version=0.3.1
group=Libraries/X
license=X11
description="XCB utilities"
src="x/xcb-util/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The xcb-util module provides a number of libraries which sit on top of
libxcb, the core X protocol library, and some of the extension
libraries. These experimental libraries provide convenience functions
and interfaces which make the raw X protocol more usable. Some of the
libraries also provide client-side code which is not strictly part of
the X protocol but which have traditionally been provided by Xlib.
EOF
}

buildPhase()
{
    ./configure $XORG_CONFIG
    make $globalBuildOptions
}

installPhase()
{
    make install
}
