#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xpyb
version=1.3
group=Libraries/X
license=PD
description="Xlib/XCB Python bindings"
src="x/xpyb/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
xpyb provides a Python binding to the X Window System protocol via libxcb.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
