#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/bash

group=lfs-stage1

buildPhase()
{
    ./configure --prefix=/tools --without-bash-malloc \
        ac_cv_func_working_mktime=yes
    make $globalBuildOptions
}

installPhase()
{
    make install
    ln -vs bash /tools/bin/sh
}
