#!/bin/bash -e

source $cbtBaseDir/settings/lfs-stage1-settings

name=create-tools-directory
group=lfs-stage1
description="Creates tools directory and symlink"

execute()
{
    mkdir $LFS/tools
    chown lfs $LFS/tools
    ln -s $LFS/tools /

    mkdir -p $LFS/tmp
    chmod 1777 $LFS/tmp
}
