#!/bin/bash -e

source $cbtBaseDir/settings/lfs-stage1-settings

name=create-bash-symlink
group=lfs-stage1
description="Creates /bin/bash symlink"

execute()
{
    mkdir -p $LFS/bin
    ln -sf /tools/bin/bash $LFS/bin
}
