#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/e2fsprogs

group=lfs-stage1

buildPhase()
{
    mkdir -v build
    cd build

    ../configure --prefix=/tools
    make $globalBuildOptions
}

installPhase()
{
    cd build

    make install-libs
    chmod -v u+w /tools/lib/{libblkid,libcom_err,libe2p,libext2fs,libss,libuuid}.a
}
