#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/gawk

group=lfs-stage1

buildPhase()
{
    ./configure --prefix=/tools ac_cv_func_working_mktime=yes
    make $globalBuildOptions
}

installPhase()
{
    make install
}
