#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/gzip

group=lfs-stage1

buildPhase()
{
    # The version of the function "futimens" used by Gzip is incompatible with the version that current Glibc provides, so we'll rename the function:
    for file in gzip.c lib/utimens.{c,h}
    do
        cp -v $file{,.orig}
        sed 's/futimens/gl_&/' $file.orig > $file
    done

    ./configure --prefix=/tools
    make $globalBuildOptions
}

installPhase()
{
    make install
}
