#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/ncurses

group=lfs-stage1

buildPhase()
{
    ./configure --prefix=/tools --with-shared \
       --without-debug --without-ada --enable-overwrite
    make $globalBuildOptions
}

installPhase()
{
    make install
}
