#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/perl

group=lfs-stage1

buildPhase()
{
    sh Configure -des -Dprefix=/tools \
                      -Dstatic_ext='Data/Dumper Fcntl IO POSIX'
    make perl utilities ext/Errno/pm_to_blib
}

installPhase()
{
    cp -v perl pod/pod2man /tools/bin
    mkdir -pv /tools/lib/perl5/$version
    cp -Rv lib/* /tools/lib/perl5/$version
}
