#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/tar

group=lfs-stage1

buildPhase()
{
    ./configure --prefix=/tools
    make $globalBuildOptions
}

installPhase()
{
    make install
}
