#!/bin/bash -e

source $cbtFunctionsDir/deployStage1SourcePackage
source $cbtBaseDir/settings/lfs-stage1-settings
source $cbtBaseDir/meta/tcl

group=lfs-stage1

buildPhase()
{
    ./configure --prefix=/tools
    make $globalBuildOptions
}

installPhase()
{
    make install
    chmod -v u+w /tools/lib/libtcl8.5.so
    make install-private-headers
    ln -sv tclsh8.5 /tools/bin/tclsh
}
