#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xcursor-themes
version=1.0.1
group=Display/X11/data
license=MIT
description="xcursor-themes"
src="x/xorg/data/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The xcursor-themes package contains the redglass and whiteglass animated cursor
themes.
EOF
}

buildPhase()
{
    ./configure $XORG_CONFIG
    make $globalBuildOptions
}

installPhase()
{
    make install
}
