#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xkeyboard-config
version=2.0
group=Display/X11/data
license=MIT
description="xkeyboard-config"
src="x/xorg/data/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The xkeyboard-config package contains the keyboard configurations database for
the X Window System.
EOF
}

buildPhase()
{
    ./configure $XORG_CONFIG --with-xkb-rules-symlink=xorg
    make $globalBuildOptions
}

installPhase()
{
    make install

    install -dv -m755 $XORG_PREFIX/share/doc/$name-$version
    install -v -m644 docs/{README,HOWTO}* \
        $XORG_PREFIX/share/doc/$name-$version
}
