#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=mpg123
version=1.13.0
group=Tools/Misc
license=LGPLv2.1
description="mpg123 tools"
src="m/mpg123/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The mpg123 distribution contains a real time MPEG 1.0/2.0/2.5 audio player/
decoder for layers 1,2 and 3 (most commonly MPEG 1.0 layer 3 aka MP3).
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
