#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=a2ps
version=4.14
group=Tools/Graphics
license=GPLv3
description="Any to PostScript converter"
src="a/a2ps/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
GNU a2ps is an Any to PostScript filter. Of course it processes plain text
files, but also pretty prints quite a few popular languages.
EOF
}

buildPhase()
{
    autoconf
    sed -i "s/GPERF --version |/& head -n 1 |/" configure
    sed -i "s|/usr/local/share|/usr/share|" configure

    ./configure --prefix=/usr \
        --sysconfdir=/etc/a2ps --localstatedir=/var \
        --enable-shared
    make $globalBuildOptions
}

installPhase()
{
    make install
}

