#!/bin/bash -e

source $cbtFunctionsDir/deployXDGDesktopSourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=ImageMagick
version=6.5.8_10
pkgVersion=6.5.8-10
group=Tools/Graphics
license=MIT
description="ImageMagick utility"
src="i/ImageMagick/$name-$pkgVersion.tar.xz"

desktopTargetDir="/usr/share/applications"
desktopName="ImageMagick display"
genericName="Image viewer"
exec=display
comment="Image viewer"
categories="X11;Graphics;"
mimeType="image/gif;image/x-xpm;image/x-xbm;image/jpeg;image/x-bmp;image/png;image/x-ico;image/x-portable-bitmap;image/x-portable-pixmap;image/x-portable-greymap;image/tiff;image/jp2;"

showLongDescription()
{
    cat << "EOF"
ImageMagick is a free, open-source software suite, used for editing and
manipulating digital images. It can be used to create, edit, compose, or convert
bitmap images, and supports a wide range of file formats, including JPEG, PNG,
GIF, TIFF.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --with-modules
    make $globalBuildOptions
}

installPhase()
{
    make install
}
