#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=openssh
version=3.2.3p1
group=Network/Servers-Clients
license=GPLv2
description="OpenSSH"
src="o/openssh/$name-$version.tar.gz"

preConfigurePhase()
{
    mkdir /var/empty
    chown root:sys /var/empty
    groupadd -g 50 sshd
    useradd -u 50 -g sshd sshd
}

buildPhase()
{
    ./configure --prefix=/usr --sysconfdir=/etc/ssh \
        --libexecdir=/usr/sbin --with-md5-passwords \
        --disable-suid-ssh \
        --with-ipv4-default
    make
}

installPhase()
{
    make install
    install -m754 $cbtBaseDir/init.d/openssh /etc/rc.d/init.d
    install -d -m755 /usr/share/ul/ul-init
    install -m644 $cbtBaseDir/plugins/ul-init/openssh /usr/share/ul/ul-init
}
