#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=openldap
version=2.0.27
group=Network/Servers-Clients
license=BSD
description="OpenLDAP"
src="o/openldap/$name-$version.tgz"

showLongDescription()
{
    cat << "EOF"
openldap is an open source suite of tools implementing the
Lightweight Directory Access Protocol (LDAP).
EOF
}

buildPhase()
{
    CPPFLAGS='-I/opt/db-3.3/include' LIBS='-L/opt/db-3.3/lib' \
      LDFLAGS='-L/opt/db-3.3/lib' \
      ./configure --prefix=/usr --sysconfdir=/etc --disable-debug \
      --libexecdir=/usr/sbin --enable-ldbm
    make depend
    make
}

installPhase()
{
    make install
    install -m754 $cbtBaseDir/init.d/openldap1 /etc/rc.d/init.d
    install -m754 $cbtBaseDir/init.d/openldap2 /etc/rc.d/init.d
    install -d -m755 /usr/share/ul/ul-init
    install -m644 $cbtBaseDir/plugins/ul-init/openldap1 /usr/share/ul/ul-init
    install -m644 $cbtBaseDir/plugins/ul-init/openldap2 /usr/share/ul/ul-init
}
