#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libofa
version=0.9.3
group=Libraries/Sound
license=GPLv2
description="Open Fingerprint Architecture library"
src="l/libofa/$name-$version.tar.gz"
patches=("l/libofa/$name-$version-gcc-4.patch")
files=("l/libofa/$name-$version-gcc-4.3.patch")
defaultPatchLevel=0

showLongDescription()
{
    cat << "EOF"
LibOFA is an audio fingerprint library, created and provided by MusicIP.
EOF
}

buildPhase()
{
    cat $sourcesDir/${files[0]} | patch -p1

    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
