#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/slackware-8.0

name=valgrind
version=1.9.6
group=Tools/Development
license=GPLv2
description="Valgrind"
src="v/valgrind/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Valgrind is a programming tool for memory debugging, memory leak detection, and
profiling.
EOF
}

buildPhase()
{
    ./configure
    make
}

installPhase()
{
    make install
}
