#!/bin/bash -e

source $cbtFunctionsDir/deployXDGDesktopSourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xfig
version=3.2.5c
group=Desktops/X11
license=xfig
description="X Figure Drawing"
src="x/xfig/${name}.${version}.full.tar.gz"
patches=("x/xfig/$name-$version.skip.missing.html.manpage.diff.gz")

desktopTargetDir="/usr/share/applications"
desktopName="XFig"
genericName="Vector graphics editor"
exec=xfig
comment="Vector graphics editor"
categories="Graphics;"
mimeType="application/x-xfig"

showLongDescription()
{
    cat << "EOF"
Xfig is an interactive drawing tool which runs under X Window System Version 11
Release 4 (X11R4) or later.

In xfig, figures may be drawn using objects such as circles, boxes, lines,
spline curves, text, etc. Those objects can be created, deleted, moved or
modified. Attributes such as colors or line styles can be selected in various
ways. For text, 35 fonts are available. It is also possible to embed images in
formats such as JPEG, PDF, EPS, PNG, etc.
EOF
}

buildPhase()
{
    sed -i -e 's|XCOMM #define XAW3D|#define XAW3D|' \
      -e 's|XCOMM #define USEXPM|#define USEXPM|' \
      -e 's|XCOMM #define USEXPM_ICON|#define USEXPM_ICON|' \
      -e "s|XFIGDOCDIR = /usr/local/xfig/doc|XFIGDOCDIR = /usr/share/doc/$name-$version|" \
      -e 's|/usr/local|/usr|g' \
      Imakefile
    xmkmf -a
    make
}

installPhase()
{
    chown -R root:root *

    make install.all
    make install.man
}
