#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xfm
version=1.5.4
group=Desktops/X11
license=GPLv2
description="X File Manager"
src="x/xfm/${name}_${version}.orig.tar.gz"

showLongDescription()
{
    cat << "EOF"
xfm is a powerful file and applications manager program written using the X
toolkit. It contains virtually all of the features that you would expect in a
file manager -- move around your directory tree in multiple windows, and move,
copy or delete files with simple mouse operations.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --sysconfdir=/etc
    make $globalBuildOptions
}

installPhase()
{
    make install
}
