#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xpaint
version=2.8.19
group=Desktops/X11
license=GPLv3
description="X Paint"
src="x/xpaint/$name-$version.tar.bz2"
patches=("x/xpaint/$name-$version-ewmh-minor-fixes.patch" "x/xpaint/$name-$version-minor_fixes.patch" "x/xpaint/$name-$version-small-improvements.patch")

showLongDescription()
{
    cat << "EOF"
XPaint is a free and open-source raster graphics editor for Unix-like
operating systems. Its main purpose is to be a lightweight and easy-to-use
raster editor. It supports various image file formats, including GIF, PNG, JPEG,
TIFF, PPM, XBM and XPM.
EOF
}

buildPhase()
{
    # Fix redefinition error
    sed -i \
        -e '/#include <X11\/Intrinsic.h>/d' \
        -e 's|typedef char \*String|#include <X11/Intrinsic.h>|' \
        rw/readWritePNG.c

    xmkmf -a
    make xaw
}

installPhase()
{
    chown -R root:root *

    make install
    make install.man
}
