#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/slackware-8.0

name=SDL
version=1.2.5
group=Libraries/Multimedia
license=LGPLv2
description="Simple DirectMedia Layer"
src="s/SDL/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Simple DirectMedia Layer is a cross-platform development library designed to
provide low level access to audio, keyboard, mouse, joystick, and graphics
hardware via OpenGL.
EOF
}

buildPhase()
{
    ./configure
    make
}

installPhase()
{
    make install
}
