#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/slackware-8.0

name=xvidcore
version=0.9.2
group=Libraries/Multimedia
license=GPLv2
description="XviD core"
src="x/xvidcore/$name-$version.tar.bz2"
workDir=$name-$version/build/generic

showLongDescription()
{
    cat << "EOF"
Xvid (formerly XviD) is an MPEG-4 video codec, implementing MPEG-4 Simple
Profile, Advanced Simple Profile, and Advanced Video Coding standards. It is
written in C with assembler optimizations for quality and speed (including MMX,
SSE, and 3Dnow! code for i386 and AltiVec for PowerPC), and is especially
optimized towards offline, multi-pass compression for storage and archival
purposes.
EOF
}

buildPhase()
{
    ./configure --enable-divx4compat
    make
}

installPhase()
{
    make install
    cp ../../src/divx4.h /usr/include
}
