#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/slackware-8.0

name=alsa-oss
version=0.9.8
license=GPLv2
group=Hardware
description="ALSA OSS"
src="a/alsa-oss/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The alsa-oss package contains the ALSA OSS compatibility library. This is used
by programs which wish to use the ALSA OSS sound interface.
EOF
}

buildPhase()
{
    ./configure
    make
}

installPhase()
{
    make install
}
