#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/slackware-8.0

name=alsa-driver
version=0.9.8
group=Hardware
license=GPLv2
description="ALSA driver"
src="a/alsa-driver/$name-$version.tar.bz2"
kernelVersion="2.4.23"

showLongDescription()
{
    cat << "EOF"
The ALSA Driver package contains the ALSA sound drivers. These are the next
generation of sound drivers for Linux.
EOF
}

buildPhase()
{
    ./configure \
      --with-moddir=/lib/modules/$kernelVersion/kernel/drivers/sound \
      --with-kernel=/lib/modules/$kernelVersion/build \
      --with-sequencer=yes \
      --with-oss=yes \
      --with-isapnp=no \
      --with-cards=dummy,mpu401,sbawe,emu10k1
    make
}

installPhase()
{
    make install
    ./snddevices
}
