#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/slackware-8.0

name=awesfx
version=0.4.4
group=Hardware
license=GPLv2
description="Sound Blaster EMU8x/10x tools"
src="a/awesfx/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Thie package includes several utilities for AWE32 sound driver on
Linux and FreeBSD systems and for Emux WaveTable of ALSA sbawe and
emu10k1 drivers. You need to use these utilities to enable sounds on
these drivers properly.
EOF
}

buildPhase()
{
    make
}

installPhase()
{
    make install
}
