#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=lynx
version=2.8.6rel.5
group=Network/Clients
license=GPLv2
description="Lynx browser"
src="l/lynx/${name}${version}.tar.gz"

showLongDescription()
{
    cat << "EOF"
Lynx is a customizable text-based web browser for use on cursor-addressable
character cell terminals.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr \
        --sysconfdir=/etc/lynx \
        --datadir=/usr/share/doc/$name-$version \
        --with-zlib \
        --with-bzlib \
        --with-screen=ncursesw \
        --enable-locale-charset &&
    make $globalBuildOptions
}

installPhase()
{
    make install-full
    chgrp -v -R root /usr/share/doc/$name-$version/lynx_doc
}
