#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=ncftp
version=3.2.2
group=Network/Clients
license=AL
description="NCFTP client"
src="n/ncftp/$name-$version-src.tar.bz2"

showLongDescription()
{
    cat << "EOF"
ncftp is an FTP client program and is a popular alternative to the standard FTP
program, /usr/bin/ftp. NcFTP offers many ease-of-use and performance
enhancements over the stock ftp client
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --sysconfdir=/etc
    make $globalBuildOptions -C libncftp shared
    make $globalBuildOptions
}

installPhase()
{
    make -C libncftp soinstall
    make install
}
