#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=cyrus-sasl
version=2.1.23
group=Libraries/Security
license=BSD
description="Simple Authentication and Security Layer"
src="c/cyrus-sasl/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Cyrus SASL is an implementation of SASL that makes it easy for application
developers to integrate authentication mechanisms into their application in a
generic way.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --sysconfdir=/etc \
        --with-dbpath=/var/lib/sasl/sasldb2 \
        --with-saslauthd=/var/run/saslauthd
    make
}

installPhase()
{
    make install

    install -v -m755 -d /usr/share/doc/$name-$version
    install -v -m644 doc/{*.{html,txt,fig},ONEWS,TODO} \
        saslauthd/LDAP_SASLAUTHD /usr/share/doc/$name-$version
    install -v -m700 -d /var/lib/sasl /var/run/saslauthd

    install -m754 $cbtBaseDir/init.d/cyrus-sasl /etc/rc.d/init.d
    install -d -m755 /usr/share/ul/ul-init
    install -m644 $cbtBaseDir/plugins/ul-init/cyrus-sasl /usr/share/ul/ul-init
}
