#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnutls
version=2.8.6
group=Libraries/Security
license=GPLv3
description="GNU TLS library"
src="g/gnutls/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
GnuTLS implements the TLS/SSL (Transport Layer Security aka Secure Sockets
Layer) protocol. GnuTLS is a GNU project.
EOF
}

buildPhase()
{
    local extraArgs=

    if [ -f /usr/include/lzo/lzoconf.h ]
    then
        extraArgs="--with-lzo"
    fi

    ./configure --prefix=/usr $extraArgs
    make $globalBuildOptions
}

installPhase()
{
    make install
}
