#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gpgme
version=1.3.0
group=Libraries/Security
license=LGPLv2.1
description="GnuPG made easy"
src="g/gpgme/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
GnuPG Made Easy (GPGME) is a C language library that allows to add
support for cryptography to a program.  It is designed to make access
to public key crypto engines like GnuPG or GpgSM easier for
applications. GPGME provides a high-level crypto API for encryption,
decryption, signing, signature verification and key management.

GPGME uses GnuPG and GpgSM as its backends to support OpenPGP and the
Cryptographic Message Syntax (CMS).
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --with-gpg=/usr/bin/gpg2 \
        --libexecdir=/usr/lib/gpgme
    make $globalBuildOptions
}

installPhase()
{
    make install
}
