#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libgcrypt
version=1.4.6
group=Libraries/Security
license=LGPLv2.1
description="GnuPG crypt library"
src="l/libgcrypt/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Libgcrypt is a general purpose crypto library based on the code used in GnuPG.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
