#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=graphviz
version=1.7.7
group=Tools/Development
license=CPLv1.0
description="Graph visualization software"
src="g/graphviz/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Graphviz is open source graph visualization software. Graph visualization is a
way of representing structural information as diagrams of abstract graphs and
networks. It has important applications in networking, bioinformatics, software
engineering, database and web design, machine learning, and in visual interfaces
for other technical domains.

The Graphviz layout programs take descriptions of graphs in a simple text
language, and make diagrams in useful formats, such as images and SVG; PDF or
Postscript for inclusion in other documents; or display in an interactive graph
browser. Graphviz has many useful features for concrete diagrams, such as
options for colors, fonts, tabular node layouts, line styles, hyperlinks, and
custom shapes.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install
}
