#!/bin/bash -e

checkIfMounted()
{
    [ "$(cut -d ' ' -f 2 < /etc/mtab | grep -x "$1" 2> /dev/null)" != "" ]
}

source settings/lfs-stage1-settings

export CBT_GLOBAL_CONFIG="$LFS/etc/cbt/cbt"
export CBT_STATE_DIR="$LFS/var/state/cbt"
export CBT_LOG_DIR="$LFS/var/log/cbt"
export TMPDIR="$LFS/tmp"
mkdir -p "$TMPDIR"

echo "Executing stage 1"
cbt-run-seq sequences/lfs-stage1

# Mount kernel filesystems

checkIfMounted $LFS/dev || mount -v --bind /dev $LFS/dev

checkIfMounted $LFS/dev/pts || mount -vt devpts devpts $LFS/dev/pts
checkIfMounted $LFS/dev/shm || mount -vt tmpfs shm $LFS/dev/shm
checkIfMounted $LFS/proc || mount -vt proc proc $LFS/proc
checkIfMounted $LFS/sys || mount -vt sysfs sysfs $LFS/sys

# Enter chroot environment

cd "$LFS"
chroot "$LFS" /tools/bin/env -i \
    HOME=/root TERM="$TERM" PS1='\u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin \
    /tools/bin/bash --login -c ul-stage2 +h

# Unmount previously mounted filesystems

umount $LFS/sys
umount $LFS/proc
umount $LFS/dev/shm
umount $LFS/dev/pts

umount $LFS/dev
