#!/bin/bash -e

configureHostname()
{
    local hostName=$(dialog --backtitle "UL" \
      --title "Network configuration tool" \
      --inputbox "Enter hostname:" \
      8 40 "$(hostname)" \
      2>&1 1>&3)

    local fqdn=$(dialog --backtitle "UL" \
      --title "Network configuration tool" \
      --inputbox "Enter fully qualified domain name:" \
      8 40 "$(hostname -f)" \
      2>&1 1>&3)

    cp /etc/sysconfig/network /etc/sysconfig/network.bak
    grep -v "^HOSTNAME=" /etc/sysconfig/network.bak > /etc/sysconfig/network || true
    echo "HOSTNAME=$hostName" >> /etc/sysconfig/network
    rm /etc/sysconfig/network.bak

    ( grep -v "^127.0.0.2" /etc/hosts
      echo "127.0.0.2 $fqdn $hostName"
    ) > /etc/hosts.new
    mv /etc/hosts.new /etc/hosts
    /etc/rc.d/init.d/localnet restart
}

configureIPv4()
{
    # Ask values to user

    set +e
    local IF=$(dialog --backtitle "UL" \
            --title "Network configuration" \
            --inputbox "Give a network interface" 8 40 "eth0" 2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        return
    fi

    set +e
    local IP=$(dialog --backtitle "UL" \
            --title "Network configuration" \
            --inputbox "Give an IP address for the network interface" 8 40 "192.168.0.1" 2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        return
    fi

    set +e
    local PREFIX=$(dialog --backtitle "UL" \
            --title "Network configuration" \
            --inputbox "Enter the subnet mask prefix number" 8 40 "24" 2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        return
    fi

    set +e
    local GATEWAY=$(dialog --backtitle "UL" \
            --title "Network configuration" \
            --inputbox "Give your default gateway IP address (or leave empty to specify none)" 8 40 "" 2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        return
    fi

    set +e
    local BROADCAST=$(dialog --backtitle "UL" \
            --title "Network configuration" \
            --inputbox "Give your broadcast address" 8 40 "192.168.0.255" 2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        return
    fi

    # Configure interface

    mkdir -p /etc/sysconfig/network-devices

    rm -f /etc/sysconfig/network-devices/ifup-$IF
    rm -f /etc/sysconfig/network-devices/ifdown-$IF

    cat > /etc/sysconfig/network-devices/ifconfig.$IF <<EOF
ONBOOT=yes
SERVICE=ipv4-static
IP=$IP
PREFIX=$PREFIX
BROADCAST=$BROADCAST
EOF

    if [ "$GATEWAY" != "" ]
    then
        echo "GATEWAY=$GATEWAY" >> /etc/sysconfig/network-devices/ifconfig.$IF
    fi

    /etc/rc.d/init.d/network restart
}

configureDhcpcd()
{
    set +e
    local IF=$(dialog --backtitle "UL" \
            --title "Network configuration" \
            --inputbox "Give a network interface" 8 40 "eth0" 2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        return
    fi

    cat > /etc/sysconfig/network-devices/ifconfig.$IF <<EOF
ONBOOT=yes
SERVICE=dhcpcd
DHCP_START=
DHCP_STOP="-k"

# Set PRINTIP="yes" to have the script print
# the DHCP assigned IP address
PRINTIP="no"

# Set PRINTALL="yes" to print the DHCP assigned values for
# IP, SM, DG, and 1st NS. This requires PRINTIP="yes".
PRINTALL="no"
EOF

    /etc/rc.d/init.d/network restart
}

exec 3>&1

while true
do
    set +e
    selectedOption=$(dialog --backtitle "UL" \
        --title "Network configuration tool" \
        --menu "Select a configuration option" \
        20 50 12 \
        "hostname"    "Configure host name" \
        "ipv4"        "Configure static IPv4 interface" \
        "dhcpcd"      "Configure DHCP client interface" \
        2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        exit
    fi
    
    case "$selectedOption" in
        hostname)
            configureHostname
            ;;
        ipv4)
            configureIPv4
            ;;
        dhcpcd)
            configureDhcpcd
            ;;
    esac
done
