#!/bin/bash -e

exec 3>&1

while true
do
    set +e
    selectedOption=$(dialog --backtitle "UL setup" \
       --title "Configuration menu" \
       --menu "Select a system aspect to configure" 19 55 12 \
       "ul-console"  "Configure console" \
       "passwd"      "Configure root password" \
       "ul-fstab"    "Configure filesystems" \
       "ul-utc"      "Configure UTC" \
       "ul-timezone" "Configure timezone" \
       "ul-grub"     "Configure GRUB" \
       "ul-network"  "Configure network" \
       "ul-init"     "Configure boot services" \
       "ul-firewall" "Configure firewall" \
       "ul-alsa"     "Configure ALSA" \
       "ul-gpm"      "Configure GPM" \
       "ul-locale"   "Configure localisation" \
       "ul-xinit"    "Configure default window manager" \
       "ul-adduser"  "Add new user" \
       "xorgconfig"  "Configure X.Org server" \
       "ul-xdm"      "Select X display manager" \
       "ul-cfgdms"   "Configure display managers" \
       "ul-xdg-menu" "Enable XDG menu in window managers" \
        2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        exit
    fi

    $selectedOption
done
