#!/bin/bash -e

source $cbtBaseDir/settings/ul-packages-settings

name=jdk-config
group=Programming
description="Configuration settings for the JDK"

execute()
{
    echo "MANDATORY_MANPATH /opt/jdk/man" >> /etc/man_db.conf
}
