#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=mono
version=2.6.7
group=Programming
license=LGPLv2
description=".NET framework implementation"
src="m/mono/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Mono is an open source implementation of Microsoft's .NET Framework as part of
the .NET Foundation and based on the ECMA standards for C# and the Common
Language Runtime.
EOF
}

# '

buildPhase()
{
    ./configure --prefix=/usr \
        --sysconfdir=/etc \
        --with-moonlight
    make
}

installPhase()
{
    make install
}
