#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=ocaml
version=3.12.0
group=Programming
license=QPL/LGPLv2
description="OCaml compiler and interpreter"
src="o/ocaml/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Objective Caml is an implementation of the ML language, based on
the Caml Light dialect extended with a complete class-based object system
and a powerful module system in the style of Standard ML.

Objective Caml comprises two compilers. One generates bytecode
which is then interpreted by a C program. This compiler runs quickly,
generates compact code with moderate memory requirements, and is
portable to essentially any 32 or 64 bit Unix platform. Performance of
generated programs is quite good for a bytecoded implementation.
This compiler can be used either as a standalone, batch-oriented
compiler that produces standalone programs, or as an interactive,
toplevel-based system.

The other compiler generates high-performance native code for a number
of processors. Compilation takes longer and generates bigger code, but
the generated programs deliver excellent performance, while retaining
the moderate memory requirements of the bytecode compiler.
EOF
}

buildPhase()
{
    ./configure --prefix /usr
    make world
    make bootstrap
    make opt
    make opt.opt
}

installPhase()
{
    make install

    # Some OCaml projects need libstr. We can provide it with a symlink
    cd /usr/lib/ocaml
    ln -s libcamlstr.a libstr.a
}
