#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=tk
version=8.5.5
group=Programming
license=tcl
description="Tk graphical toolkit for Tcl"
src="t/tk/${name}${version}-src.tar.gz"
workDir="${name}${version}/unix"

showLongDescription()
{
    cat << "EOF"
Tk is a graphical user interface toolkit that takes developing desktop
applications to a higher level than conventional approaches. Tk is the standard
GUI not only for Tcl, but for many other dynamic languages, and can produce
rich, native applications that run unchanged across Windows, Mac OS X, Linux and
more.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr \
                --enable-threads \
                --mandir=/usr/share/man
    make $globalBuildOptions

    # The Tk package expects that its source tree is
    # preserved so that packages depending on it for their compilation
    # can utilize it. This command removes the references to the
    # build directory and replaces them with saner system-wide locations.

    sed -i \
        -e "s@^\(TK_SRC_DIR='\).*@\1/usr/include'@" \
        -e "/TK_B/s@='\(-L\)\?.*unix@='\1/usr/lib@" \
        -e "/SEARCH/s/=.*/=''/" \
        tkConfig.sh
}

installPhase()
{
    make install
    make install-private-headers
    ln -v -sf wish8.5 /usr/bin/wish
}
