#!/bin/bash -e

if [ -f /etc/sysconfig/mouse ]
then
    source /etc/sysconfig/mouse
fi

# Set protocol on help if it is not set

PROTOCOL="${PROTOCOL:-help}"

# Show dialogs

exec 3>&1

while true
do
    # Put GPM help in text file
    gpm -m /dev/null -t help > /tmp/status || true

    set +e
    dialog --backtitle "UL" \
            --title "Mouse configuration" \
            --textbox /tmp/status 20 79
    exitStatus=$?
    set -e

    rm -f /tmp/status

    if [ "$exitStatus" -ne 0 ]
    then
        exit
    fi

    set +e
    PROTOCOL=$(dialog --backtitle "UL" \
            --title "Mouse configuration" \
            --inputbox "Enter your mouse protocol type\n(help to show types)" 10 40 "$PROTOCOL" \
            2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        exit
    fi

    if [ "$PROTOCOL" != "help" ]
    then
        break
    fi
done

set +e
MDEVICE=$(dialog --backtitle "UL" \
        --title "Mouse configuration" \
        --menu "Pick your mouse device" 20 40 10 \
        "/dev/mouse" "Default mouse" \
        "/dev/psaux" "PS/2 Mouse" \
        "other"      "Other mouse device" \
        2>&1 1>&3)
exitStatus=$?
set -e

if [ "$exitStatus" -ne 0 ]
then
    exit
fi

if [ "$MDEVICE" = "other" ]
then
    set +e
    MDEVICE=$(dialog --backtitle "UL" \
            --title "Mouse configuration" \
            --inputbox "Enter your mouse device file" 8 40 "/dev/mouse" \
            2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        exit
    fi
fi

cat > /etc/sysconfig/mouse <<EOF
PROTOCOL=$PROTOCOL
MDEVICE=$MDEVICE
EOF
