#!/bin/bash -e

queryKeymaps()
{
    cd /usr/share/kbd/keymaps/i386

    find . -type f | grep -v './include/' | while read file
    do
        echo "$file"
        echo "-"
    done
}

exec 3>&1

set +e

selectedLayout=$(dialog --backtitle "UL" \
  --title "Keyboard layout configuration" \
  --menu "Select keyboard layout" \
  20 70 12 \
  "(none)" "Use in-kernel keyboard layout" \
  $(queryKeymaps) \
  2>&1 1>&3)
exitStatus=$?
set -e

if [ $exitStatus -eq 0 ]
then
    if [ "$selectedLayout" = "(none)" ]
    then
        rm -f /usr/share/kbd/keymaps/defkeymap.map.gz
    else
        cd /usr/share/kbd/keymaps
        ln -sf "$selectedLayout" defkeymap.map.gz
    fi

    /etc/rc.d/init.d/loadkeys
else
    exit $exitStatus
fi
