#!/bin/bash -e

configureHostname()
{
    local hostName=$(dialog --backtitle "UL" \
      --title "Network configuration tool" \
      --inputbox "Enter hostname:" \
      8 40 "$(hostname)" \
      2>&1 1>&3)

    local fqdn=$(dialog --backtitle "UL" \
      --title "Network configuration tool" \
      --inputbox "Enter fully qualified domain name:" \
      8 40 "$(hostname -f)" \
      2>&1 1>&3)

    cp /etc/sysconfig/network /etc/sysconfig/network.bak
    grep -v "^HOSTNAME=" /etc/sysconfig/network.bak > /etc/sysconfig/network || true
    echo "HOSTNAME=$hostName" >> /etc/sysconfig/network
    rm /etc/sysconfig/network.bak

    ( grep -v "^127.0.0.2" /etc/hosts
      echo "127.0.0.2 $fqdn $hostName"
    ) > /etc/hosts.new
    mv /etc/hosts.new /etc/hosts
    /etc/rc.d/init.d/localnet restart
}

configureIPv4()
{
    # Ask values to user

    set +e
    local IF=$(dialog --backtitle "UL" \
            --title "Network configuration" \
            --inputbox "Give a network interface" 8 40 "eth0" 2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        return
    fi

    set +e
    local IP=$(dialog --backtitle "UL" \
            --title "Network configuration" \
            --inputbox "Give an IP address for the network interface" 8 40 "192.168.0.1" 2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        return
    fi

    set +e
    local NETMASK=$(dialog --backtitle "UL" \
            --title "Network configuration" \
            --inputbox "Enter the subnet mask" 8 40 "255.255.255.0" 2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        return
    fi

    set +e
    local BROADCAST=$(dialog --backtitle "UL" \
            --title "Network configuration" \
            --inputbox "Give your broadcast address" 8 40 "192.168.0.255" 2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        return
    fi

    # Configure interface

    mkdir -p /etc/sysconfig/network-devices

    rm -f /etc/sysconfig/network-devices/ifup-$IF
    rm -f /etc/sysconfig/network-devices/ifdown-$IF

    cat > /etc/sysconfig/network-devices/ifconfig.$IF <<EOF
ONBOOT=yes
IP=$IP
NETMASK=$NETMASK
BROADCAST=$BROADCAST
EOF

    /etc/rc.d/init.d/network restart
}

configureDefaultGateway()
{
    # Ask values to user

    set +e
    local GATEWAY=$(dialog --backtitle "UL" \
            --title "Network configuration" \
            --inputbox "Give an IP address for the default gateway\n(or leave empty to remove settings)" 10 40 "192.168.0.1" 2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        return
    fi

    if [ "$GATEWAY" = "" ]
    then
        cp /etc/sysconfig/network /etc/sysconfig/network.bak
        grep -v "^GATEWAY=" /etc/sysconfig/network.bak | grep -v "^GATEWAY_IF=" > /etc/sysconfig/network
        rm /etc/sysconfig/network.bak
        return
    fi

    set +e
    local GATEWAY_IF=$(dialog --backtitle "UL" \
            --title "Network configuration" \
            --inputbox "Give a default gateway network interface" 8 40 "eth0" 2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        return
    fi

    # Update configuration

    cp /etc/sysconfig/network /etc/sysconfig/network.bak
    grep -v "^GATEWAY=" /etc/sysconfig/network.bak | grep -v "^GATEWAY_IF_" > /etc/sysconfig/network
    rm /etc/sysconfig/network.bak

    cat >> /etc/sysconfig/network <<EOF
GATEWAY=$GATEWAY
GATEWAY_IF=$GATEWAY_IF
EOF

    /etc/rc.d/init.d/network restart
}

configureDhcpcd()
{
    set +e
    local IF=$(dialog --backtitle "UL" \
            --title "Network configuration" \
            --inputbox "Give a network interface" 8 40 "eth0" 2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        return
    fi

    cat > /etc/sysconfig/network-devices/ifconfig.$IF <<EOF
ONBOOT=yes
EOF

    cat > /etc/sysconfig/network-devices/ifup-$IF <<EOF
#!/bin/sh
# Begin /etc/sysconfig/network-devices/ifup-$IF

source /etc/sysconfig/rc
source \$rc_functions

echo "Bringing up the $IF interface via DHCP..."
/sbin/dhcpcd $IF
evaluate_retval
# End /etc/sysconfig/network-devices/ifup-$IF
EOF
    chmod 755 /etc/sysconfig/network-devices/ifup-$IF

    cat > /etc/sysconfig/network-devices/ifdown-$IF <<EOF
#!/bin/sh
# Begin /etc/sysconfig/network-devices/ifdown-$IF

source /etc/sysconfig/rc
source \$rc_functions

echo "Bringing down the $IF interface..."
/sbin/dhcpcd -k $IF
evaluate_retval

# Never allow this script to fail completely because it disrupts shutdown
true

# End /etc/sysconfig/network-devices/ifdown-$IF
EOF

    chmod 755 /etc/sysconfig/network-devices/ifdown-$IF

    /etc/rc.d/init.d/network restart
}

exec 3>&1

while true
do
    set +e
    selectedOption=$(dialog --backtitle "UL" \
        --title "Network configuration tool" \
        --menu "Select a configuration option" \
        20 50 12 \
        "hostname"    "Configure host name" \
        "ipv4"        "Configure static IPv4 interface" \
        "gateway"     "Configure the default gateway" \
        "dhcpcd"      "Configure DHCP client interface" \
        2>&1 1>&3)
    exitStatus=$?
    set -e

    if [ "$exitStatus" -ne 0 ]
    then
        exit
    fi
    
    case "$selectedOption" in
        hostname)
            configureHostname
            ;;
        ipv4)
            configureIPv4
            ;;
        gateway)
            configureDefaultGateway
            ;;
        dhcpcd)
            configureDhcpcd
            ;;
    esac
done
