#!/bin/bash -e

queryWindowManagers()
{
    windowManagers=()

    for wm in /usr/share/ul/ul-xinit/*
    do
        source "$wm"
	local wmName="$(basename "$wm")"
	local targetLink="$(readlink /etc/X11/xinit/xinitrc)"
	local selected
	
	if [ "xinitrc.$wmName" = "$targetLink" ]
	then
	    selected=on
	else
	    selected=off
	fi
	
        windowManagers=("${windowManagers[@]}" "$wmName" "$description" "$selected")
    done
}

exec 3>&1

queryWindowManagers

set +e
DESKTOPENV=$(dialog --backtitle "UL" \
       --title "xinit configuration" \
       --radiolist "Select personal desktop environment" 20 50 12 \
       "${windowManagers[@]}" \
       2>&1 1>&3)
exitStatus=$?
set -e

if [ $exitStatus -ne 0 ]
then
    exit 1
fi

ln -sfn xinitrc.$DESKTOPENV /etc/X11/xinit/xinitrc
