#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gst-python
version=0.10.20
group=Libraries/Multimedia
license=LGPLv2.1
description="GStreamer Python bindings"
src="g/gst-python/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
GStreamer python overrides for the gobject-introspection-based pygst bindings.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
