#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gst-plugins-base
version=0.10.31
group=Libraries/Multimedia
license=LGPLv2
description="GStreamer base plugins"
src="g/gst-plugins-base/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
A well-groomed and well-maintained collection of GStreamer plug-ins and
elements, spanning the range of possible types of elements one would want
to write for GStreamer.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
