#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gst-plugins-good
version=0.10.26
group=Libraries/Multimedia
license=LGPLv2
description="GStreamer good plugins"
src="g/gst-plugins-good/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
A collection of plug-ins you'd want to have right next to you on the
battlefield.  Shooting sharp and making no mistakes, these plug-ins have it
all: good looks, good code, and good licensing.  Documented and dressed up
in tests.  If you're looking for a role model to base your own plug-in on,
here it is.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr \
        --with-gconf-schema-file-dir=/etc/opt/gnome-$gnome2Version/gconf/schemas
    make $globalBuildOptions
}

installPhase()
{
    make install
}
