#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xine-lib
version=1.1.18.1
group=Libraries/Multimedia
license=LGPLv2
description="Xine libraries"
src="x/xine-lib/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
xine-lib is a free multimedia engine that is used by a variety of media players
such as Totem and noatun.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --enable-static
    make $globalBuildOptions
}

installPhase()
{
    make install
}
