#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=atkmm
version=2.21.2
group=Libraries/gnome2
license=LGPLv2.1
description="ATK C++ bindings"
src="a/atkmm/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
atkmm is the C++ binding for the ATK library.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
