#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=cairomm
version=1.8.6
group=Libraries/gnome2
license=LGPLv2
description="Cairo C++ bindings"
src="c/cairomm/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
This library provides a C++ interface to cairo.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
