#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=dbus-glib
version=0.92
group=Libraries/gnome2
license=GPLv2/AFLv2.1
description="D-Bus bindings for GLib"
src="d/dbus-glib/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
D-BUS is a simple IPC library based on messages. This library makes it possible
to use D-Bus functionality from GLib applications.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc \
        --libexecdir=/opt/gnome-$gnome2Version/lib/dbus-glib
    make $globalBuildOptions
}

installPhase()
{
    make install
}
