#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=eggdbus
version=0.6
group=Libraries/gnome2
license=LGPLv2
description="Alternative D-Bus bindings for GLib"
src="e/eggdbus/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Alternative GLib bindings library for D-Bus
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --libexecdir=/opt/gnome-$gnome2Version/lib/eggdbus \
        --localstatedir=/var/lib
    make $globalBuildOptions
}

installPhase()
{
    make install
}
