#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gdk-pixbuf
version=2.22.1
group=Libraries/gnome2
license=LGPLv2
description="GDK pixel buffer library"
src="g/gdk-pixbuf/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The Gdk Pixbuf package is a toolkit for image loading and pixel buffer
manipulation. It is used by GTK+ 2 and GTK+ 3 to load and manipulate images.
In the past it was distributed as part of GTK+ 2 but it was split off into a
separate package in preparation for the change to GTK+ 3. 
EOF
}

buildPhase()
{
    local extraArgs=

    if jasper --version
    then
        extraArgs="$extraArgs --with-jasper"
    fi

    ./configure --prefix=/opt/gnome-$gnome2Version $extraArgs
    make $globalBuildOptions
}

installPhase()
{
    make install
}
