#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-sharp
version=2.24.2
group=Libraries/gnome2
license=LGPLv2.1
description=".NET bindings for GNOME libraries"
src="g/gnome-sharp/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Gnome# is a .NET language binding for assorted GNOME libraries.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
