#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-vfs-monikers
version=2.15.3
group=Libraries/gnome2
license=LGPLv2
description="GNOME Virtual Filesystem Monikers"
src="g/gnome-vfs-monikers/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The GNOME VFS Monikers package contains Bonobo monikers that were pulled out of
the GNOME VFS package during the Bonobo to D-Bus conversion. This package is
required so that the GNOME VFS API/ABI remains stable.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
