#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-vfs
version=2.24.4
group=Libraries/gnome2
license=LGPLv2
description="GNOME Virtual Filesystem"
src="g/gnome-vfs/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
This is the GNOME Virtual File System.

GNOME VFS is currently used as one of the foundations of the Nautilus
file manager.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version \
        --libexecdir=/opt/gnome-$gnome2Version/lib/gnome-vfs-2.0
    make $globalBuildOptions
}

installPhase()
{
    make install
}
