#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gtk+2
version=2.22.1
group=Libraries/gnome2
license=LGPLv2
description="GTK+ toolkit"
src="g/gtk+/gtk+-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
GTK+ is a multi-platform toolkit for creating graphical user interfaces.
Offering a complete set of widgets, GTK+ is suitable for projects ranging from
small one-off projects to complete application suites.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --sysconfdir=/etc/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
