#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gtkimageview
version=1.6.4
group=Libraries/gnome2
license=LGPLv2.1
description="GTK image view library"
src="g/gtkimageview/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
GtkImageView is a widget that provides a zoomable and panable view of a
GdkPixbuf. It is intended to be usable in most types of image viewing
applications.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
