#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libcroco
version=0.6.2
group=Libraries/gnome2
license=LGPLv2
description="CSS 2 parsing library"
src="l/libcroco/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Libcroco is a standalone css2 parsing and manipulation library.
The parser provides a low level event driven SAC like api
and a css object model like api.
Libcroco provides a CSS2 selection engine and an experimental
xml/css rendering engine.

This library is being written to bring the css support
to the mlview xml editor project but it can be used
for other applications as well.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
