#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libgnome-keyring
version=2.32.0
group=Libraries/gnome2
license=LGPLv2
description="GNOME Keyring Library"
src="l/libgnome-keyring/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
gnome-keyring is a program that keep password and other secrets for
users. The library libgnome-keyring is used by applications to integrate
with the gnome keyring system.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
