#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=ndesk-dbus
version=0.6.1a
group=Libraries/gnome2
license=MIT
description="D-Bus for .NET"
src="n/ndesk-dbus/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
This is a C# implementation of D-Bus. It's often referred to as "managed
D-Bus" to avoid confusion with existing bindings (which wrap libdbus).
EOF
}

# "

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
