#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=vala
version=0.10.2
group=Libraries/gnome2
license=LGPLv2.1
description="Vala programming language"
src="v/vala/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Vala is a new programming language that aims to bring modern programming
language features to GNOME developers without imposing any additional
runtime requirements and without using a different ABI compared to
applications and libraries written in C.

valac, the Vala compiler, is a self-hosting compiler that translates
Vala source code into C source and header files. It uses the GObject
type system to create classes and interfaces declared in the Vala source
code.

The syntax of Vala is similar to C#, modified to better fit the GObject
type system.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnome2Version \
        --enable-vapigen
    make $globalBuildOptions
}

installPhase()
{
    make install
}
