#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=iso-codes
version=3.15
group=Libraries/Shared
license=LGPLv2.1
description="Lists of various ISO standards"
src="i/iso-codes/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
This package provides lists of various ISO standards (e.g. country,
language, language scripts, and currency names) in one place, rather
than repeated in many programs throughout the system.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
