#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libmowgli
version=0.7.0
group=Libraries/Shared
license=BSD-3
description="Class library for C"
src="l/libmowgli/$name-$version.tbz2"

showLongDescription()
{
    cat << "EOF"
libmowgli is a class library containing performance and usability oriented
extensions to C.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
