#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=libvisual
version=0.4.0
group=Libraries/Shared
license=LGPLv2.1
description="Middle layer between applications using audio visualization"
src="l/libvisual/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Libvisual is a library that acts as a middle layer between applications that
want audio visualisation and audio visualisation plugins.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
