#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=lzo
version=2.03
group=Libraries/Shared
license=GPLv2
description="Fast portable lossless data compression"
src="l/lzo/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
LZO is a portable lossless data compression library written in ANSI C.
It offers pretty fast compression and very fast decompression.
Decompression requires no memory.

In addition there are slower compression levels achieving a quite
competitive compression ratio while still decompressing at
this very high speed.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --enable-shared
    make $globalBuildOptions
}

installPhase()
{
    make install
}
