#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=pcre
version=7.9
group=Libraries/Shared
license=zlib
description="Perl Compatible Regular Expressions library"
src="p/pcre/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The PCRE library is a set of functions that implement regular expression pattern
matching using the same syntax and semantics as Perl 5. PCRE has its own native
API, as well as a set of wrapper functions that correspond to the POSIX regular
expression API.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --docdir=/usr/share/doc/$name-$version \
        --enable-utf8 --enable-unicode-properties \
        --enable-pcregrep-libz --enable-pcregrep-libbz2
    make $globalBuildOptions
}

installPhase()
{
    make install
}
