#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=audacious
version=2.4.5
group=Applications
license=GPLv3
description="Audacious audio player"
src="a/audacious/$name-$version.tgz"

showLongDescription()
{
    cat << "EOF"
Audacious is an open source audio player. A descendant of XMMS, Audacious plays
your music how you want it, without stealing away your computer's resources from
other tasks. Drag and drop folders and individual song files, search for artists
and albums in your entire music library, or create and edit your own custom
playlists. Listen to CD's or stream music from the Internet. Tweak the sound
with the graphical equalizer or change the dynamic range with audio effects.
EOF
}

buildPhase()
{
    local extraArgs=

    if [ "$audaciousAllowSSE2" = "" ] || [ "$audaciousAllowSSE2" = "0" ]
    then
        extraArgs="--disable-sse2"
    fi

    ./configure --prefix=/usr $extraArgs
    make $globalBuildOptions
}

installPhase()
{
    make install
}
