#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=kmplayer
version=0.10.0c
group=Applications
license=GPLv2
description="KDE front-end for KMPlayer"
src="k/kmplayer/$name-$version.tar.bz2"
workDir="$name-$version"

showLongDescription()
{
    cat << "EOF"
KMPlayer, a simple frontend for MPlayer/FFMpeg/Xine. It can play DVD/VCD movies,
from file or url and from a video device. If setup right, KMPlayer can embed
inside konqueror. Which means if you click on a movie file, the movie is played
inside konqueror.

It can also embed inside khtml, enabling movie playback inside a html page.

Movie recording using mencoder (part of the mplayer package).
No video during recording, but you can always open a new window and play it
there. Broadcasting, http streaming, by using ffserver/ffmpeg.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/kde-$kdeVersion
    make
}

installPhase()
{
    make install
}
