#!/bin/bash -e

source $cbtFunctionsDir/deployXDGDesktopSourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=thunderbird
version=3.1.20
group=Applications
license=MPLv1/LGPLv2.1/GPLv2
description="Mozilla Thunderbird"
src="t/thunderbird/$name-$version.source.tar.bz2"
workDir="comm-1.9.2"

desktopTargetDir="/usr/share/applications"
desktopName="Mozilla Thunderbird"
genericName="Mail client and calendar"
exec="thunderbird"
icon=/opt/$name-$version/lib/$name-$version/chrome/icons/default/default48.png
comment="Mail client and calendar"
categories="Application;Network;"

showLongDescription()
{
    cat << "EOF"
Mozilla Thunderbird is a free and open-source personal information manager
primarily used as an e-mail client with a calendar and contactbook, as well as
an RSS feed reader, chat client and news client.
EOF
}

buildPhase()
{
    cat > mozconfig <<EOF
# This file contains the options used in the Thunderbird build. You may
# need to specify additional options for your specific build needs.
# Use the information provided by running './configure --help' to
# help you determine if you need to add any additional options.
# Some additional options can be added by uncommenting the examples
# in this file or adding options by inserting a line containing
# 'ac_add_options --some-option-you-need'.  Be aware that some accepted
# options, such as '--with-system-bz2', do not affect the build.

# Specify that Thunderbird should be built.
ac_add_options --enable-application=mail

# Use the default settings specified in the source tree. The
# --enable-application=mail is set in this file. This file does not exist in
# this version of Thunderbird.
#. \$topsrcdir/mailnews/config/mozconfig

# Specify that the Lightning calendar extension should be built as per the
# Mozilla distributed Thunderbird.
ac_add_options --enable-calendar

# Create an object directory and specify to build the package in that
# directory. If desired, modify the location of the object directory
# to a directory inside the source tree by removing '../' from the
# line below.
mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/../thunderbird-build

# Specify the installation prefix. If you would prefer Thunderbird installed in a
# different prefix, modify the line below to fit your needs.
ac_add_options --prefix=/opt/$name-$version

# Apply a minimal level of optimization (-O).
ac_add_options --enable-optimize

# These options are used so that the Thunderbird binaries are linked to
# the system-installed copies of the specified libraries instead of
# the source tree code which may not be the most recent versions.
# With the exception of libsqlite3, the libraries are statically linked.

# (Options to use system installed libraries)
# Using the shipped version of libsqlite3 has been reported to cause
# problems with other applications which were using sqlite3.
# Only comment this line if you know exactly what you are doing!
ac_add_options --enable-system-sqlite

# Comment this only if you want to use whatever patched version of cairo
# is in the shipped mozilla tree, together with the system headers.
ac_add_options --enable-system-cairo

# Comment this if you have not installed lcms.
ac_add_options --enable-system-lcms

# Uncomment this if you have installed Hunspell
#ac_add_options --enable-system-hunspell

# Uncomment this if you have installed startup-notification
ac_add_options --enable-startup-notification

# Comment this if you did not build libjpeg before GTK+-2.
ac_add_options --with-system-jpeg

# These two options enable support for building Thunderbird with
# system-installed versions of the Network Security Services (NSS)
# and Netscape Portable Runtime (NSPR) libraries. Comment them if
# you wish to use the included copies (not recommended).
ac_add_options --with-system-nspr
ac_add_options --with-system-nss

# Comment this if you have not built png with the apng patch.
ac_add_options --with-system-png

# The pthreads option is only used when building nspr
# Uncomment this if you build the included nspr.
#ac_add_options --with-pthreads

# Zlib is included in LFS. Do not comment this line.
ac_add_options --with-system-zlib

# (Options to disable parts of the package)
# This option is used to disable the a11y support in the Thunderbird
# binaries. Comment out this option if you require a11y support.
ac_add_options --disable-accessibility

# Uncomment this if you did not build cURL.
#ac_add_options --disable-crashreporter

# Comment this if you have built DBus-Glib.
#ac_add_options --disable-dbus

# Comment this if you have Gnome-VFS and libgnomeui, and wish to
# integrate Thunderbird into your Gnome desktop.
#ac_add_options --disable-gnomevfs

# Comment this if you have wireless-tools installed and wish to use the new
# Necko WiFi scanning.
ac_add_options --disable-necko-wifi

# Comment this if you have installed libnotify.
ac_add_options --disable-libnotify

# This option is added so that the Mozilla Installer program is not
# built or installed. The program is not required for a BLFS
# installation of Thunderbird.
ac_add_options --disable-installer

# If you enable javaxpcom, you must have a java compiler installed.
ac_add_options --disable-javaxpcom

# Enable the build of static internal libs (currently required).
ac_add_options --enable-static

# This option is added so that test libraries and programs are not
# built. These would only be required for debugging purposes.
ac_add_options --disable-tests

# Disable the updater, which is not appropriate if you build from source.
ac_add_options --disable-updater

# (options to add extra parts of the package)
# This option causes the installed Thunderbird binaries to have the official
# Thunderbird name embedded in them. Due to license restrictions, you
# may not distribute binaries created using this option.  It also
# means you get a popup EULA when you first run Thunderbird.
ac_add_options --enable-official-branding

# This option is used so that the debugging symbols are removed from
# the installed binaries during the installation process. Comment out
# this option if you may have a need to retain the debugging symbols
# in the installed binaries (the resulting binaries will be about 7MB
# bigger).
ac_add_options --enable-strip

# Uncomment this option if you desire support for dual-monitor
# display using the X-Window Xinerama libraries.
ac_add_options --enable-xinerama

# Enable strong cryptography (This is explicitly required if you plan to use
# the Enigmail extension for Thunderbird).
ac_add_options --enable-crypto

# Point to the Xulrunner libraries - comment these for a standalone client
# DO NOT UNCOMMENT THESE - System XULRunner is broken until Thunderbird
# development catches up with XULRunner-1.9.2.
#ac_add_options --with-system-libxul
#ac_add_options --with-default-mozilla-five-home=/opt/xulrunner-$xulRunnerVersion/lib/xulrunner-devel-$xulRunnerVersion
EOF

    make -f client.mk build
}

installPhase()
{
    make -f client.mk install

    ln -sfn /opt/$name-$version /opt/$name

    install -m755 $cbtBaseDir/profile.d/32thunderbird.sh /etc/profile.d
    if which csh
    then
        install -m755 $cbtBaseDir/profile.d/32thunderbird.csh /etc/profile.d
    fi
}
