#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=attr
version=2.4.44
group=Tools/Filesystems
license=LGPLv2.1/GPLv2
description="Extended Attributes library and tools"
src="a/attr/$name-$version.src.tar.gz"

showLongDescription()
{
    cat << "EOF"
The attr package contains utilities to administer the extended attributes on
filesystem objects.
EOF
}

buildPhase()
{
    sed -i -e 's|/@pkg_name@|&-@pkg_version@|' \
           -e 's|@prefix|$(DESTDIR)&|' \
           -e 's|@libexec|$(DESTDIR)&|' \
        include/builddefs.in

    INSTALL_USER=root INSTALL_GROUP=root \
        ./configure --prefix=/usr --libexecdir=/usr/lib
    make $globalBuildOptions
}

installPhase()
{
    make install install-dev install-lib
    chmod -v 755 /usr/lib/libattr.{la,so.1.1.0}
}
