#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=dosfstools
version=3.0.4
group=Tools/Filesystems
license=GPLv2
description="FAT filesystem tools"
src="d/dosfstools/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The dosfstools package contains various utilities for use with the FAT family of
file systems.
EOF
}

buildPhase()
{
    make PREFIX=/usr
}

installPhase()
{
    make PREFIX=/usr install
}
