#!/bin/bash -e

export CFLAGS="-O2 -march=pentium3"
export CXXFLAGS="$CFLAGS"

set +h
umask 022
LFS=/mnt/lfs
LC_ALL=POSIX
LFS_TGT=$(uname -m)-lfs-linux-gnu
PATH=/tools/bin:$PATH
export LFS LC_ALL LFS_TGT PATH

sourcesDir=$LFS/mnt/source
CBT_UNPACK_PLUGINS=$LFS/usr/share/cbt/unpack-plugins
CBT_UNCOMPRESS_PLUGINS=$LFS/usr/share/cbt/uncompress-plugins
