#!/bin/bash -e

xorgVersion=7.3
XORG_PREFIX="/usr/X11R$xorgVersion"
XORG_CONFIG="--prefix=$XORG_PREFIX --sysconfdir=/etc --mandir=$XORG_PREFIX/share/man --localstatedir=/var"

gnomeVersion=1.4.1
gnome2Version=2.32.1
kdeVersion=3.5.10
xulRunnerVersion=1.9.2.19
firefoxVersion=3.6.28
thunderbirdVersion=3.1.20

sourcesDir=/mnt/source

set +h
umask 022
