#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=kde-i18n-nl
version=3.5.10
group=Desktops/kde-i18n
license=GPLv2
description="KDE Dutch internationalization"
src="k/kde-i18n/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Dutch localization settings for KDE.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/kde-$kdeVersion --sysconfdir=/etc/opt/kde-$kdeVersion \
        --disable-debug --disable-dependency-tracking
    make $globalBuildOptions
}

installPhase()
{
    make install
}
