#!/bin/bash -e

name=bzip2
version=1.0.2
description="bzip2"
license=BSD-3
src="b/bzip2/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
bzip2 is a freely available, patent free, high-quality data compressor.
It typically compresses files to within 10% to 15% of the best available
techniques (the PPM family of statistical compressors), whilst being around
twice as fast at compression and six times faster at decompression.
EOF
}
