#!/bin/bash -e

name=diffutils
version=2.8
description="GNU Diffutils"
license=GPLv2
src="d/diffutils/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
GNU Diffutils is a package of several programs related to finding differences
between files.
EOF
}
