#!/bin/bash -e

name=sed
version=3.02
description="GNU Sed"
license=GPLv2
src="s/sed/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
sed (stream editor) is a non-interactive command-line text editor. 

sed is commonly used to filter text, i.e., it takes text input, performs some
operation (or set of operations) on it, and outputs the modified text. sed is
typically used for extracting part of a file using pattern matching or
substituting multiple occurrences of a string within a file.
EOF
}
