#!/bin/bash -e

name=tar
version=1.13
description="GNU Tar"
license=GPLv2
src="t/tar/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
GNU Tar provides the ability to create tar archives, as well as various other
kinds of manipulation. For example, you can use Tar on previously created
archives to extract files, to store additional files, or to update or list files
which were already stored. 
EOF
}
