#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=libticalcs
version=4.4.3
group=Libraries/App
license=LGPLv2.1
description="TI calculators library"
src="l/libticalcs/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
This library is part of the TILP framework and provides support for a variety of
Texas Instruments (TI) calculator models.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install
}
