#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=fribidi
version=0.10.4
group=Libraries/Graphics
license=LGPLv2.1
description="Unicode Bidirectional algorithm implementation"
src="f/fribidi/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
GNU FriBidi is the Free Implementation of the Unicode Bidirectional Algorithm.

In order to have proper Arabic and Hebrew support, the BiDi algorithm should
have been implemented.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
