#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gd
version=2.0.35
group=Libraries/Graphics
license=gd
description="GD library"
src="g/gd/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
GD is an open source code library for the dynamic creation of images by
programmers. GD is written in C, and "wrappers" are available for Perl, PHP and
other languages. GD creates PNG, JPEG and GIF images, among other formats. GD is
commonly used to generate charts, graphics, thumbnails, and most anything else,
on the fly. While not restricted to use on the web, the most common applications
of GD involve website development.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
