#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=lcms
version=1.17
group=Libraries/Graphics
license=MIT
description="Little Color Monitoring System"
src="l/lcms/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Little CMS or LCMS is an open-source color management system, released as a
software library for use in other programs which will allow the use of
International Color Consortium (ICC) profiles.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
