#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=libEMF
version=1.0.4
group=Libraries/Image
license=LGPLv2.1
description="EMF generator library"
src="l/libEMF/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
libEMF is a library for generating Enhanced Metafiles on systems which
don't natively support the ECMA-234 Graphics Device Interface
(GDI). The library is intended to be used as a driver for other
graphics programs such as Grace or gnuplot. Therefore, it implements a
very limited subset of the GDI.
EOF
}

# '

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
