#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=libwpg
version=0.1.3
group=Libraries/Image
license=LGPLv2
description="WordPerfect Graphics library"
src="l/libwpg/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Libwpg project is a collection of library and tools to work with graphics in WPG
(WordPerfect Graphics) format. WPG is the format used among others in Corel
sofware, such as WordPerfect(tm) and Presentations(tm).
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
