#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=libwebp
version=0.1.3
group=Libraries/Image
license=BSD-3
description="WebP library"
src="l/libwebp/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
WebP codec: library to encode and decode images in WebP format. This package
contains the library that can be used in other programs to add WebP support,
as well as the command line tools 'cwebp' and 'dwebp'.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
