#!/bin/sh
# Begin $rc_base/init.d/apache

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy: bdubbs $
#$Date: 2005-08-01 14:29:19 -0500 (Mon, 01 Aug 2005) $

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
   start)
      boot_mesg "Starting the Avahi Daemon"
      /usr/sbin/avahi-daemon -D
      evaluate_retval

      boot_mesg "Starting the Avahi mDNS/DNS-SD Configuration Daemon"
      /usr/sbin/avahi-dnsconfd -D
      evaluate_retval
      ;;

   stop)
      boot_mesg "Stopping the Avahi mDNS/DNS-SD Configuration Daemon"
      /usr/sbin/avahi-dnsconfd -k
      evaluate_retval

      boot_mesg "Stopping the Avahi Daemon"
      /usr/sbin/avahi-daemon -k
      evaluate_retval
      ;;

   reload)
      boot_mesg "Reloading the Avahi mDNS/DNS-SD Configuration Daemon"
      /usr/sbin/avahi-dnsconfd -r
      evaluate_retval

      boot_mesg "Reloading the Avahi Daemon"
      /usr/sbin/avahi-daemon -r
      evaluate_retval
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   status)
      statusproc avahi-daemon
      statusproc avahi-dnsconfd
      ;;

    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

# End $rc_base/init.d/apache
