#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=qt
version=3.3.8b
group=Libraries/kde
license=GPLv2/QPL
description="Trolltech Qt library"
src="q/qt/$name-x11-free-$version.tar.gz"
buildAsRoot=true

showLongDescription()
{
    cat << "EOF"
qt is a cross-platform application development framework for creating graphical
user interfaces as well as cross-platform applications that run on various
software and hardware platforms with little or no change in the underlying
codebase while still being a native application with native capabilities and
speed.
EOF
}

buildPhase()
{
    export QTDIR=$PWD
    export LD_LIBRARY_PATH=$PWD/lib:$LD_LIBRARY_PATH
    export PATH=$PWD/bin:$PATH

    yes yes | ./configure -prefix /opt/$name-$version \
        -sysconfdir /etc/opt/$name-$version \
        -qt-gif \
        -system-zlib \
        -system-libpng \
        -system-libjpeg \
        -system-libmng \
        -plugin-imgfmt-png \
        -plugin-imgfmt-jpeg \
        -plugin-imgfmt-mng \
        -no-exceptions \
        -thread \
        -tablet
    make $globalBuildOptions
}

installPhase()
{
    make install

    ln -v -sfn $name-$version /opt/$name &&
    ln -v -s libqt-mt.so /opt/qt/lib/libqt.so &&
    cp -v -r doc/man examples /opt/qt/doc

    install -m755 $cbtBaseDir/profile.d/22qt.sh /etc/profile.d
    if which csh
    then
        install -m755 $cbtBaseDir/profile.d/22qt.csh /etc/profile.d
    fi
}
