#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=gb
version=0.0.17
group=Libraries/gnome
license=GPLv2
description="GNOME Basic"
src="g/gb/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
GNOME Basic is an embryonic attempt to provide Visual Basic like functionality
within the GNOME environment.
EOF
}

buildPhase()
{
    CPPFLAGS='-I/opt/gnome/include' \
      ./configure --prefix=/opt/gnome-$gnomeVersion --enable-shared
    make
}

installPhase()
{
    make install
}
