#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/extra-settings

name=soup
version=0.7.11
group=Libraries/gnome
license=LGPLv2.1
description="SOAP implementation in C"
src="s/soup/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Soup is a SOAP (Simple Object Access Protocol) implementation in C. 

It provides an queued asynchronous callback-based mechanism for sending and
servicing SOAP requests, and a WSDL (Web Service Definition Language) to C
compiler which generates client stubs and server skeletons for easily calling
and implementing SOAP methods.

It uses the Glib main loop and is designed to work well with GTK
applications.  This enables GNOME applications to access SOAP servers
on the network in a completely asynchronous fashion, very similar to the
Gtk+ programming model (a synchronous operation mode is also supported
for those who want it).

The WSDL compiler will help you make your applications interoperate
with services that expose their descriptions through WSDL.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnomeVersion --enable-shared
    make
}

installPhase()
{
    make install
}
