#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=a52dec
version=0.7.4
group=Libraries/Audio
license=GPLv2
description="ATSC A/52 decoder"
src="a/a52dec/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
liba52 is a free library for decoding ATSC A/52 streams. The A/52 standard is
used in a variety of applications, including digital television and DVD. It
is also known as AC-3.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
