#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=faac
version=1.28
group=Libraries/Audio
license=LGPLv2
description="Freeware Advanced Audio Codec"
src="f/faac/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
FAAC is an encoder for a lossy sound compression scheme specified in MPEG-2 Part
7 and MPEG-4 Part 3 standards and known as Advanced Audio Coding (AAC). This
encoder is useful for producing files that can be played back on iPod. Moreover,
iPod does not understand other sound compression schemes in video files.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
