#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=wavpack
version=4.60.1
group=Libraries/Audio
license=BSD-3
description="Wavpack encoder/decoder"
src="w/wavpack/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
This package contains the WavPack command-line programs and the WavPack library.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
