#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gal
version=0.24
group=Libraries/gnome
license=LGPLv2.1
description="Gnome application library"
src="g/gal/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The GAL package contains library functions that came from Evolution and
Gnumeric. GAL is short for GNOME Application Libs.
EOF
}

buildPhase()
{
    CPPFLAGS='-I/opt/gnome/include' \
      ./configure --prefix=/opt/gnome-$gnomeVersion --enable-shared
    make
}

installPhase()
{
    make install
}
