#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=glib
version=1.2.10
group=Libraries/gnome
license=LGPLv2.1
description="GLib"
src="g/glib/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
GLib is a general-purpose, portable utility library, which provides many useful
data types, macros, type conversions, string utilities, file utilities, a
mainloop abstraction, and so on.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnomeVersion \
      --mandir=/opt/gnome-$gnomeVersion/share/man \
      --infodir=/opt/gnome-$gnomeVersion/share/info
    make
}

installPhase()
{
    make install
    ln -sfn /opt/gnome-$gnomeVersion /opt/gnome
    mkdir -p /etc/opt/gnome-$gnomeVersion
    ln -sfn /etc/opt/gnome-$gnomeVersion /etc/opt/gnome

    install -m755 $cbtBaseDir/profile.d/20gnome.sh /etc/profile.d
    if which csh
    then
        install -m755 $cbtBaseDir/profile.d/20gnome.csh /etc/profile.d
    fi
}
