#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-print
version=0.35
group=Libraries/gnome
license=LGPLv2.1
description="GNOME printing"
src="g/gnome-print/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Contains an implementation of the GNOME printing architecture.
EOF
}

buildPhase()
{
    CPPFLAGS='-I/opt/gnome/include' \
      ./configure --prefix=/opt/gnome-$gnomeVersion --sysconfdir=/etc/opt/gnome-$gnomeVersion --enable-shared
    make
}

installPhase()
{
    make install
}
