#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnomemm
version=1.2.2
group=Libraries/gnome
license=GPLv2
description="C++ wrapper for GNOME UI"
src="g/gnomemm/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
This package provides a C++ for GNOME UI. It is a sub package of the Gtk--
project. The interface provides a convenient interface for C++ programmers to
create GNOME GUIs with GTK+'s flexible object-oriented framework.
EOF
}

# '

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnomeVersion
    make
}

installPhase()
{
    make install
}
