#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-vfs
version=1.0.5
group=Libraries/gnome
license=LGPLv2.1
description="GNOME VFS"
src="g/gnome-vfs/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Gnome VFS (short for GNOME Virtual File System) is an abstraction layer of the
GNOME platform for the reading, writing and execution of files.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnomeVersion \
      --sysconfdir=/etc/opt/gnome-$gnomeVersion \
      --mandir=/opt/gnome-$gnomeVersion/share/man \
      --enable-shared
    make
}

installPhase()
{
    make install
}
