#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gtk+
version=1.2.10
group=Libraries/gnome
license=LGPLv2.1
description="GTK+ toolkit"
src="g/gtk+/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
GTK+ is a free open-source widget toolkit for creating graphical user interfaces
targeted at Linux and specifically GNOME (though with some use in other desktop
environments).
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnomeVersion \
      --sysconfdir=/etc/opt/gnome-$gnomeVersion \
      --mandir=/opt/gnome-$gnomeVersion/share/man \
      --infodir=/opt/gnome-$gnomeVersion/share/info
    make
}

installPhase()
{
    make install
}
