#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=librsvg
version=1.0.2
group=Libraries/gnome
license=LGPLv2.1
description="SVG parser library"
src="l/librsvg/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
librsvg is a free software SVG rendering library written as part of the GNOME
project, intended to be lightweight and portable.
EOF
}

buildPhase()
{
    CPPFLAGS='-I/opt/gnome/include' \
      ./configure --prefix=/opt/gnome-$gnomeVersion --enable-shared
    make
}

installPhase()
{
    make install
}
