#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=compress
version=4.0
group=Tools/Packers
license=PD
description="LZW compress tool"
src="c/compress/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Compress is a fast, simple LZW file compressor. Compress does not have the
highest compression rate, but it is one of the fastest programs to compress
data. Compress is the defacto standard in the UNIX community for compressing
files.
EOF
}

buildPhase()
{
    echo 0 > USERMEM
    make
}

installPhase()
{
    cp -v compress atob btoa /usr/bin
    cp -v compress.1 btoa.1 /usr/share/man/man1
}
