#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=rpm
version=4.0.4
group=Tools/Packers
license=GPLv2
description="RPM package manager"
src="r/rpm/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
RPM (RPM Package Manager) is a free and open-source package management system.
The name RPM refers to the .rpm file format and the package manager program
itself. RPM was intended primarily for Linux distributions; the file format is
the baseline package format of the Linux Standard Base.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install
    rpm --initdb
    rpm --rebuilddb
}
