#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gedit
version=0.9.7
group=Desktops/gnome
license=GPLv2
description="GNOME editor"
src="g/gedit/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
gedit is a text editor for X using the GTK+ and GNOME libraries.
EOF
}

buildPhase()
{
    ./configure --prefix=/opt/gnome-$gnomeVersion --enable-shared
    make
}

installPhase()
{
    make install
}
