#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=gnome-games
version=1.4.0.4
group=Desktops/gnome
license=GPLv2
description="GNOME games"
src="g/gnome-games/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
A collection of games for the GNOME desktop.
EOF
}

buildPhase()
{
    CPPFLAGS='-I/opt/gnome/include' \
      ./configure --prefix=/opt/gnome-$gnomeVersion \
      --sysconfdir=/etc/opt/gnome-$gnomeVersion \
      --localstatedir=/var/lib --enable-shared
    make
}

installPhase()
{
    make install
}
