#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=mtools
version=3.9.8
group=Tools/Misc
license=GPLv2
description="MS-DOS floppy and filesystem tools"
src="m/mtools/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Mtools is a collection of utilities to access MS-DOS disks from GNU and Unix
without mounting them. It supports Win'95 style long file names, OS/2 Xdf disks
and 2m disks (store up to 1992k on a high density 3 1/2 disk). In addition to
file access, it supports many FAT-specific features: volume labels, FAT-specific
file attributes (hidden, system, ...), "bad block" map maintenance, access to
remote floppy drives, Iomega ZIP disk protection, "secure" erase, display of
file's on-disk layout, etc.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --sysconfdir=/etc
    make
}

installPhase()
{
    make install
}
