#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=sharutils
version=4.2.1
group=Tools/Misc
license=GPLv2
description="GNU Shell Archive utilities"
src="s/sharutils/$name-$version.tar.gz"
patches=("s/sharutils/$name-$version-gettext-1.patch" "s/sharutils/$name-$version-vulnerability_fix-1.patch")

showLongDescription()
{
    cat << "EOF"
shar makes so-called shell archives out of many files, preparing
them for transmission by electronic mail services. unshar helps
unpacking shell archives after reception.

uuencode prepares a file for transmission over an electronic channel
which ignores or otherwise mangles the eight bit (high order bit) of
bytes. uudecode does the converse transformation.

remsync allows for remote synchronization of directory trees,
using electronic mail. This part of sharutils is still alpha.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make
}

installPhase()
{
    make install
}
