#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=Gtk-Perl
version=0.7008
group=Libraries/Perl
license=LGPLv2
description="GTK+ bindings for Perl"
src="g/Gtk-Perl/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
GTK-Perl is the collective name for a set of perl bindings for GLib, GTK+, and
various related libraries. These modules make it easy to write Gtk and Gnome
applications using a natural, perlish, object-oriented syntax.
EOF
}

buildPhase()
{
    perl Makefile.PL --without-guessing
    make
}

installPhase()
{
    make install
}
