#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=PDL
version=2.3.4
group=Libraries/Perl
license=AL
description="Perl Data Language"
src="p/PDL/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
PDL is the Perl Data Language, a perl extension that is designed for scientific
and bulk numeric data processing and display. It extends perl's syntax and
includes fully vectorized, multidimensional array handling, plus several paths
for device-independent graphics output.
EOF
}

# '

buildPhase()
{
    perl Makefile.PL
    make
}

installPhase()
{
    make install
}
