#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=XML-Writer
version=0.4
group=Libraries/Perl
license=AL
description="XML file writing support for Perl"
src="x/XML-Writer/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
XML::Writer is a helper module for Perl programs that write an XML document.
The module handles all escaping for attribute values and character data and
constructs different types of markup, such as tags, comments, and processing
instructions.
EOF
}

buildPhase()
{
    perl Makefile.PL
    make
}

installPhase()
{
    make install
}
