#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xmms-wma
version=1.0.5
group=Applications
license=GPLv2
description="WMA input plugin for XMMS"
src="x/xmms-wma/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Plug-in of support of format WMA V1/V2 for XMMS using ffmpeg code.
EOF
}

buildPhase()
{
    make
}

installPhase()
{
    make INSTALL_DIR=/opt/gnome/lib/xmms/Plugins install
}
