#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=ncompress
version=4.2.4.4
group=Tools/Packers
license=PD
description="LZW compress tool"
src="n/ncompress/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Compress is a fast, simple LZW file compressor. Compress does not have the
highest compression rate, but it is one of the fastest programs to compress
data. Compress is the defacto standard in the UNIX community for compressing
files.
EOF
}

buildPhase()
{
    make
}

installPhase()
{
    cp -v compress /usr/bin
    ln -s compress /usr/bin/uncompress
    cp -v compress.1 /usr/share/man/man1
}
