#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=sharutils
version=4.10
group=Tools/Packers
license=GPLv3
description="GNU Shell Archive utilities"
src="s/sharutils/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
shar makes so-called shell archives out of many files, preparing
them for transmission by electronic mail services. unshar helps
unpacking shell archives after reception.

uuencode prepares a file for transmission over an electronic channel
which ignores or otherwise mangles the eight bit (high order bit) of
bytes. uudecode does the converse transformation. They are derived
from the BSD NET/2 distribution, but enchanced with the features
described in recent POSIX standards.

remsync allows for remote synchronization of directory trees,
using electronic mail. This part of sharutils is still alpha.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
