#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=zip
version=3.0
group=Tools/Packers
license=info-zip
description="Zip from Info-Zip"
src="z/zip/${name}30.tar.gz"

showLongDescription()
{
    cat << "EOF"
Package containing a compressor/archiver for creating and modifying zipfiles.
EOF
}

buildPhase()
{
    make -f unix/Makefile generic_gcc
}

installPhase()
{
    make prefix=/usr -f unix/Makefile install
}
