#!/bin/bash -e

source $cbtFunctionsDir/deployXDGDesktopSourcePackage
source $cbtBaseDir/settings/extra-settings

name=dosbox
version=0.73
license=GPLv2
group=Emulators
description="DOS emulator with internal DOS"
src="d/dosbox/$name-$version.tar.gz"

desktopTargetDir="/usr/share/applications"
desktopName="DOSBox"
genericName="DOS emulator"
exec="dosbox"
comment="DOS emulator with internal DOS"
categories="Emulator;"

showLongDescription()
{
    cat << "EOF"
DOSBox is an emulator that recreates a MS-DOS compatible environment (complete
with Sound, Input, Graphics and even basic networking). This environment is
complete enough to run many classic MS-DOS games completely unmodified.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
