#!/bin/bash -e

source $cbtFunctionsDir/deployXDGDesktopSourcePackage
source $cbtBaseDir/settings/extra-settings

name=uae
version=0.8.29
license=GPLv2
group=Emulators
description="Ultimate Amiga Emulator"
src="u/uae/$name-$version.tar.bz2"

desktopTargetDir="/usr/local/share/applications"
desktopName="UAE"
genericName="Amiga emulator"
exec=uae
comment="Ultimate Amiga Emulator"
categories="Emulator;"

showLongDescription()
{
    cat << "EOF"
UAE is a computer emulator which emulates the hardware of Commodore
International's Amiga range of computers. This version of UAE is the original
core distribution.
EOF
}

# '

buildPhase()
{
    ./configure --with-alsa --with-sdl --with-sdl-gfx
    make $globalBuildOptions
}

installPhase()
{
    make install
}
