#!/bin/bash -e

source $cbtFunctionsDir/deployXDGDesktopSourcePackage
source $cbtBaseDir/settings/extra-settings

name=VisualBoyAdvance
version=1.7.2
license=GPLv2
group=Emulators
description="Gameboy, Gameboy Color and Advance emulator"
src="v/VisualBoyAdvance/$name-src-$version.tar.gz"

desktopTargetDir="/usr/local/share/applications"
desktopName="Visual Boy Advance"
exec="VisualBoyAdvance"
comment="GB, GBC, GBA Emulator"
mimeType="application/x-gameboy-rom;application/x-gba-rom"
categories="Emulator;"
noDisplay=true

showLongDescription()
{
    cat << "EOF"
This is a GB/GBC/GBA emulator for Windows, Linux, MacOS X and BeOS.
EOF
}

buildPhase()
{
    ./configure --sysconfdir=/etc
    make $globalBuildOptions
}

installPhase()
{
    make install

    if [ -d /opt/kde/share/mimelnk ]
    then
        mkdir -p /opt/kde/share/mimelnk/emulators
        cd /opt/kde/share/mimelnk/emulators

        cat > gb.desktop << "EOF"
[Desktop Entry]
Type=MimeType
Comment=Gameboy ROM
MimeType=application/x-gameboy-rom
Icon=binary
Patterns=*.gb;*.GB;*.gbc;*.GBC
EOF

    cat > gba.desktop << "EOF"
[Desktop Entry]
Type=MimeType
Comment=Gameboy Advance ROM
MimeType=application/x-gba-rom
Icon=binary
Patterns=*.gba;*.GBA
EOF
    fi
}
