#!/bin/bash -e

source $cbtBaseDir/settings/extra-settings

name=wine-config
group=Emulators
description="Global configuration settings for WINE"

execute()
{
    echo "MANDATORY_MANPATH /opt/wine/share/man" >> /etc/man_db.conf
    echo "/opt/wine/lib" >> /etc/ld.so.conf
    ldconfig
}
