#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=util-macros
version=1.1.5
group=Display/X11/util
license=MIT
description="util-macros"
src="x/xorg/util/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
X.org generated util package: util-macros
EOF
}

buildPhase()
{
    ./configure $XORG_CONFIG --with-xorg-module-dir=/usr/X11R7.3/lib/X11/modules
    make
}

installPhase()
{
    make install
}
