#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=xterm
version=230
group=Display/X11
license=MIT
description="Terminal emulator for X"
src="x/xorg/$name-$version.tgz"

showLongDescription()
{
    cat << "EOF"
xterm is the standard terminal emulator for the X Window System. It allows users
to run programs which require a command-line interface.
EOF
}

buildPhase()
{
    TERMINFO=/usr/lib/terminfo ./configure $XORG_CONFIG \
        --enable-luit --enable-wide-chars \
        --with-app-defaults=/etc/X11/app-defaults
    make $globalBuildOptions
}

installPhase()
{
    make install
    make install-ti
}
