#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=polkit
version=0.94
group=Services
license=LGPLv2
description="polkit service"
src="p/polkit/$name-$version.tar.gz"
patches=("p/polkit/$name-$version-fix_namespace_conflicts-1.patch")
showLongDescription()
{
    cat << "EOF"
PolicyKit is a toolkit for defining and handling authorizations. It
is used for allowing unprivileged processes to speak to privileged
processes.
EOF
}

preConfigurePhase()
{
    # Create users and groups
    groupadd -g 27 polkitd
    useradd -c "PolicyKit Daemon Owner" -d /etc/polkit-1 -u 27 -g polkitd -s /bin/false polkitd
}

buildPhase()
{
    ./configure --prefix=/usr \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --libexecdir=/usr/lib/polkit-1
    make $globalBuildOptions
}

installPhase()
{
    make install

    cat > /etc/pam.d/polkit-1 << "EOF"
# Begin /etc/pam.d/polkit-1

auth     include        system-auth
account  include        system-account
password include        system-password
session  include        system-session

# End /etc/pam.d/polkit-1
EOF
}
