#!/bin/bash -e

source $cbtBaseDir/settings/lfs-settings

name=create-optimize-env-setting
group=lfs-stage2
description="Creates a profile.d file that provides compiler optimizations"

execute()
{
    if [ "$CFLAGS" != "" ]
    then
        mkdir -p /etc/profile.d
        echo "export CFLAGS=\"$CFLAGS\"" >> /etc/profile.d/01optimize.sh
        chmod 755 /etc/profile.d/01optimize.sh
    fi

    if [ "$CXXFLAGS" != "" ]
    then
        mkdir -p /etc/profile.d
        echo "export CXXFLAGS=\"$CXXFLAGS\"" >> /etc/profile.d/01optimize.sh
        chmod 755 /etc/profile.d/01optimize.sh
    fi
}
