#!/bin/bash -e

source $cbtBaseDir/settings/lfs-settings

name=create-essential-files-and-links
group=lfs-stage2
description="Creates essential files and symlinks"

execute()
{
    ln -sfnv /tools/bin/{bash,cat,echo,pwd,stty} /bin
    ln -sfnv /tools/bin/perl /usr/bin
    ln -sfnv /tools/lib/libgcc_s.so{,.1} /usr/lib
    ln -sfnv /tools/lib/libstdc++.so{,.6} /usr/lib
    ln -sfnv bash /bin/sh

    touch /etc/mtab

    cat > /etc/passwd << "EOF"
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/bin/false
nobody:x:99:99:Unprivileged User:/dev/null:/bin/false
lfs:x:998:998:LFS:/dev/null:/bin/bash
EOF

# Some groups were added: users, netdev

    cat > /etc/group << "EOF"
root:x:0:
bin:x:1:
sys:x:2:
kmem:x:3:
tty:x:4:
tape:x:5:
daemon:x:6:
floppy:x:7:
disk:x:8:
lp:x:9:
uucp:x:10:
audio:x:11:
video:x:12:
utmp:x:13:
usb:x:14:
cdrom:x:15:
mail:x:34:
netdev:x:86:
nogroup:x:99:
users:x:100:
lfs:x:998:
EOF

    touch /var/run/utmp /var/log/{btmp,lastlog,wtmp}
    chgrp -v utmp /var/run/utmp /var/log/lastlog
    chmod -v 664 /var/run/utmp /var/log/lastlog
}
