#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/diffutils

group=lfs-stage2
patches=("d/diffutils/$name-$version-i18n-1.patch")

buildPhase()
{
    touch man/diff.1

    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
