#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/e2fsprogs

group=lfs-stage2

buildPhase()
{
    # Fix a hardcoded path to /bin/rm in E2fsprogs' testsuite
    sed -i 's@/bin/rm@/tools&@' lib/blkid/test_probe.in

    mkdir -v build
    cd build

    ../configure --prefix=/usr --with-root-prefix="" \
        --enable-elf-shlibs
    make $globalBuildOptions
}

installPhase()
{
    cd build

    make install
    make install-libs

    chmod -v u+w /usr/lib/{libblkid,libcom_err,libe2p,libext2fs,libss,libuuid}.a

    gunzip -v /usr/share/info/libext2fs.info.gz
    install-info --dir-file=/usr/share/info/dir \
                 /usr/share/info/libext2fs.info

    makeinfo -o doc/com_err.info ../lib/et/com_err.texinfo
    install -v -m644 doc/com_err.info /usr/share/info
    install-info --dir-file=/usr/share/info/dir \
             /usr/share/info/com_err.info
    install -v -m644 -D ../doc/libblkid.txt \
        /usr/share/doc/e2fsprogs-1.41.3/libblkid.txt
}
