#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings

name=file
version=4.26
description="File"
group=lfs-stage2
license=BSD
src="f/file/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
The file command is "a file type guesser", that is, a command-line tool that
tells you in words what kind of data a file contains. This command doesn't rely
on filename extentions to tell you the type of a file, but looks at the file's
actual contents.
EOF
}

buildPhase()
{
    # Fix the man page so that it will reflect recent changes to the -e (--exclude) parameter:
    sed -i -e '197,+1d' \
        -e '189,+1d' \
        -e 's/token$/tokens/' doc/file.man

    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
}
