#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings

name=flex
version=2.5.35
group=lfs-stage2
description="Flex"
license=BSD
src="f/flex/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
Flex (fast lexical analyzer generator) is a free and open-source software
alternative to lex. It is a computer program that generates lexical analyzers
(also known as "scanners" or "lexers").

It is frequently used as the lex implementation together with Berkeley Yacc
or GNU bison parser generators.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
    ln -sfv libfl.a /usr/lib/libl.a

    cat > /usr/bin/lex << "EOF"
#!/bin/sh
# Begin /usr/bin/lex

exec /usr/bin/flex -l "$@"

# End /usr/bin/lex
EOF
chmod -v 755 /usr/bin/lex

    mkdir -pv /usr/share/doc/$name-$version
    cp -v doc/flex.pdf \
        /usr/share/doc/$name-$version
}
