#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/gawk

group=lfs-stage2

buildPhase()
{
    ./configure --prefix=/usr --libexecdir=/usr/lib \
        ac_cv_func_working_mktime=yes
    make $globalBuildOptions
}

installPhase()
{
    make install

    mkdir -pv /usr/share/doc/$name-$version
    cp -v doc/{awkforai.txt,*.{eps,pdf,jpg}} \
        /usr/share/doc/$name-$version
}
