#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/gettext

group=lfs-stage2

buildPhase()
{
    ./configure --prefix=/usr \
        --docdir=/usr/share/doc/$name-$version
    make $globalBuildOptions
}

installPhase()
{
    make install
}
