#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/grep

group=lfs-stage2
patches=("g/grep/$name-$version-debian_fixes-1.patch" "g/grep/$name-$version-upstream_fixes-1.patch")

buildPhase()
{
    ./configure --prefix=/usr \
        --bindir=/bin \
        --without-included-regex
    make $globalBuildOptions
}

installPhase()
{
    make install
}
