#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings

name=iproute2
version=2.6.26
group=lfs-stage2
description="IP networking tools"
license=GPLv2
src="i/iproute2/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The IPRoute2 package contains programs for basic and advanced IPv4-based
networking.
EOF
}

buildPhase()
{
    make DESTDIR= SBINDIR=/sbin
}

installPhase()
{
    make DESTDIR= SBINDIR=/sbin MANDIR=/usr/share/man \
        DOCDIR=/usr/share/doc/$name-$version install

    mv -v /sbin/arpd /usr/sbin
}
