#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings

name=lfs-bootscripts
version=20081031
group=lfs-stage2
description="LFS Bootscripts"
license=BSD
src="l/lfs-bootscripts/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The LFS-Bootscripts package contains a set of scripts to start/stop the LFS
system at bootup/shutdown.
EOF
}

buildPhase()
{
    true
}

installPhase()
{
    make install
}
