#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings

name=Linux-PAM
version=1.0.3
group=lfs-stage2
license=BSD-3
description="Pluggable Authentication Modules"
srcs=("l/Linux-PAM/$name-$version.tar.bz2" "l/Linux-PAM/$name-$version-docs.tar.bz2")

showLongDescription()
{
    cat << "EOF"
Linux Pluggable Authentication Modules (PAM) is a suite of libraries that allow
a Linux system administrator to configure methods to authenticate users. It
provides a flexible and centralized way to switch authentication methods for
secured applications by using configuration files instead of changing
application code.
EOF
}

buildPhase()
{
    ./configure --sbindir=/lib/security \
            --docdir=/usr/share/doc/$name-$version \
            --enable-read-both-confs
    make $globalBuildOptions
}

installPhase()
{
    make install

    chmod -v 4755 /lib/security/unix_chkpwd

    mv -v /lib/security/pam_tally /sbin

    mv -v /lib/libpam{,c,_misc}.la /usr/lib
    sed -i 's| /lib| /usr/lib|' /usr/lib/libpam_misc.la

    if [ -L /lib/libpam.so ]
    then
        for LINK in libpam{,c,_misc}.so
        do
            ln -v -sf ../../lib/$(readlink /lib/${LINK}) /usr/lib/${LINK}
            rm -v /lib/${LINK}
        done
    fi
}
