#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/m4

group=lfs-stage2

buildPhase()
{
    ./configure --prefix=/usr # LFS 6.4 errate says this should be removed: --enable-threads
    make $globalBuildOptions
}

installPhase()
{
    make install
}
