#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/perl

group=lfs-stage2

buildPhase()
{
    # Use shared zlib, rather than the internal copy
    #sed -i -e "s|BUILD_ZLIB\s*= True|BUILD_ZLIB = False|"           \
    #   -e "s|INCLUDE\s*= ./zlib-src|INCLUDE    = /usr/include|" \
    #   -e "s|LIB\s*= ./zlib-src|LIB        = /usr/lib|"         \
    #ext/Compress/Raw/Zlib/config.in

    sh Configure -des -Dprefix=/usr \
                      -Dvendorprefix=/usr \
                      -Dman1dir=/usr/share/man/man1 \
                      -Dman3dir=/usr/share/man/man3 \
                      -Dpager="/usr/bin/less -isR"
    make $globalBuildOptions
}

installPhase()
{
    make install
}
