#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/sed

group=lfs-stage2

buildPhase()
{
    ./configure --prefix=/usr --bindir=/bin --enable-html
    make $globalBuildOptions
    make html
}

installPhase()
{
    make install
}
