#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings

name=shadow
version=4.1.2.1
group=lfs-stage2
description="Shadow password suite"
license=BSD
src="s/shadow/$name-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
The Shadow Password Suite consists of a collection of library modules and
administrative utilities which provide for enhanced system security.
EOF
}

buildPhase()
{
    # Disable the installation of the groups program because coreutils provides a better version
    sed -i 's/groups$(EXEEXT) //' src/Makefile.in
    find man -name Makefile.in -exec sed -i 's/groups\.1 / /' {} \;

    # Disable the installation of Chinese and Korean manpages, as man-db cannot format them properly
    sed -i -e 's/ ko//' -e 's/ zh_CN zh_TW//' man/Makefile.in

    # Shadow supplies other manual pages in a UTF-8 encoding. Man-DB can display these in the recommended encodings by using the convert-mans script which was installed during the Man-DB package:
    for i in de es fi fr id it pt_BR; do
        convert-mans UTF-8 ISO-8859-1 man/${i}/*.?
    done

    for i in cs hu pl; do
        convert-mans UTF-8 ISO-8859-2 man/${i}/*.?
    done

    convert-mans UTF-8 EUC-JP man/ja/*.?
    convert-mans UTF-8 KOI8-R man/ru/*.?
    convert-mans UTF-8 ISO-8859-9 man/tr/*.?

    # Instead of using the default crypt method, use the more secure MD5 of password encryption
    sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD MD5@' \
       -e 's@/var/spool/mail@/var/mail@' etc/login.defs

    ./configure --sysconfdir=/etc
    make $globalBuildOptions
}

installPhase()
{
    make install
    mv -v /usr/bin/passwd /bin

    # Additional PAM configuration steps from BLFS book

    # Change login config to use PAM modules
    install -v -m644 /etc/login.defs /etc/login.defs.orig

    for FUNCTION in LASTLOG_ENAB MAIL_CHECK_ENAB \
                    PORTTIME_CHECKS_ENAB CONSOLE \
                    MOTD_FILE NOLOGINS_FILE PASS_MIN_LEN \
                    SU_WHEEL_ONLY MD5_CRYPT_ENAB \
                    CONSOLE_GROUPS ENVIRON_FILE \
                    ULIMIT ENV_TZ ENV_HZ ENV_SUPATH \
                    ENV_PATH QMAIL_DIR MAIL_DIR MAIL_FILE \
                    CHFN_AUTH FAILLOG_ENAB QUOTAS_ENAB FTMP_FILE \
                    OBSCURE_CHECKS_ENAB CRACKLIB_DICTPATH \
                    PASS_CHANGE_TRIES PASS_ALWAYS_WARN ISSUE_FILE
    do
        sed -i "s/^$FUNCTION/# &/" /etc/login.defs
    done

    # Create PAM configuration files

    mkdir -p /etc/pam.d

    cat > /etc/pam.d/login << "EOF"
# Begin /etc/pam.d/login

auth        requisite      pam_nologin.so
auth        required       pam_securetty.so
auth        required       pam_env.so
auth        required       pam_unix.so
account     required       pam_access.so
account     required       pam_unix.so
session     required       pam_motd.so
session     required       pam_limits.so
session     optional       pam_mail.so      dir=/var/mail standard
session     optional       pam_lastlog.so
session     required       pam_unix.so
password    required       pam_unix.so      md5 shadow

# End /etc/pam.d/login
EOF

    cat > /etc/pam.d/passwd << "EOF"
# Begin /etc/pam.d/passwd

password    required       pam_unix.so      md5 shadow

# End /etc/pam.d/passwd
EOF

    cat > /etc/pam.d/su << "EOF"
# Begin /etc/pam.d/su

auth        sufficient      pam_rootok.so
auth        required        pam_unix.so
account     required        pam_unix.so
session     optional        pam_mail.so     dir=/var/mail standard
session     optional        pam_xauth.so
session     required        pam_env.so
session     required        pam_unix.so

# End /etc/pam.d/su
EOF

    cat > /etc/pam.d/chage << "EOF"
# Begin /etc/pam.d/chage

auth        sufficient      pam_rootok.so
auth        required        pam_unix.so
account     required        pam_unix.so
session     required        pam_unix.so
password    required        pam_permit.so

# End /etc/pam.d/chage
EOF

    for PROGRAM in chfn chgpasswd chpasswd chsh groupadd groupdel \
                   groupmems groupmod newusers useradd userdel usermod
    do
        install -v -m644 /etc/pam.d/chage /etc/pam.d/$PROGRAM
        sed -i "s/chage/$PROGRAM/" /etc/pam.d/$PROGRAM
    done

    cat > /etc/pam.d/other << "EOF"
# Begin /etc/pam.d/other

auth        required        pam_deny.so
auth        required        pam_warn.so
account     required        pam_deny.so
account     required        pam_warn.so
password    required        pam_deny.so
password    required        pam_warn.so
session     required        pam_deny.so
session     required        pam_warn.so

# End /etc/pam.d/other
EOF

    # The /etc/login.access file is not used, because it is now controlled by pam_access.so
    if [ -f /etc/login.access ]
    then
        mv -v /etc/login.access /etc/login.access.NOUSE
    fi

    # The /etc/limits file is not used, because it is now controlled by pam_limits.so
    if [ -f /etc/limits ]
    then
        mv -v /etc/limits /etc/limits.NOUSE
    fi

    # During previous configuration, several items were removed from
    # /etc/login.defs. Some of these items are now
    # controlled by the pam_env.so
    # module and the /etc/security/pam_env.conf
    # configuration file.  In particular, the default path has been
    # changed.
    ENV_PATH=`grep '^ENV_PATH' /etc/login.defs.orig | \
        awk '{ print $2 }' | sed 's/PATH=//'`
    echo 'PATH        DEFAULT='`echo "${ENV_PATH}"`\
    '        OVERRIDE=${PATH}' \
        >> /etc/security/pam_env.conf
    unset ENV_PATH

    # Disable the creation of new mailbox files for new users and change
    # default group to 100 (last aspect is not in the LFS book, but fixes an
    # annoying issue
    sed -i -e 's/yes/no/' \
        -e 's/1000/100/' \
        /etc/default/useradd

}
