#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings
source $cbtBaseDir/meta/tar

group=lfs-stage2

buildPhase()
{
    ./configure --prefix=/usr --bindir=/bin --libexecdir=/usr/sbin
    make $globalBuildOptions
}

installPhase()
{
    make install
}
