#!/bin/bash -e

source $cbtBaseDir/settings/lfs-settings

name=vim-configure
group=lfs-stage2
description="Creates a basic vim config"

execute()
{
    cat > /etc/vimrc << "EOF"
" Begin /etc/vimrc

set nocompatible
set backspace=2
syntax on
if (&term == "iterm") || (&term == "putty")
  set background=dark
endif

" End /etc/vimrc
EOF
}
