#!/bin/bash -e

source $cbtFunctionsDir/deployStage2SourcePackage
source $cbtBaseDir/settings/lfs-settings

name=zlib-static
version=1.2.3
group=lfs-stage2
description="static zlib compression library"
license=zlib
src="z/zlib/zlib-$version.tar.bz2"

showLongDescription()
{
    cat << "EOF"
zlib is designed to be a free, general-purpose, legally unencumbered lossless
data-compression library for use on virtually any computer hardware and
operating system. The zlib data format is itself portable across platforms.

This package provides a compiled static library.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr
    make $globalBuildOptions
}

installPhase()
{
    make install
    chmod -v 644 /usr/lib/libz.a
}
