#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=dash
version=0.5.4
group=Tools/Shells
license=BSD-3
description="Debian Almquist Shell"
src="d/dash/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
dash is a shell that is the most compliant with the Bourne Shell (not to be
confused with bash: the Bourne Again SHell) without any extra features.

Bourne Shell is available of most commercial UNIX systems. dash can be useful
for testing scripts to be sh-compliant. It can also be used as a lightweight
shell as it has a small memory and storage footprint compared to most other
sh-compliant shells.
EOF
}

buildPhase()
{
    ./configure --bindir=/bin --mandir=/usr/share/man
    make $globalBuildOptions
}

installPhase()
{
    make install

    mkdir -p /usr/lib/ul-adduser
    cat > /usr/lib/ul-adduser/dash << "EOF"
shellPath=/bin/dash
description="Debian Almquist SHell"
EOF
}
