#!/bin/bash -e

source $cbtFunctionsDir/deploySourcePackage
source $cbtBaseDir/settings/ul-packages-settings

name=tcsh
version=6.16.00
group=Tools/Shells
license=BSD
description="TENEX C shell"
src="t/tcsh/$name-$version.tar.gz"

showLongDescription()
{
    cat << "EOF"
Tcsh is a version of the Berkeley C-Shell with the addition of a command line
editor, command and file name completion, listing etc. and a bunch of small
additions to the shell itself.
EOF
}

buildPhase()
{
    ./configure --prefix=/usr --bindir=/bin
    make $globalBuildOptions
    sh ./tcsh.man2html
}

installPhase()
{
    make install

    cp tcsh.man /usr/share/man/man1/tcsh.1
    ln -v -sf tcsh /bin/csh
    ln -v -sf tcsh.1 /usr/share/man/man1/csh.1
    install -v -m755 -d /usr/share/doc/$name-$version/html
    install -v -m644 tcsh.html/* /usr/share/doc/$name-$version/html
    install -v -m644 FAQ         /usr/share/doc/$name-$version

    cat > /etc/csh.login << "EOF"
# Begin /etc/csh.login

foreach script (/etc/profile.d/*.csh)
    source "$script"
end

# End /etc/csh.login
EOF

    cat > /etc/csh.cshrc << "EOF"
# Begin /etc/cshrc

# Provides a colored /bin/ls command
alias ls 'ls --color=auto'

# Configure prompt
set prompt = '[%n@%m %c]$ '

# End /etc/cshrc
EOF

    install -m755 $cbtBaseDir/profile.d/00base.csh /etc/profile.d

    if [ "$CFLAGS" != "" ]
    then
        echo "setenv CFLAGS \"$CFLAGS\"" > /etc/profile.d/01optimize.csh
        chmod 755 /etc/profile.d/01optimize.csh
    fi

    if [ "$CXXFLAGS" != "" ]
    then
        echo "setenv CXXFLAGS \"$CXXFLAGS\"" >> /etc/profile.d/01optimize.csh
        chmod 755 /etc/profile.d/01optimize.csh
    fi

    install -m755 $cbtBaseDir/profile.d/02pkg-config.csh /etc/profile.d

    mkdir -p /usr/lib/ul-adduser
    cat > /usr/lib/ul-adduser/tcsh << "EOF"
shellPath=/bin/tcsh
description="TENEX C-SHell"
EOF

    cat > /usr/lib/ul-adduser/csh << "EOF"
shellPath=/bin/csh
description="Generic C-compatible shell"
EOF
}
