#!/bin/bash -e

source $cbtFunctionsDir/deployDesktopSourcePackage
source $cbtBaseDir/settings/slackware-8.0

name=xbill
version=2.1
group=Games
license=GPLv2
description="XBill"
src="x/xbill/$name-$version.tar.gz"

desktopName="XBill"
category=Games
exec=/usr/local/bin/xbill
comment="XBill"
icon=/opt/gnome/share/pixmaps/xbill.png

showLongDescription()
{
    cat << "EOF"
XBill is an arcade style game for the X Window System. The game features a
bespectacled character known as "Bill". The goal is to prevent Bill's legions of
clones from installing "Wingdows", a virus "cleverly designed to resemble a
popular operating system", on a variety of computers running other operating
systems.
EOF
}

# '

buildPhase()
{
    CPPFLAGS='-I/usr/X11R6/include' ./configure
    make
}

installPhase()
{
    make install
}
